src/lib/platform/MSWindowsDesks.cpp

Fixes issue #4349 in MSWindowsDesks.cpp by using HWND_TOP instead of HWND_TOPMOST. All credit for this fix goes to @gitscrubz and @dubuaych

Fix #4349 - Bringing windows to front

---

src/lib/platform/OSXScreen.cpp
src/lib/platform/OSXScreen.h

This patch corrects issues with double click and adds triple click to
MacOSX. Double click was functioning but double clicking and then
dragging would not work.
Triple clicking now selects an entire line and double clicking and dragging now adds words to the selection correctly.
Fixes Bug: 3784

Double click breaks dragging and tripple click on Mac

---

src/gui/res/MainWindowBase.ui

The shortcut for the server checkbox on the main gui is now Alt-V. This deconflicts the start/stop button.
Fixes #4367

Changed server shortcut on GUI main window

---

src/lib/platform/OSXKeyState.cpp
src/lib/platform/OSXKeyState.h
src/lib/platform/OSXScreen.cpp

On MacOSX modifier keys will often stick. I was able to verify that modifier state in the Synergy client is correct and the system modifier state is incorrect. Furthermore, I was able to verify that an event is posted to the operating system for the key up event. 
After determining that Synergy is in the correct state, I attempted to fix this issue by asking the operating system what its modifier state was before every event was sent and then sending extra events to correct the systems modifier state if it was incorrect. This solution worked but after looking at the log of corrections, it became evident that this code was only required to correct mouse events. This was due to the fact that all key events pass the modifier state along with them. So the final solution was to remove the …

Modifier keys often stuck down on Mac client

---

src/gui/src/WebClient.cpp

Corrected a small typo concerning an error message I received myself while using synergy.

Typo 'occurred' in WebClient.cpp

---

src/gui/src/PluginManager.cpp

Fixes "Plugin download fails on CentOS with 'Could not get Linux package type' error" (see issue synergy/synergy#4720) according to @nbolton suggestion.
It has been succesfully built, packaged and tested with success on my centos 6.5 machine. It means that the ns plugin is now correctly downloaded on centos 6.5 and ssl encryption is available again.

Fix issue synergy/synergy#4720

---

src/lib/net/SocketMultiplexer.cpp

I've encountered Issue #2866 in 1.6.1, so patch from tracker is still actual.
Detailed steps and investigation is in the issue: https://github.com/synergy/synergy/issues/2866#issuecomment-58849356

High client CPU usage and laggy mouse

---

src/setup/win32/Product.wxs

The WiX `CompanionFile` attribute was causing the installer to be confused, logging:
``Won't Overwrite; Won't patch; Existing file is unversioned but modified``
and hence not installing a bunch of the DLLs in some cases.
Removing this attribute makes the installer work as expected again on a machine which previously reproduced #3774.
@nbolton @XinyuHou please review
P.S. this is my first PR to Synergy so please tell me if I'm doing anything wrong, or if I need to kick off a build etc...! :smiley:

Fix missing DLLs after install #3774

---

src/micro/uSynergy.h

I was unable to compile on Solaris 11 and noticed this was undefined anyway. Never committed to the project before and welcome feedback (however basic this change is)

Removed _BYTE_ORDER test in uSynergy for Solaris 11

---

src/lib/platform/XWindowsScreen.cpp

These are the only valid ones:
[~]>for i in `seq 0 1 11`; do echo Testing $i; xte "mouseclick $i"; done
Testing 0
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  132 (XTEST)
Minor opcode of failed request:  2 (X_XTestFakeInput)
Value in failed request:  0x0
Serial number of failed request:  12
Current serial number in output stream:  15
Testing 1
Testing 2
Testing 3
Testing 4
Testing 5
Testing 6
Testing 7
Testing 8
Testing 9
Testing 10
Testing 11
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  132 (XTEST)
Minor opcode of failed request:  2 (X_XTestFakeInput)
Value in failed request:  0xb
Serial number of failed request:  12
And there are mice out there …

Only allow mouse buttons 1 to 10 on Linux

---

src/gui/res/lang/Languages.xml

correct Language.xml indent and replace "한국의" with "한국어" in the meaning of "Korean Language", not "of Korea"

Improve Korean language description

---

src/lib/platform/XWindowsScreen.cpp

...RawMotion events, since having both causes weird behaviour for double tap screen change.
Fixes  #3197 (which was closed as obsolete).

Linux: Disable regular motion events when using XInput 2

---

src/lib/platform/OSXScreen.mm

OSXScreen was not adding mouse movement deltas to mouse events while
dragging. Some 3D applications rely on these deltas to implement
dragging. Adding the mouse deltas to the mouse event fixes dragging in
these applications. Ex: Unity3d

#3992 macOS: Dragging broken in Unity

---

src/lib/platform/MSWindowsKeyState.cpp

virtaual key table is mapped for all IMEs not just active IME.
And this cause wrong modifier key pressed issue.
For example, if I use Korean and Japanese IMEs,
pressing hangul key makes alt key pressed.
So when I press just 'a', client interpretes that 'alt-a'.

Fix muti imes issue in Windows OS,

---

src/lib/server/Config.cpp

My monitor setup consists six monitors, all the same size. The three top monitors are connected to a Raspberry Pi each. The bottom monitors are connected to my workstation. For the Synergy setup to work properly I'd needed to enter values like 33.33333333 and 66.66666667. When entering them rounded as 33 and 67, the cursor makes annoying jumps at the monitor corners. To fix this I added support for using floating point values to specify the range instead of integers.

Added support for precise screen positioning

---

src/lib/platform/XWindowsScreen.cpp

XWindowsScreen::saveShape() using XRRSizes / XRRRotations to
calculate screen dimensions when XRandR and a rotated screen
was detected. This is wrong. The screen dimensions in the
display properties already reflect rotation.
Moreover, on servers supporting XRandR >= 1.2, the XRRSizes()
and XRRRotations calls from XRandR 1.1 will return the
properties of the "primary output" in XRandR 1.2 terms rather than
the properties of the entire screen.

XRandR: fix screen size calculation

---

src/test/unittests/synergy/ClipboardChunkTests.cpp

This only fixes the test. I have not verified the code behind the test is functioning as
designed. It was relayed I should submit a pull request for review.
This is related to: https://github.com/symless/synergy/issues/5838

Fix ClipboardChunkTests unit test on big endian archs.

---

CMakeLists.txt
ChangeLog
src/test/unittests/synergy/ClipboardChunkTests.cpp

Fix for Issue #5648, using proposed code from @PutzWorks. Also includes compilation fixes to allow compiling on Sierra (unfortunately, I was only able to implement the fix with QT4). Tested on my two Macs, both of which were exhibiting the mouse problem, and are now no longer exhibiting the problem with this new build.

Fix for Issue #5648 - Mouse Drifting/Jittering/Lagging

---

src/lib/server/Server.cpp

We have found and fixed a bug using PVS-Studio tool. [PVS-Studio](https://www.viva64.com/en/pvs-studio/) is a static code analyzer for C, C++ and C#.
We suggests having a look at the emails, sent from @pvs-studio.com.
Analyzer warning: [V625](https://www.viva64.com/en/w/V625/) Consider inspecting the 'for' operator. Initial and final values of the iterator are the same. Server.cpp 253

Server omits client connections in ｄestructors

---

CMakeLists.txt
dist/rpm/synergy.spec.in
res/synergy.desktop
res/synergy2.desktop

The current icon path on Linux is preventing themes from providing their own icons for synergy.
.desktop files should generally avoid providing absolute icon paths when possible and instead simply adhere to [these conventions](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#directory_layout).
Let me know if you need any more information, if you'd like me to change target branch, etc.
Thanks

Fix icon path on Linux

---

src/lib/platform/XWindowsUtil.cpp

These codes were not supported at all, presumably due to being introduced
only in Unicode 3.0.

Add support for latin 's' and 't' with comma below

---

doc/synergy.conf.example

instead of saying apparently absolute statements
like "Foo is to the right of Bar",
use relative phrasing "for Bar, Foo is to the right".
This makes it clearer that the configuration file
does not describe a globally consistent spatial arrangement
but rather a set of areas that can be linked in arbitrary ways.

synergy.conf.example: clarify comments

---

src/lib/platform/XWindowsScreen.cpp

XWindowsScreen::m_isOnScreen currently initializes to true for all
screens, meaning that every screen assumes it currently has control of
the shared mouse pointer when it starts up. For the primary (server)
screen, this is appropriate; when synergy starts, the local mouse should
still move the cursor on the local screen.
However, for secondary screens, this is incorrect; when the client
connects, it does _not_ have control of the shared mouse pointer, as the
server's mouse still moves the server's cursor.
This doesn't make much difference in most cases, as the secondary screen
behaves almost identically whether m_isOnScreen is true or false;
however, the local input detection code will only fire if the variable
is false, meaning that once the client connects, it first has to gain
the …

Initialize XWindowsScreen to offscreen for secondary displays

---

src/gui/CMakeLists.txt

Since qt5_use_modules is deprecated in newer cmake versions
use target_link_libraries with Qt5:: targets instead.
see: http://doc.qt.io/qt-5/cmake-manual.html

Use target_link_libraries instead of qt5_use_modules

---

src/gui/src/ActionDialog.cpp
src/gui/src/ScreenSetupView.cpp

Some Qt gui headers are no longer included when including QtGui
adding these two missing headers makes Synergy build here on windows.

Add missing header includes to build against Qt 5.11.0

---

src/gui/src/ActionDialog.cpp
src/gui/src/ScreenSetupView.cpp

This fixes #6366 and #6375
Named the include correctly according to [review comments](https://github.com/symless/synergy-core/pull/6486#discussion_r279495680) (@darkdragon-001)

Fixes Qt Headers for 5.11+ with the correct naming scheme

---

dist/wix/Include.wxi.in
dist/wix/Product.wxs
src/cmd/synergyc/CMakeLists.txt
src/cmd/synergyc/synergyc.exe.manifest
src/cmd/synergys/CMakeLists.txt
src/cmd/synergys/synergys.exe.manifest
src/gui/src/AppConfig.cpp
src/gui/src/AppConfig.h
src/gui/src/MainWindow.cpp
src/gui/src/MainWindow.h
src/gui/src/MainWindowBase.ui
src/gui/src/SettingsDialog.cpp
src/gui/src/SettingsDialogBase.ui
src/lib/net/SecureListenSocket.cpp
src/lib/net/SecureListenSocket.h
src/lib/net/SecureSocket.cpp
src/lib/net/TCPSocket.cpp
src/lib/platform/XWindowsUtil.cpp
src/lib/server/ClientListener.cpp
src/lib/server/ClientListener.h

Thought I would spend some time pulling in a number of fixes and improvments from forks that arn't in synergy.
I started the PR so you can track the changes im making  over time and will ask for review when im finished.
Changes thus far
- ce8c65f - Fixed access violation in SSL sockets 
- 5af4b13 - Double clicking tray shows GUI, Tray also has tooltip 
- ccb0237 - Fixed Autohide 
- 9240cc1 - Implimented Minimize to tray 
-  b3298ad - Fixed race condition 
- eb02587 - Added CLOG_DEBUG for opening/closing TCPSocket objects and fixed assert() crash
- 84fcbea - Added dpiAwareness PerMonitor, and set min height to auto for diffrent scaling
- edfc7e9 - Added description to XWindows error handler message 
- 3023f9b - removed redistributable magic from installer

Pull in fixes from forks

---

src/gui/src/SslCertificate.cpp

Upped the default key size of synergy TLS connections across all platforms
This won't replace an existing certificate.
The old certificate must be deleted manually.

Increased SSL keysize and SHA algorithm #6561

---

CMakeLists.txt
src/lib/net/SecureSocket.cpp

The patch to get SSL working on Linux seems to break it for Mac, this fixes those errors, also updated the displayed protocol version as some versions of open SSL return "SSLv3/TLSv1" for any protocol above SSLv3. 
The protocol is obtained from the cipher description function rather than the version function.

Open SSL fixes for macOS

---

src/gui/src/SslCertificate.cpp

This reverts commit 1bc2cf57
Fixes #6608

Reverting changes the the openSSL binary location

---

src/lib/synergy/KeyMap.cpp

Original PR #6448 
Fixes #4 
Fixes quote key on US international keyboards
New PR created as old PR would pull in v2 changes

Fixed quote key on US International keyboard

---

src/lib/platform/MSWindowsDesks.cpp
src/lib/platform/MSWindowsDesks.h
src/lib/platform/MSWindowsKeyState.cpp

Original PR #5885 
> Related to: #4288 #4290
>
>Printscreen sends Alt+Printscreen to Windows clients (#4288). Previous patch (#4290) only removes the alt+printscreen scancode from being mapped to VK_SNAPSHOT AFAIK. This patch adds send_keyboard_input and send_mouse_input to replace keybd_event and mouse_event but are functionally the same other than the ability for send_keyboard_input to send virtual-keys and scancodes so Windows can produce certain key-combos (like alt+printscreen). There's still a bit of special handling for Alt+Printscreen so the correct key up/down scancodes are sent but everything appears to work.
>
>Feel free to test and make suggestions.
I lost the original commit author details during the cherry-pick, But the source of this change belongs to @yupi2
I also Removed …

Send Print Screen key to Windows clients

---

src/lib/net/SecureSocket.cpp

This patch is for the 1.X versions. 2.X does not have this problem.
Weirdly enough, LibreSSL has a high enough version, yet does not feature SSL_get_client_ciphers.

Fixed missing SSL_get_client_ciphers with LibreSSL

---

src/gui/src/MainWindow.cpp
src/gui/src/MainWindow.h
src/gui/src/MainWindowBase.ui

Fixes #6472 
This adds a help entry linking to [symless website help page]("http://symless.com/help?source=gui").
* creates new "Help" sub-menu in OS X
* nests under existing "Help" sub-menu for all other platforms.

Added context menu link to the help site

---

src/gui/src/AppConfig.cpp
src/gui/src/AppConfig.h
src/gui/src/MainWindow.cpp
src/gui/src/MainWindow.h

Fixes #6587 
When the auto configure option is changed a signal is sent to the main window to update and start the service

Added signal when auto config is changed to update UI

---

src/gui/CMakeLists.txt

I found make install copies synergy into the bundle/Synergy.app but fails to install the Qt frameworks. Adding this call to macdeployqt when running make install fixes it for macos. A similar solution may be wanted for windows also.

Use macdeployqt to install Qt frameworks inside bundle

---

ChangeLog
src/lib/platform/XWindowsScreen.cpp
src/lib/platform/XWindowsScreen.h

> I have a laptop I put on a dock when I get to work. That dock has a display attached giving me 2 displays to work from. when my laptop becomes a client for the desktop PC, the Desktop PC acting as server is only aware of the original display size, not the new, larger area, constraining the pointer on the client PC (my laptop) to a corner in the upper left corner of the larger, external display on the left.
> 
> This patch checks if xinerama is enabled.
> Then checks if there is >1 screen, and gets the sizes.
> Then adds a listener for 'xconfigure.window == m_root' event.
> The listener sets the 'display size' to the new size, if there is one.
> 
> The patch allows me to put my laptop on the dock and synergy correctly updates the screen size. The bug is 6 years old and I've been applying …

Fix for client resolution change on Linux

---

CMakeLists.txt
ChangeLog
src/CMakeLists.txt
src/lib/synergy/KeyMap.h
src/test/unittests/synergy/KeyMapTests.cpp

Original PR #5943
Resolves #6725 
Disable building of test with a CMake option which also moves test code from non test files

Disable test with cmake option

---

ChangeLog
cmake/Version.cmake
src/gui/src/ConfigWriter.cpp

Adding the system scoped settings changed the location of the user scoped setting which broke backward compatibility with older settings, This PR intends to solve that issue
Resolves #6730

Changed user scope setting location back

---

CI/Linux/linux-build.yml
CI/MacOS/mac-build.yml
CI/Windows/windows-build.yml
ChangeLog

Resolves #6734 
This PR correctly name the installer file for both Windows and Linux, This also combines all the checksums into a single txt file for each installer

Fixed naming of installers for linux and windows

---

CMakeLists.txt
ChangeLog

Resolves #6739
Making submodule init/update transparent to the end user.
This change prevents CMake builds from failing if submodules have not been
installed, e.g., Google Test.
This relates to #6710.

Update git submodules during build

---

ChangeLog
src/gui/src/MainWindow.cpp

Fixed  account name with spaces causing TLS path errors

---

ChangeLog
src/lib/platform/MSWindowsWatchdog.cpp
src/lib/platform/MSWindowsWatchdog.h

Fixes #6567 
Captured all child process info as they are created, and closed handles when process are killed, Also added a close everything function to clear all all child process information when the deamon resets
Other info
Installed shotgun in deamon for zombie control

SYNERGY-92 Fixed deamon leaving zombie process hanging about feeding on memory

---

CI/Linux/linux-build.yml
ChangeLog
azure-pipelines.yml

Resolves #6771 
For some reason Ubuntu 16 didn't like running in parallel and as azure doesn't give
many cores. Disabling multi core building doesn't affect the time that much

SYNERGY-292 Added Ubuntu 16 back the the build pipline

---

src/lib/platform/XWindowsClipboard.cpp

Resolves #6660 
Resolves #6582 
Added atom "text/plain;charset=utf-8" to the m_converters list to prevent falling back to "STRING", causing non ASCII characters to be replaced by question marks. Note that the capital UTF-8 atom is also a valid one.

Add missing XAtom for utf-8 handling with Xorg.

---

ChangeLog
src/lib/shared/SerialKey.cpp
src/lib/shared/SerialKey.h
src/test/unittests/shared/SerialKeyTests.cpp
src/test/unittests/synergy/ProtocolUtilTests.cpp

Unfortunately we are not able to use std::chrono due to compilation errors on: centos7.6, ubuntu1604, debian9

SYNERGY-362 Eliminate using std::chrono 

---

ChangeLog
src/test/unittests/synergy/ServerArgsParsingTests.cpp

It seems that compilers such as the one shipped with CentOS 7.6 can implement ```auto``` rather strangely; avoiding the issue by not using auto on this new test.

fix for older compilers

---

.github/workflows/job-sonarcloud.yml

Fixes issue with PR #6872 where SonarCloud check is not able to use the Secret Token.  Also, fixes minor typo.
Changing the `pull_request` job to `pull_request_target`.
> [`pull_request_target`](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request_target)
>
> This event is similar to `pull_request`, except that it runs in the context of the base repository of the pull request, rather than in the merge commit. This means that you can more safely make your secrets available to the workflows triggered by the pull request, because only workflows defined in the commit on the base repository are run.

PR SonarCloud

---

src/gui/src/TrayIcon.h

Removing C++14 constructs for compatibility on CentOS7.6.
Jira issue Synergy-734.

PR changes 6889 and resolution for CentOS 7.6

---

scripts/buildCoreLinux.sh
scripts/buildCoreMacos.sh

The directory separator is "backward"

Fix path on mac and linux

---

CI/Windows/windows-build.yml
ChangeLog

In the Azure pipelines CI for windows. We relied on the openssl.exe dep in the ext directory. I moved it and now I'm fixing the CI script.

Change OpenSSL paths

---

CI/MacOS/mac-build.yml
ChangeLog
azure-pipelines.yml

Fixes macOS CI build and removes the Centos7.6 build until we are ready to deal with it.

Mac build failures

---

CMakeLists.txt
ChangeLog

Adds an extra layer of validation on whether to build the enterprise version of the application. This makes creating workflows easier compared to having custom conditional logic in multiple places of the workflow in order to set or not set the environment variable.

SYNERGY-833 Add extra enterprise validation

---

ChangeLog
src/gui/src/IpcClient.cpp
src/gui/src/MainWindow.cpp
src/gui/src/main.cpp
src/lib/base/Log.cpp
src/lib/base/String.cpp
src/lib/base/XBase.cpp
src/lib/net/SecureSocket.cpp
src/lib/server/InputFilter.cpp
src/lib/server/Server.cpp
src/lib/synergy/IKeyState.cpp

* Test commit to check sonar reaction

SYNERGY-511 SonarCloud security hotspots in Synergy-core

---

CMakeLists.txt
ChangeLog
cmake/Version.cmake
src/gui/CMakeLists.txt

This PR removes cmake option SYNERGY_AUTOCONFIG to disable ability to build synergy with unsupported autoconfig functionality. 
In the same time we still have SYNERGY_AUTOCONFIG checks in the code.
Code cleanup will be prepared under separate task

SYNERGY-1015 remove cmake option for autoconfig

---

ChangeLog
src/lib/platform/OSXScreen.h
src/lib/platform/OSXScreen.mm

There was an additional division to fix exponential scale on macOS. 
Looks like it was actual for old version because there is no exponential scale on actual macOS.

SYNERGY-1047 Scroll doesn't work in case of macOS is server

---

ChangeLog
src/test/unittests/CMakeLists.txt

*Fix sources and headers rules in unittests project

Hot-Fix-unittest-CMakeFileList

---

ChangeLog
src/gui/src/MainWindow.cpp
src/gui/src/MainWindow.h

This PR is to close synergy using the X button and using quit on the panel on all Linux systems.
This solution was agreed with Andrea.

SYNERGY-1229 Synergy is running after quit on Linux

---

CI/job-doxygen.yml
ChangeLog
src/lib/client/Client.cpp
src/lib/server/ClientProxyUnknown.cpp
src/lib/server/Server.cpp
src/lib/server/Server.h
src/lib/synergy/protocol_types.cpp
src/lib/synergy/protocol_types.h

Under this PR the following changes were implemented:
1. Removed language notification on the server side.
2. Enable notification on the client side even if sync is off.
3. Notification message was changed according to the task SYNERGY-1287
4. Changed Doxygen job to use ubuntu-latest instead of ubuntu-16 because ubuntu-16 is no available anymore on Azure Pipelines.

SYNERGY-1287 display language notifications only on client side

---

.github/workflows/aws-upload-windows.yml
ChangeLog
scripts/buildCoreWindows.ps1

Fix unstable build for synergy-core binaries on windows. Seems that specifying `x64` makes it work.

SYNERGY3-150 Fix unstable build for windows core

---

src/lib/platform/XWindowsClipboard.cpp
src/lib/platform/XWindowsClipboardUTF8Converter.cpp
src/lib/platform/XWindowsClipboardUTF8Converter.h

GTK normalizes line endings in the clipboard to CRLF for the text/plain;charset=utf-8 clipboard format.
This results in double lines when pasting text copied from Linux to Windows because the Windows client converts line endings and expects only LF.

Fix double lines when pasting text from Linux to Windows

---

ChangeLog
src/lib/net/SecureSocket.cpp
src/lib/net/SecureSocket.h
src/lib/platform/OSXAutoTypes.h
src/lib/platform/OSXKeyState.cpp
src/lib/platform/OSXKeyState.h
src/lib/synergy/unix/AppUtilUnix.cpp

This PR fixed the following memory leaks:
1. In function getKeyboardLayoutList call for CFDictionaryCreat and TISCreateInputSourceList
2. A new function freeSSL to call free SSL memory from destructor and function close

SYNERGY1-1497 Fix memory leaks

---

ChangeLog
src/lib/arch/unix/ArchNetworkBSD.cpp
src/lib/arch/win32/ArchNetworkWinsock.cpp
src/lib/net/NetworkAddress.cpp
src/lib/net/SecureSocket.cpp
src/lib/platform/OSXScreenSaver.cpp

The following memory leaks were fixed:
1. In `isScreenSaverEngine` free memory allocated by `CopyProcessName`
2. In `nameToAddr` free memory allocated by `getaddrinfo`
3. In ​​`SecureSocket::verifyCertFingerprint` free memory allocated by `SSL_get_peer_certificate`
Sonar shows some code duplication which we had previously.
It requires some refactoring which will increase testing scope hence it should be done under a separate task.

SYNERGY1-1497 memory leaks in synergyc on mac os

---

.github/workflows/job-build-raspberry-pi.yaml
ChangeLog

When builds happen for the Raspberry PI, GitHub is only building two of the 6 runs it should be doing. By adding the name as a matrix option, it allows us to see all runs of the workflow.

Show all Raspberry PI builds

---

src/gui/src/AboutDialog.cpp
src/gui/src/AboutDialogBase.ui

This PR fixed the following issues:
1. Horizontal scrolling for elite backers 
2. Update about text
3. Fix issue with version number on macOS

Use vertical scroll on the about screen

---

src/gui/src/SettingsDialog.cpp
src/gui/src/SettingsDialog.h

SYNERGY1-1616
This PR updates fixes problem with client/host mode checkbox when user switches between settings scope

Update visibility for client/host mode checkbox during settings loading.

---

src/gui/src/AppConfig.cpp
src/gui/src/AppConfig.h

During switching between settings scopes (user and system), this sets the default value for the hidden option `InitiateConnectionFromServer`.
SYNERGY1-1616

Use default value for 'Initiate connection from server'

---

src/lib/base/Log.cpp
src/lib/base/String.cpp
src/lib/synergy/IKeyState.cpp

Without the change the build on upcoming `gcc-13` ails as:
src/lib/base/Log.cpp: In member function 'void Log::print(const char*, int, const char*, ...)':
src/lib/base/Log.cpp:128:23:
error: 'SIZE_MAX' was not declared in this scope
128 |     if ((strnlen(fmt, SIZE_MAX) > 2) && (fmt[0] == '%' && fmt[1] == 'z')) {
|                       ^~~~~~~~
src/lib/base/Log.cpp:30:1:
note: 'SIZE_MAX' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
29 | #include <ctime>
+++ |+#include <cstdint>
30 |
gcc-13 cleaned it's header dependencies and that exposes these failures.

synergy-core: add missing <cstdint> includes for SIZE_MAX

---

ChangeLog
res/openssl/synergy.conf

[SYNERGY1-1634](https://symless.atlassian.net/browse/SYNERGY1-1634)
Upgrade the default hashing algorithm for message digests from md5 to sha256.

Upgrade the default hashing algorithm

---

CMakeLists.txt
ChangeLog
src/cmd/CMakeLists.txt

When building Synergy, we should only need to build a single `synergy-core` binary or separate `synergys` and `synergyc` binaries.

Build unified core or separate server and client

---

src/lib/synergy/ServerApp.cpp

S3-834
This PR changes warning for XSocketAddressInUse to fatal error

Change warning to fatal error

---

ChangeLog
src/lib/mt/Thread.cpp

[S3-1369](https://symless.atlassian.net/browse/S3-1369)
We seem to be reporting system errors as <unknown>.
This splits out exception throws and non-exception throws.
[S3-1369]: https://symless.atlassian.net/browse/S3-1369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Catch standard exceptions on unexpected exit

---

ChangeLog
src/lib/platform/MSWindowsWatchdog.cpp

In an attempt to fix a C++20 compile issue, `si.lpDesktop` (`src\lib\platform\MSWindowsWatchdog.cpp`) was assigned to a string buffer, but since this was on the stack, it'll have been deleted before Win32 could access it.
Compile error:
`error C2440: '=': cannot convert from 'const char [16]' to 'LPSTR'`
Related warning:
`ISO C++11 does not allow conversion from string literal to 'LPSTR' (aka 'char *')`
Error from Windows Daemon:
```
[2024-01-12T19:48:11] FATAL: failed to launch, error: process immediately stopped
C:\Projects\symless\synergy-3.1\ext\synergy-core\src\lib\platform\MSWindowsWatchdog.cpp,290
```
Since `lpDesktop` wants a mutable char buffer, I'll use a heap char buffer (rather than casting to `LPSTR` as was done previously).
S3-2008

 Restore lpDesktop assignment in Windows daemon

---

CMakePresets.json
ChangeLog

Ninja brings significant benefits to building on Windows, but we don't need it for macOS and Linux right now (so we can stick with make).
S3-1978

Only use Ninja to build on Windows

---

.github/workflows/job-test-windows.yml
.vscode/tasks.json
ChangeLog
scripts/windows_daemon.py
src/lib/platform/MSWindowsSession.cpp
src/lib/platform/MSWindowsWatchdog.cpp

In the Windows daemon. after calling `Process32Next`, the `GetLastError` function can intermittently return `ERROR_FILE_EXISTS` (`Cannot create a file when that file already exists`) which doesn't make sense in the context of `Process32Next`; this function should not normally return that error code. This suggests that some other earlier Win32 function call is failing and setting the error state.
For now, we'll call `SetLastError(0)` to reset the error state before calling `Process32Next`.
This PR also adds a new script, `scripts\windows_daemon.py` which makes it easier to install the Windows daemon from the `build/bin` dir (to save us from fiddling around with commands).
To test: Difficult to reproduce as it's intermittent (perhaps a memory error). If you build the daemon, install it …

Reset error state before calling Process32Next

---

CMakePresets.json
ChangeLog

This splits the existing CMake presets `windows`, `macos`, and `linux` into:
- `windows-debug`
- `windows-release`
- `macos-debug`
- `macos-release`
- `linux-debug`
- `linux-release`
S3-2041

Split CMake presets into debug and release

---

.vscode/launch.json
.vscode/tasks.json
CMakePresets.json
ChangeLog

Debugging the Windows Daemon is possible with `cppvsdbg` modes, `attach` and `launch` (when run with `-f` or `/f`). This PR surfaces this knowledge to make it easier for others to debug the Windows Daemon.

Update VS Code config for Windows daemon debugging

---

.vscode/launch.json
ChangeLog
src/lib/base/Log.cpp

This PR changes the debug source paths from: `/path/to/foobar.cpp,123` to `/path/to/foobar.cpp:123`
When compiled in debug mode, source paths are printed for each log line, making it easy to locate the log line in the soruce. However, due to the comma char (`,`) between the path and the line number, IDEs like VS Code won't take you to the line in the source file when you click the path; for the path and line number to be clickable it has to be a colon (`:`) before the line number. Having a clickable path was never considered because back in the early 2000s when this code was introduced; clickable artifacts in terminal output  wasn't yet a common feature.
This PR also changes the `windows daemon launch` VS Code launch target, adding a similar target to rebuild before launching. There are …

Clickable debug source paths and new launch target

---

.vscode/extensions.json
ChangeLog

This PR adds recommended extensions for C++ and LLDB which are used to run the targets in `.vscode/launch.json`.

Add C++ and LLDB to VS Code recommendations

---

.github/workflows/create-release.yml

I believe this solves the problem where:
> GitHub prevents workflows from running on events that were caused by other workflows to prevent unlimited recursion (See the docs: [Triggering a workflow from a workflow](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow))

Use org token instead of regular token to create releases

---

ChangeLog
cmake/Packaging.cmake

https://symless.atlassian.net/browse/S1-1713
To test:
1. Use Debian-like 
2. Configure and build
3. `./scripts/package.py`

Add `qt6-qpa-plugins` Qt dependency for Debian

---

ChangeLog
scripts/lib/mac.py
src/gui/CMakeLists.txt

https://symless.atlassian.net/browse/S1-1714
To test:
1. Same as https://github.com/symless/synergy-core/pull/7379
2. ... but actually test the binary: `./build/bundle/Synergy.app/Contents/MacOS/synergy`

Re-run `macdeployqt6` to copy missing Qt 6 dependencies

---

ChangeLog
cmake/Build.cmake
src/lib/arch/win32/XArchWindows.h
src/lib/base/Path.cpp
src/lib/common/Version.cpp
src/lib/common/Version.h
src/lib/gui/OSXHelpers.mm
src/lib/net/InverseSockets/SecureClientSocket.h
src/lib/net/SecureSocket.h
src/lib/platform/OSXDragSimulator.m
src/lib/platform/OSXDragView.m
src/lib/platform/OSXKeyState.cpp
src/lib/platform/OSXMediaKeySupport.m
src/lib/platform/OSXPasteboardPeeker.m
src/lib/platform/OSXScreen.mm
src/lib/synergy/App.cpp
src/lib/synergy/DaemonApp.cpp
src/lib/synergy/KeyState.h
src/lib/synergy/unix/AppUtilUnix.h
src/lib/synergy/win32/AppUtilWindows.cpp
src/lib/synergy/win32/AppUtilWindows.h
src/test/unittests/synergy/ServerAppTests.cpp

https://symless.atlassian.net/browse/S1-1778
Adds:
```
if(WIN32)
message(STATUS "Enabling warnings as errors (MSVC)")
add_compile_options(/WX)
elseif(UNIX)
message(STATUS "Enabling warnings as errors (GNU/Clang)")
add_compile_options(-Werror)
endif()
```

Fixed warnings and enable errors as warnings

---

ChangeLog
src/gui/src/MainWindow.cpp
src/gui/src/MainWindow.h
src/gui/src/MainWindowBase.ui
src/gui/src/main.cpp
src/lib/gui/byte_utils.h
src/lib/gui/config/AppConfig.cpp
src/lib/gui/config/AppConfig.h
src/lib/gui/config/ConfigScopes.h
src/lib/gui/config/IAppConfig.h
src/lib/gui/config/IConfigScopes.h
src/lib/gui/core/CoreProcess.cpp
src/lib/gui/core/CoreProcess.h
src/lib/gui/dialogs/SettingsDialog.cpp
src/lib/gui/dialogs/SettingsDialog.h
src/lib/gui/ipc/QDataStreamProxy.h
src/lib/gui/ipc/QIpcClient.cpp
src/lib/gui/ipc/QIpcClient.h
src/lib/gui/messages.cpp
src/lib/gui/messages.h
src/lib/gui/proxy/QSettingsProxy.cpp
src/lib/gui/proxy/QSettingsProxy.h
src/lib/synergy/Screen.cpp
src/test/shared/gui/mocks/AppConfigMock.h
src/test/unittests/gui/config/AppConfigTests.cpp

https://symless.atlassian.net/browse/S1-1744
https://symless.atlassian.net/browse/S1-1792
https://symless.atlassian.net/browse/S1-1793
Also:
- Swap assert in screen dtor for warning log lines
- Flush IPC write buffer (to fix clear settings IPC bug)
- Fixed: app has run before setting was never set
- Show message box on first server run

Show message box explaining why settings are read-only

---

ChangeLog
src/lib/platform/wayland.h
src/lib/synergy/App.h
src/lib/synergy/ArgParser.cpp
src/lib/synergy/ArgsBase.h
src/lib/synergy/ClientApp.cpp
src/lib/synergy/ServerApp.cpp

https://symless.atlassian.net/browse/S1-1822

Use EI screen when `XDG_SESSION_TYPE` is "wayland"

---

.github/workflows/create-release.yml
.github/workflows/create-tag.yml

https://symless.atlassian.net/browse/S1-1801
> When people in the community want to see [releases](https://github.com/symless/synergy-core/releases) in a GitHub project, they do not expect to see each merge into main/master as a release; it’s confusing when you observe a series of “pre-release” snapshots that are not real releases. It also makes finding actual releases difficult and frustrating.
> Only create tags for each revision. We should create releases from an actual release branch. For instance, if we merge a PR into main/master, it should make a tag (not a release) and when we push to a branch beginning in release then it should create a release. 
> Important: We should also delete all releases that are pre-releases (under the assumption they are not actual releases); this should …

Only create tags (not releases) when merging PRs into master

---

ChangeLog
cmake/Libraries.cmake
config.yaml
meson.build
scripts/install_deps.py
scripts/lib/meson.py
subprojects/libei.wrap
subprojects/libportal.wrap

> Installing the built libportal causes issues such as Nautilus not working (maybe a libportal bug report is needed).
> Instead of installing, use the local build if SYSTEM_LIBPORTAL is false. Also, use master instead of tag (for all git subprojects), since it’s only used for development. An arg for install_deps.py such as --no-system libportal,libei would be useful.
1. Use GNOME46 (sorry, haven't tested with KDE yet but I plan to)
1. Install the deps for `libportal`:
- Debian-like: `./scripts/install_deps.py --subproject libportal`
- Other distro: Sorry, no script but you can probably work out the deps from [`config.yaml`](https://github.com/symless/synergy/blob/df6fdb3eda5f35624d33e9109206d46a4cfd1e30/config.yaml#L175)
1. Build local `libportal`:
- Run: `./scripts/install_deps.py …

Option to link against local `libportal` and other subprojects

---

.vscode/launch.json
src/lib/platform/EiEventQueueBuffer.cpp
src/lib/platform/XWindowsEventQueueBuffer.cpp

> just noticed that doing a pipe2(pipefd, O_NONBLOCK) might be smarter here
@whot Looks good, tested on Wayland and X, client and server with libei main and libportal main :+1: 
---
https://symless.atlassian.net/browse/S1-1812

Port EI fixes to use `pipe2` instead of `pipe` and `fcntl`

---

ChangeLog
scripts/install_deps.py
scripts/lib/windows.py

>The command daemon.py --reinstall freezes waiting for process to stop due to the new file lock feature.
> Turn this feature off by default and allow it to be enabled with an arg.
https://symless.atlassian.net/browse/S1-1836

Only wait for elevated process to end when arg is set

---

.github/workflows/ci.yml
ChangeLog

> Our FreeBSD runner serves an important purpose for our project, but it is the slowest runner. Part of that is the setup time, but it also seems slow to build relative to the other runners.
> An option to use all available CPUs on the host system would be helpful: https://github.com/vmactions/freebsd-vm/issues/85#issuecomment-2336596167 
https://symless.atlassian.net/browse/S1-1840
---
Special thanks to @Neilpang for improving [`vmactions/freebsd-vm`](https://github.com/vmactions/freebsd-vm) to use the maximum CPUs on the host system (https://github.com/vmactions/freebsd-vm/issues/85).

Use 16-CPU CI runner for FreeBSD

---

.github/workflows/ci.yml
ChangeLog

> It appears that the vcpkg dep openssl is being rebuilt on Windows even though the vcpkg_installed dir is cached. This might be because it also needs the git-tree to be cached to avoid rebuilding.
> Either cache the local appdir or go back to using a local (project) install of vcpkg.
https://symless.atlassian.net/browse/S1-1842

Cache vcpkg local app dir to restore built OpenSSL

---

src/lib/platform/EiEventQueueBuffer.cpp
src/lib/platform/EiScreen.cpp

> The debug messages are very noisy in the EI screen implementation.
> Move more frequently occurring debug messages to DEBUG1 where appropriate.
https://symless.atlassian.net/browse/S1-1835

Move some EI server log messages to higher log levels

---

.github/workflows/ci.yml
ChangeLog
cmake/Libraries.cmake
meson.build
meson_options.txt
scripts/install_deps.py
scripts/lib/meson.py
subprojects/.gitignore
subprojects/libportal.wrap
subprojects/packagefiles/libportal/static-lib.diff
subprojects/packagefiles/wintoast-patch/meson.build
subprojects/packagefiles/wintoast/meson.build
subprojects/wintoast.wrap

> Beta testers won’t be able to try Wayland server support until libportal 0.8.x lands in the package repos. Some rolling distros like Arch are cutting-edge and already have 0.8.x, so they are not a problem, but Ubuntu and Debian can take some time.
> If we bundle libportal by statically linking it, we can allow beta testers to start testing Wayland server support early.
https://symless.atlassian.net/browse/S1-1830

Option to static link `libportal` ahead of 0.8.x distribution

---

ChangeLog
cspell.json
scripts/lib/env.py
scripts/package.py

> The Debian package does not contain the version codename (e.g. “trixie”) so the Debian version is ambiguous.
> Add the version codename to the package to differentiate it from the Debian 12 package.
https://symless.atlassian.net/browse/S1-1845
> When rebuilding the S1 CI, the S3 filename style was copied without realizing that it is different to the S1 style, so now the S1 style in 1.15+ no longer matches 1.14 and below.
> The filename style should match between versions, so we should restore the old filename.
https://symless.atlassian.net/browse/S1-1849

Make package filenames consistent with previous versions

---

.github/workflows/ci.yml
ChangeLog

> Debian 13 trixie now has libportal 0.8, so no need to static link.
> https://symless.atlassian.net/browse/S1-1848

Remove static link of libportal from Debian Trixie CI

---

ChangeLog
scripts/lib/mac.py

> The community edition CI workflow fails because there is no APPLE_CODESIGN_ID env var set.
> Do not sign the bundle if the APPLE_CODESIGN_ID env var is not set.
https://symless.atlassian.net/browse/S1-1850

Make `APPLE_CODESIGN_ID` env var optional for CE CI

---

.github/actions/run-retry/action.yml
.github/workflows/sonarcloud-analysis.yml
ChangeLog

https://symless.atlassian.net/browse/S1-1844
Random failure on SonarCloud integtest step, e.g.:
https://github.com/symless/synergy/actions/runs/10789939224/job/29924012244 
```
[       OK ] ConfigTests.load_noArgs_returnsFalse (0 ms)
[----------] 8 tests from ConfigTests (1 ms total)
[----------] Global test environment tear-down
[==========] 18 tests from 5 test suites ran. (655 ms total)
[  PASSED  ] 18 tests.
(INFO) Reading coverage data...
(WARNING) Unrecognized GCOV output for /__w/synergy/synergy/src/lib/arch/unix/ArchMultithreadPosix.cpp
branch  2 taken -1
This is indicative of a gcov output parse error.
Please report this to the gcovr developers
at <https://github.com/gcovr/gcovr/issues>.
(WARNING) Exception during parsing:
NegativeHits: Got negative hit value in gcov line 'branch …
```

Add `run-retry` action to workaround `integtest` `gcovr` issue

---

ChangeLog
src/lib/deskflow/protocol_types.cpp

Fixes: #7523 
revert protocol hello to `Synergy`
NOTE: For compatibility with Barrier / InputLeap we need to use `Barrier` 
TODO: Check for and Send the correct one based on what we are connecting to

fix: protocol compatibility with Synergy

---

.github/actions/dist-upload/action.yml
.github/workflows/ci.yml
.github/workflows/test-dist-upload.yml
ChangeLog

Problem: Google Drive upload breaks CI on `master` and is also a downstream requirement which we probably don't need it for Deskflow.
Solution: Remove Google Drive use in CI, and let downstream worry about that.

Remove Google Drive upload and always upload to GitHub

---

ChangeLog
src/lib/deskflow/IPlatformScreen.h
src/lib/deskflow/PlatformScreen.h
src/lib/deskflow/Screen.cpp
src/lib/platform/EiScreen.cpp
src/lib/platform/EiScreen.h
src/lib/platform/MSWindowsScreen.cpp
src/lib/platform/MSWindowsScreen.h
src/lib/platform/OSXScreen.h
src/lib/platform/OSXScreen.mm
src/lib/platform/XWindowsScreen.cpp
src/lib/platform/XWindowsScreen.h

Blocked by: https://github.com/deskflow/deskflow/pull/7522
---
On exiting a screen, deskflow attempts to unset keys that are down while leaving the screen. In some cases, such as with Wayland (EiScreen), the keys are reset but after the device emulation has already ended by `Screen::leave()`. This leaves the keys in the pressed state since the reset will fail after emulation stops, and may leave the keys stuck pressed until the environment implementing libei is restarted (such as with Kwin).
This pull request splits `Screen::leave()` into `Screen::canLeave()` and `Screen::leave()`, allowing for the keys to be reset in between.
Basically:
Check for screen leave allowed -> Reset keys -> Actually leave
Resolves: #7518

fix: stuck keys on leave

---

ChangeLog
config.yaml

CI error: https://github.com/deskflow/deskflow/actions/runs/10953461679/job/30413790856
This PR resolves transient issues on CI:
```
sudo pacman -Sy --noconfirm base-devel cmake ninja gcc openssl glib2 gdk-pixbuf2 libxtst libnotify libxkbfile gtest pugixml libei libportal qt6-base qt6-tools gtk3
:: Synchronizing package databases...
core downloading...
extra downloading...
warning: base-devel-1-2 is up to date -- reinstalling
warning: cmake-3.30.3-2 is up to date -- reinstalling
resolving dependencies...
warning: ninja-1.12.1-1 is up to date -- reinstalling
warning: gcc-14.2.1+r134+gab884fffe3fc-1 is up to date -- reinstalling
warning: openssl-3.3.2-1 is up to date -- reinstalling
warning: gdk-pixbuf2-2.42.12-1 is up to date -- reinstalling
warning: libxtst-1.2.5-1 is up to date -- …
```

ci: always upgrade packages on arch

---

.github/workflows/lint-changelog.yml

Blocked by: #7533 
We don't always need to add to the `ChangeLog`, for instance when it's a minor edit to the docs.
This PR allows a PR author to add `{no-changelog-lint}` to their PR in order to skip the `ChangeLog` lint.

ci: option to skip changelog lint in PR

---

README.md

Blocked by: #7533, #7535
The link to `config.yaml` is not working in `README.md`.
{no-changelog-lint}

docs: fixed link to `config.yaml` in `README.md`

---

.github/actions/lint-error/action.yml
.github/workflows/lint-clang.yml
.github/workflows/lint-cmake.yml
ChangeLog

Fixes: #7527
:warning: Code style errors are intentional and are for testing (to trigger the lint errors). Before merging, apply the suggested fixes. The lint error comments should go away automatically once the lint errors are fixed.

ci: lint and add comment to PR on fail

---

.github/ISSUE_TEMPLATE/bug_report.yml

With issues such as #7541, it's important to know what environment the binary is being run in, since it behaves diffeently in dev env vs package. It would also be useful to know who built the package (us or an external package maintainer).
This PR adds an option to the bug report template so the reporter can specity how it was built.
{no-changelog-lint}

docs: add build type to bug report form

---

README.md

Blocked by: https://github.com/deskflow/deskflow/pull/7539
Damn, I forgot to test the links from PR #7532 and we checked in a broken link.
This PR fixes the link and adds the missing sponsor badge.
[Preview](https://github.com/deskflow/deskflow/blob/7f3012e407f5f4f0b3d2fbc5460f870bf1ffc235/README.md)
{no-changelog-lint}

docs: add extra badges and fix sponsor link

---

.github/workflows/ci.yml
.github/workflows/lint-changelog.yml
.github/workflows/lint-clang.yml
.github/workflows/lint-cmake.yml
.github/workflows/valgrind-analysis.yml

When the comment action is triggered by a PR originating from an external fork (i.e. a contributor) the error, `Resource not accessible by integration` shows because the worklow doesn't automatically have write permission to the PR.
Example: https://github.com/deskflow/deskflow/actions/runs/10964481892?pr=7511
We need to explicitly grant this permission with:
```
permissions:
pull-requests: write
```
{no-changelog-lint}

ci: give write permission for PR comments

---

cmake/Libraries.cmake

Oops, in PR #7544 I accidentally set the option name to `DEFAULT_SYSTEM_TOMLPLUSPLUS` when it should have been `SYSTEM_TOMLPLUSPLUS`. This causes a CMake warning:
```
[cmake] CMake Warning (dev) at cmake/Libraries.cmake:648 (option):
[cmake]   Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
[cmake]   --help-policy CMP0077" for policy details.  Use the cmake_policy command to
[cmake]   set the policy and suppress this warning.
[cmake] 
[cmake]   For compatibility with older versions of CMake, option is clearing the
[cmake]   normal variable 'DEFAULT_SYSTEM_TOMLPLUSPLUS'.
[cmake] Call Stack (most recent call first):
[cmake]   cmake/Libraries.cmake:16 (configure_tomlplusplus)
[cmake]   CMakeLists.txt:32 (configure_libs)
[cmake] This warning is for project developers. …
```

build: fixed option name for `SYSTEM_TOMLPLUSPLUS`

---

ChangeLog
scripts/lib/env.py
scripts/setup_venv.py

Related discussion: https://github.com/deskflow/deskflow/discussions/7550
When running any of the Python scripts in `scripts` dir, if you don't first run `install_deps.py` then you'll see an error:
```
$ ./scripts/lint_cmake.py 
Hint: Run the `install_deps.py` script first.
Traceback (most recent call last):
File "/home/nick/Projects/deskflow/./scripts/lint_cmake.py", line 20, in <module>
env.ensure_in_venv(__file__)
File "/home/nick/Projects/deskflow/scripts/lib/env.py", line 135, in ensure_in_venv
raise RuntimeError(f"Virtual environment not found at: {VENV_DIR}")
RuntimeError: Virtual environment not found at: .venv
```
This can create an obstacle to first time contributors or those who don't want to run `install_deps.py` (i.e. would rather install deps manually). 
This PR makes the …

build: script to create Python virtual env

---

CMakeLists.txt
ChangeLog
cmake/Build.cmake
src/gui/src/AboutDialog.cpp
src/lib/common/copyright.h

Fixes: #7545
We are using `__DATE__` macro which does not respect `SOURCE_DATE_EPOCH` making it difficult for downstream packagers to create reproducible builds.
Using `string(TIMESTAMP BUILD_DATE "%Y-%m-%d" UTC)` in CMake respects [`SOURCE_DATE_EPOCH`](https://reproducible-builds.org/docs/source-date-epoch/). ~~And for older versions of CMake (Debian Trixie for instance uses CMake 3.30.0) we have the less desirable way.~~
> only respects SOURCE_DATE_EPOCH since version 3.8.0 ([April 2017](https://cmake.org/pipermail/cmake-developers/2017-April/029946.html)). Note that the final argument UTC is required or the timestamp may vary between timezones.
Edit: The min version for CMake is set to 3.8 for this reason.

build: set `BUILD_DATE` instead of using `__DATE__`

---

.github/actions/lint-error/action.yml
.github/workflows/lint-clang.yml
.github/workflows/lint-cmake.yml
.github/workflows/lint-comment.yml

Related to: #7558
:warning: This PR probably doesn't work (unless I got lucky), but we have to merge this before we can test it; to quote the [`workflow_run` docs](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_run):
> Note: This event will only trigger a workflow run if the workflow file is on the default branch.
This is likely to be a security feature.

ci: use `workflow_run` to comment on PRs

---

cmake/Definitions.cmake
cmake/Packaging.cmake
res/dist/arch/PKGBUILD.in
src/gui/src/ServerConfigDialogBase.ui
src/lib/gui/constants.h
src/lib/gui/proxy/QSettingsProxy.cpp
src/lib/platform/MSWindowsClipboard.cpp
src/lib/platform/OSXScreen.mm

The 'symless.com' domain is used in various places.
Replace it with 'deskflow.org'
Note: Remaining 'symless.com' URLs will be removed when licensing is moved downstream to Synergy.

feat: change most domains to Deskflow

---

.env.example
.vscode/tasks.json
src/gui/src/MainWindow.cpp
src/lib/gui/VersionChecker.cpp
src/lib/gui/VersionChecker.h
src/lib/gui/config/AppConfig.cpp
src/lib/gui/config/AppConfig.h
src/lib/gui/env_vars.h
src/lib/gui/messages.cpp
src/lib/gui/messages.h
src/lib/gui/proxy/QNetworkAccessManagerProxy.cpp
src/lib/gui/proxy/QNetworkAccessManagerProxy.h
src/test/unittests/gui/VersionCheckerTests.cpp

Blocked by: https://github.com/deskflow/deskflow/pull/7552
Update checker features that don't request permission are often viewed as violating privacy. Incidentally, the assumed permission is a privacy obstacle for downstream package maintainers.
Instead of assuming permission to check for updates, ask for permission beforehand. We still need to keep the update checker for users who want to know when the next version is out, which is especially useful for Windows users.
_Note:_ The download URL still needs changing, but it's tangled up with the license code; so I'll fix that later once I'm moving all the customer stuff downstream.

feat: ask for permission before update check

---

.github/workflows/ci.yml
scripts/install_deps.py
scripts/lib/vcpkg.py

Fixes: #7540
Using the GitHub system-installed `vcpkg` seems to cause issues with caching. Instead, we will ignore the system-installed `vcpkg` and use our own local bootstrapped one; this seems to allow us greater control over caching. Using `restore-keys` seems to have no benefit, so this was removed.

ci: remove `restore-keys` for `vcpkg` and use local bootstrap

---

.github/workflows/ci-comment.yml

ci: use `github.event.workflow_run.id` for CI summary comment

---

.github/workflows/ci-comment.yml

ci: check for summaries dir before building message

---

.github/workflows/ci-comment.yml

ci: fixed syntax error in ci comment workflow

---

.github/workflows/ci.yml
src/lib/server/Server.cpp

Fixes: #4245
Blocked by: #7522, #7569
---
We now have a working prototype where onMouseMoveSecondary can be adjusted via an environment variable at startup. This implementation is server-side and relates to the issue discussed at #4245 (credit to @neworld for their initial implementation).
To double the mouse speed, use the following on the server side:
```
SYNERGY_MOUSE_ADJUSTMENT=2; open /Applications/Synergy.app
```
This results in consistent mouse speed across my Mac OS X server and HiDPI Windows client, achieving the desired functional outcome.
To reduce the speed, you can modify the value like so:
```
SYNERGY_MOUSE_ADJUSTMENT=0.3; open /Applications/Synergy.app
```
In the future, this could ideally be managed through the UI, with the ability to apply different speed adjustments for …

Update onMouseMoveSecondary to allow offset adjustments

---

config.yaml

Fixes: #7513
For some reason `aqt` is trying to download `6.7.3` even though it doesn't exist in [`official_releases/qt/6.7`](https://qt.mirror.constant.com/official_releases/qt/6.7/) on the Qt mirror.
Note: We have discussed using `vcpkg` instead of `aqt` on Windows, but this PR fixes the problem for now so we should land it before looking at using `vcpkg`. See: [Discussion on `vcpkg` vs `aqt`](https://github.com/deskflow/deskflow/discussions/7586)

ci: lock qt version to 6.7.2 on win/mac

---

cmake/Libraries.cmake

Rationale: `libei` 1.3 and `libportal` 0.8 are required for non-X support on both server and client, therefore setting these as minimum versions makes sense.

build: Bump min `libei` and `libportal` versions

---

.github/workflows/ci.yml
.github/workflows/sonarcloud-analysis.yml

We are using the old way to install `sonar-scanner` and `build-wrapper`, but there has been a GitHub action for a while now which simplifies the process.
This PR uses the [`sonarsource/sonarcloud-github-c-cpp`](https://github.com/SonarSource/sonarcloud-github-c-cpp) action to install `sonar-scanner` and `build-wrapper` instead of doing it manually as before. This PR should not change the behavior, but does decrease our maintenance burden.

Use `sonarsource/sonarcloud-github-c-cpp`

---

src/lib/gui/messages.cpp

Since we're not using the word beta in the version number, saying "beta" doesn't make sense. I reworded the message to reflect this.
I believe it still makes sense to have this message, so that people are aware that our Wayland support is still a WIP.

Remove word 'beta' from Wayland message

---

README.md

I'm re-wording the readme so it's a bit more relevant to the current state of the code (where all the commercial stuff has been moved downstream). [Preview](https://github.com/deskflow/deskflow/blob/readme-typos/README.md)

Make `README.md` more relevant to current repo state

---

.github/actions/init-python/action.yml
.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/lint-clang.yml
.github/workflows/lint-cmake.yml
.github/workflows/sonarcloud-analysis.yml
.github/workflows/valgrind-analysis.yml

Caching the `.venv` dir in CI was a bad idea, as it only saves a few seconds and causes a lot of complexity; where caching adds only negligible performance gains, we should always avoid it.
Fixes error on macOS:
```
Run ./scripts/install_deps.py
CI environment detected
Using virtual environment for: /Users/runner/work/deskflow/deskflow/scripts/install_deps.py
dyld[2337]: Library not loaded: /opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/Python
Referenced from: <CAFBC7FD-3E97-32A7-8EE8-EF3B8E2B346A> /Users/runner/work/deskflow/deskflow/.venv/bin/python
Reason: tried: '/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/Python' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/python@3.12/3.12.6/Framewor …
```

Remove Python `.venv` dir caching to reduce complexity

---

README.md

Blocked by: #7636 (though technically CI is redundant as it's just a docs change)
I believe this is a very important tennett to building a successful collaborative community. We must avoid the benevolent dictatorship problem that exists in other projects.

Add discussion value to project values in README.md

---

src/gui/src/AddClientDialog.cpp
src/gui/src/DataDownloader.cpp
src/gui/src/ServerConfigDialog.cpp

Requires: #7624 Landed first To Pass Lint
Update the Qt Connections to use the "Qt5" Style.

Use modern Qt connections in GUI

---

src/gui/src/main.cpp

The implicity default doesn't match the actual name of the desktop file.
This fixes e.g. the application icon on Wayland

fix: Set correct QGuiApplication::desktopFileName

---

src/gui/src/DeskflowApplication.cpp

On Plasma it is preferred to use the default Breeze style instead of Fusion
Breeze also has dark mode support out of the box, so no need to work around that

feat: Use native style on KDE Plasma

---

.github/workflows/ci.yml
cmake/Packaging.cmake

This should only ever be set from the outside, not the project itself
Distribution build systems will set it to the right value
This breaks installing it to a custom if desired

build: Don't force CMAKE_INSTALL_PREFIX

---

.github/workflows/ci.yml

- Adjust CI so that all jobs need linting to pass to run . 
- CI will not run if the PR only contains changes to these files:
- any md files  (README etc..)
-`.gitignore`
-`.gitattributes` 
- github `ISSUES_TEMPLATES`
-  `.env.example`
-  the `cspell.json` file

CI: Requires Lint to pass before running other jobs. Allow CI to be skipped for non code changes

---

.github/workflows/ci.yml
cmake/Build.cmake

This should not be used
It results in build failures when using different environments/toolchains that produce new warnings
This can especially happen on compiler or dependency updates

build: Drop warnings_as_errors

---

.github/workflows/ci.yml

- Allow for the Ci jobs `CI Passed` to run as long as its dependent jobs are have not ` failed` and were not `cancelled`
- Allow for the `Test results` job to be skipped if the windows , linux and macos jobs were also skipped

ci: fix how doc only jobs are scanned

---

.gitattributes

Don't add the items below to "Source" exports
-  `.github*`
-  `.gitattributes`
-  `.gitignore`

chore: add basic .gitattributes

---

.github/ISSUE_TEMPLATE/bug_report.yml

In an attempt to slow the duplicate Wayland portal issues being raised. 
- Add os option  for  Linux (X11) / Llinux (wayland)
- Add note for linux(wayland ) bug reporters to check the known issues first.
- Add note for mac os to check apples unknown dev guidance (i.e get unsigned app to run )

chore: add note known issues in bug_template

---

src/lib/deskflow/ClientApp.cpp
src/lib/deskflow/ServerApp.cpp

Broken "." position was fixed like this.
Before:
```
--display <display>  when in X mode, connect to the X server
at <display>
.      --no-xinitthreads    do not call XInitThreads()
```
After:
```
--display <display>  when in X mode, connect to the X server
at <display>.
--no-xinitthreads    do not call XInitThreads()
```

fix: align --display explanation in help message

---

README.md

I think it's important to help people understand the difference between Deskflow and Input Leap. e.g. We don't support Qt5, but IL seem to want to support Qt5.

Add leading edge philosophy to README.md

---

.github/actions/test-summary/action.yml
.github/workflows/test-actions.yml

Fixes: #7674 
In future: We should move the `test-summary` action and related code from `test-actions.yml` into a new actions repository, possibly in a personal repo. It could be useful for other projects and doesn't seem like something that needs to be maintained within Deskflow.

Fixed error count logic for test summary

---

.github/ISSUE_TEMPLATE/bug_report.yml

I fixed some things in the bug report template that were bugging me (no pun intended). I also noticed I was having to put "n/a" a lot in the setup and repro steps fields.

docs: Add other build type to bug report template

---

.github/workflows/codeql-analysis.yml

Copied ignore paths from `ci.yml` now that CodeQL Analysis is running on it's own trigger.

Ignore paths for CodeQL Analysis

---

.github/workflows/ci.yml

- Cache the stuff vcpkg puts in the build folder.

ci: vcpkg cache working

---

cmake/Libraries.cmake
src/lib/gui/tls/TlsCertificate.cpp

fix: Use `OPENSSL_EXE_DIR` instead of `OPENSSL_ROOT_DIR` on Windows

---

res/dist/arch/PKGBUILD.in

ci: Use `cmake` instead of `make` directly for Arch package

---

src/lib/deskflow/Config.cpp
src/test/integtests/deskflow/ConfigTests.cpp

ci: Catch std::exception on toml::parse_file

---

.github/workflows/ci.yml

Blocked by: #7741, #7752
- Integration tests are flakey by nature, make them optional on FreeBSD.
- This also includes a mini refactor of `ci.yml` to reduce some duplication.
Spotted a small issue while testing this: #7739

Optional FreeBSD integtests  and reduce CMake arg dupe

---

.github/ISSUE_TEMPLATE/bug_report.yml

I hate to add one more checkbox, but this is important as we keep asking it and sometimes forget. I also made one more field optional to reduce friction. Still no support for [radio buttons](https://github.com/orgs/community/discussions/4318) yet from GitHub.

docs: Checkbox for continuous build on bug template

---

res/dist/arch/PKGBUILD.in

In testing our ci arch build i noticed we were missing 
- tomlplusplus 
- cli11 
from our depends list, since our ci has them we need them on the machine using the package.

build: arch package requires tomlplusplus and cli11

---

.github/workflows/ci.yml

- New mac for mac os 
-  Use Brew to get `cmake`, `openssl` and `googletest`
-  Qt Install action to install Qt. 
-  Allow cmake fetch and embed, `tomlplusplus` and `cli11` fix #7759
- New `env.CMAKE_CONFIGURE` holds our basic cmake command 
- `cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_WARNINGS_AS_ERRORS=ON`
- Use this everywhere we can

ci: New macOS CI with Qt action

---

README.md

Someone told me they got confused when they read this recently:
> Nothing customer-related (this is all moved downstream to Synergy)
They thought it meant:
> "No GUI here, downstream keeps all the good stuff to themselves."
People are cynical.
Perhaps we should remove it, or reword it?
The original intent was to mean:
> "We removed the code that checks for serial keys, switches features based on the serial key, etc. That is now only in Synergy downstream."
It was also meant to communicate:
> "Deskflow isn't orchestrated by Symless and isn't directed to satisfy only Synergy customer needs."
Perhaps one of these ideas or something else:
- We don't put the cart before the horse; downstream does not dictate what we work on.
- Commercial needs have been moved downstream, keeping us focused on …

docs: Remove confusing value line in readme

---

README.md

add a tip for mac users to run xattr -c on the app post download
[Preview](https://github.com/deskflow/deskflow/blob/readme-update-2/README.md)

docs: readme add mac os xattr note

---

README.md

For Synergy to provide sponsorship, it's important that the project links to Synergy as well as endorsing it. Also the sentence, "while maintaining its customer-oriented code downstream" can easily be misinterpreted, so it's removed.
[Preview](https://github.com/deskflow/deskflow/blob/readme-sponsor/README.md)

Update README.md to restore sponsor link

---

README.md

Sponsor link should have been `/synergy`.
[Preview](https://github.com/deskflow/deskflow/blob/readme-sponsor-2/README.md)

docs: Fixed sponsor link in README

---

src/lib/gui/dialogs/SettingsDialog.h

- Removing unused CoreApp includes.

chore: settingsDialog rm unused CoreTool include

---

CMakeLists.txt
doc/CMakeLists.txt

typo doc target is `user-docs`
- Remove `DOCS` option for `BUILD_DOCS` 
Breaks builds with `BUILD_DOCS` on or doxygen and it not specified .

doc: correct target for documents

---

.github/workflows/ci.yml

This is in response to the discussion  https://github.com/deskflow/deskflow/discussions/7837 
Ideally we would like to have the continuous not marked a pre-release while also not being tagged the `latest` release . Since we are not able todo this without making the release step more complicated then it should be we will use `pre-release` until we are able to either not create or not hyjack the latest tag.

ci: use pre-release for continuous to stop it from grabbing latest tag

---

.github/actions/get-version/action.yml

the get-version action should always return a full 4 part version string from describe

ci: git-version-action: Always report described version

---

scripts/package.py

modified the package script to use the name we want from cpack
Packages not made by cmake are now named: 
`deskflow-version_win64.msi`
`deskflow-version_mac_x64.msi`
`deskflow-version_mac_arm64.msi`

ci: adjust pacakge script to use the names we would like when in cpack

---

res/dist/mac/bundle/Contents/Info.plist.in
res/win/version.rc.in

Have the entry for windows / mac binaries say 
© 2024 Deskflow Developers

build: add deskflow devs to binaries copyright

---

README.md

Add info about our new [homebrew tap](https://github.com/deskflow/homebrew-tap) to the [Readme](https://github.com/deskflow/deskflow/blob/brewtap/README.md)

chore: add homebrew tap info to readme

---

src/lib/deskflow/Screen.cpp

These asserts in particular keep catching me in debug. They don't seem to have any adverse effect in release build, so they'll probably be more useful as warnings.
Related to, but doesn't necessarily solve: #7863

chore: Replace screen leave/enter asserts with warnings

---

.github/actions/get-version/action.yml
.github/workflows/ci.yml
CMakeLists.txt

A Change to the release workflow that we missed having not tagged yet. 
- Strip `refs/tags/v` from the `DESKFLOW_PACKAGE_VERSION`  that the get-version action reports when run on a `v` tag
- Release step can run if the ref is 'master ' or a tag   It can not be both
Note: release steps:
- Bump the version in the main CMakeLists.txt
- Make PR (like this)  
After landing.
- Tag the commit with an annotated tag like `git tag -a v1.71.1 -m "v1.17.1"`
- Push the tag  `git push origin v1.17.1`

Prepare 1.17.1

---

README.md

- Change the [readme](https://github.com/deskflow/deskflow/blob/readme-latest-link/README.md) to use 'latest' for the stable tag

docs: Update readme to use latest for the stable link

---

src/gui/src/MainWindow.cpp
src/gui/src/dialogs/SettingsDialog.cpp
src/gui/src/dialogs/SettingsDialog.h
src/gui/src/dialogs/SettingsDialog.ui

Fixes #7890  By exposing a check box in the application settings to enable or disable the check
- Add the option to enable or disable update checks in the settings dialog
- Fix the SettingsDialog UI files so it stops generating invalid Alignment values when the form is edited.
- Use `AppConfig` object directly in the SettingsDialog
- Fix an issue where the initial setting for auto update is not set.

Gui: Expose Check for updates option

---

README.md

`brew instal` works as intended, but only because Homebrew has aliases for a few common typos. Changed to `brew install`

fix: single typo in README.md

---

CMakeLists.txt
deploy/org.deskflow.deskflow.metainfo.xml

after landing must tag v1.17.2 
`git tag -a v.117.2 -m"v1.17.2"`
`git push orgin v1.17.2`
Stage for 1.17.2 release.

Release 1.17.2

---

.github/workflows/continuous-integration.yml
cmake/Packaging.cmake
deploy/dist/flatpak/org.deskflow.deskflow.yml
deploy/org.deskflow.deskflow.metainfo.xml

- Adjust the generated name for flatpak artifacts. `deskflow-version-linux-arch.flatpak`
- Do not cleanup /lib/debug from the generated flatpak
- Fallback to 'linux' if `DISTRO_NAME` is empty
- Update the description in the metadata
- User `master` version of flatpak builder
- Use `x86_64` for linux job name sufixes

Flatpak nits

---

README.md

Updates to the readme [Preview](https://github.com/deskflow/deskflow/blob/readme_updates_2/README.md)
- Add a note that Windows 10+ is needed to run the GUI  fixes: #7917 
- Add flathub dl badge

Add windows requirement and flathub link to readme

---

CMakeLists.txt

Removing the Define for `NDEBUG` was a mistake 
1. Set `NDEBUG` in main CMakeLists.txt when needed
2. Make note to unify the logic to not need this define

ReAdd NDEBUG define

---

README.md

When looking at #7969 I noticed that our readme currently lacks a note about the minimum required version for macOS so i have added a note.

chore: Add minimum macOS version to readme

---

src/gui/src/MainWindow.cpp

- Fix up the tray icon so the app shows or hides when the icon is Clicked 
- Remove Show / Hide from the trayMenu
- Remove Show from the window menu , it is not possible to trigger this its disabled when the window is shown

fix: Tray Icon Click to hide / show

---

src/gui/src/dialogs/SettingsDialog.cpp
src/gui/src/dialogs/SettingsDialog.ui

fixes #7949 
- Adjust Settings Dialog groupboxes to be maximum (take up the most vertical space they could need)
- Adjust Settings Dialog to have a fixedHeight based on content height
- Settings Dialog is now Modal 
- Remove Unneeed window hints from the settings dialog

Fix: #7949 Use correct sizing for Settings Dialog

---

src/lib/base/Unicode.cpp

The data pointer needs to move before decoding the second surrogate, and not after. Because of this the first surrogate was begin decoded again, resulting in an invalid codepoint.
This affected clipboard operations originating on Windows machines, where the text in CF_UNICODE is encoded in UTF-16 and copying characters from a high plane (like emojis) was broken.

Fixed UTF-16 surrogate handling

---

scripts/lint_clang.py
src/gui/src/AppDelegate.mm
src/gui/src/MainWindow.cpp
src/gui/src/TrayIcon.cpp
src/gui/src/TrayIcon.h
src/lib/gui/OSXHelpers.h
src/lib/gui/OSXHelpers.mm
src/lib/platform/OSXDragSimulator.m
src/lib/platform/OSXDragView.m
src/lib/platform/OSXMediaKeySupport.m
src/lib/platform/OSXPasteboardPeeker.m
src/lib/platform/OSXScreen.mm
src/lib/platform/OSXScreenSaverUtil.m

General:
- Use QList<QAction*> instead of a std::vector<QAction*>
- Clean up the `showAndActivate` Logic just show always no matter the previous state
- Clang-Format the `.m` and `.mm` files ( I had to edit one so i did a commit formatting them all) 
- Added *.m and *.mm to `scipts/lint-clang.py`
Update the tray for mac OS
-  Do not show / hide when the icon is pressed
-  Show "Bring Window to Front"  in the tray menu (ActionRestore)
- "Bring Window to Front" works when the app is hidden with ⌘ + H

Improve the macOS tray UX

---

src/lib/server/ClientListener.cpp

With this You will be prompted to allow new clients the first time they attempt to connect.
If you ignore them they are ignored until the server restarts. If you accept them you will be asked to add them to your server layout (once).
Part of #7806

Fix(CVE-2021-42075): Close TCP connections after handshake failures

---

src/lib/server/Config.cpp

fixes https://github.com/deskflow/deskflow/issues/7942

fix: #7942, Correctly substitute config name part

---

src/lib/deskflow/ServerApp.h

fixes: #7940 
fixes: #7941 
by using std::string 's insert method in place is %s sub for the static string

Fix: #7940 and #7941

---

src/apps/deskflow-gui/MainWindow.cpp
src/apps/deskflow-gui/MainWindow.h
src/apps/deskflow-gui/MainWindow.ui
src/lib/gui/config/AppConfig.cpp
src/lib/gui/config/AppConfig.h

Add the ability to toggle the log (its state is saved on exit)
When Deskflow's log is collapsed the widow's size is fixed: 
If you expand the log: you can resize how you like and this size is remembered if you close the log it goes back to the above state.

feat: Visiblity toggle for the log on the main window

---

src/apps/deskflow-gui/dialogs/SettingsDialog.cpp
src/apps/deskflow-gui/main.cpp

- Use `QApplication::` in place of `qApp->`

chore: use static QApplication members where possible

---

src/apps/deskflow-gui/MainWindow.cpp

- Fix show and activate on mac os (need showNormal after all)
- make a duplicate quit action for the tray menu on mac os
- Fixes #8012

fix: Mac os gui nits

---

src/apps/deskflow-gui/main.cpp

IDK why, but on Fedora, `QT_LOGGING_RULES` is set in a way that turns off `qDebug()`. We have our own env var, `DESKFLOW_GUI_DEBUG` to turn on debug logging, so I think overriding `QT_LOGGING_RULES` should be ok. 
Open to alternatives.

fix: `qDebug` doesn't work on Fedora

---

.github/workflows/continuous-integration.yml

on windows `x.y` needs to be quoted.

Release v.18.0, with proper win package

---

src/apps/deskflow-gui/dialogs/AboutDialog.cpp
src/apps/deskflow-gui/dialogs/AboutDialog.h

Set it so the AboutDialog's copy version button copies the entire version number shown. 
Before it would capture only the kVersion (x.y.z.t) now its also will include any SHA if added to the dialo. This will make it easier to compare dev versions that are still PRs in cases where the generated version would be the same as another PR version due to them having the same number of commits to add on top of master.

refactor: Copy the full version string on the about dialog

---

src/lib/platform/EiKeyState.cpp
src/lib/platform/EiScreen.cpp

fixes #8017 
For the wayland backend these messages are now under the `Debug` Context
- `failed to create xkb context: Resource temporarily unavailable`
-  `logical output size: 1536x864@0.0`

fix: 8017, move wayland notes to debug context

---

src/apps/deskflow-gui/MainWindow.cpp
src/apps/deskflow-gui/MainWindow.h

Fixes the mac os tray quit not working (forgot to connect it to something) 
Added a single method `MainWindow::quitApp` for both quit actions to call

fix: Unify both Quit actions to use the same function

---

src/apps/deskflow-gui/MainWindow.cpp
src/apps/deskflow-gui/MainWindow.ui

This fixes the TLS fingerprint not being visible when enabled. moves it from the server box to the main window area and shows it no matter the mode.
- Be sure to call `updateLocalFingerprint` when we apply a new config
fixes: #7924

fix: The Tls Fingerprint label not being shown on start up

---

src/apps/deskflow-gui/MainWindow.cpp

- Fixes the access prompt for wayland starts under the main dialog.

fix: Wayland Prompt starts under MainWindow

---

src/lib/gui/constants.h

Update suggested tray support on gnome to link  [Appindicator support](https://extensions.gnome.org/extension/615/appindicator-support/)

chore: update gnome tray fix link 

---

src/apps/deskflow-gui/MainWindow.cpp
src/apps/deskflow-gui/MainWindow.h
src/lib/gui/OSXHelpers.h
src/lib/gui/OSXHelpers.mm

- Resolving Quitting vs Hiding in the `MainWindow::CloseEvent`
- This simplifies the code around hiding and quiting alot
- Remove unneeded `MainWindow::onAppAboutToQuit` slot 
- Use Mac OS Native Hide on macOS to "hide to tray"

Proper hide to tray

---

deploy/mac/deploy.cmake
src/apps/deskflow-gui/CMakeLists.txt

Make it easier to run the locally built binaries on mac os by not running macdeployqt on app copies outside of a package staging directory.

Run MacDeployQt at install time on staged app only

---

deploy/mac/deploy.cmake
src/apps/deskflow-gui/CMakeLists.txt

#8037 now breaks mac os CI builds as they are made w/o rpath this fixes that by defining the rpath in the gui's properties.

build:  set macOS RPATH for the gui via property

---

deploy/mac/deploy.cmake

TLDR:
1. We can use "Open Anyway" again
2. Removes the need for the second Deskflow permission in accessibility 
3. Fingers crossed No more permission removal and reassignment after "upgrading" Deskflow
Sign the app with a local dummy cert when building. This allows us to "distribute" and have users see the old this is untrusted dialog where they can use "Open Anyway" in setting to bypass it (no longer do they have to use xattr -c as the only method to initially run the application
This also seams to have the added side effect of the accessibility panel only showing ONE Deskflow entry and only asking once not neeed to ask again when connected to a server or when switching to server mode.

Macos Sign the App with local cert

---

CMakeLists.txt
deploy/windows/deploy.cmake
src/apps/deskflow-gui/CMakeLists.txt

- Run `windeployqt` at install time on package stage
- Prevent package creation when the build is configured for debug

Fix windows debug builds

---

src/apps/deskflow-gui/VersionChecker.cpp

- noticed then when scanning for issues with `clazy`

Version Checker use case insensitive compare in place of toLower()

---

CMakeLists.txt

fixes https://github.com/deskflow/deskflow/issues/8033
- Use the fallback version if the local copy has no tags 
- This version will have a tweak of `9999` to make sure the SHA is show in the about dialog

Configure with the Fallback version if git found with out tags

---

src/lib/deskflow/ProtocolUtil.cpp
src/lib/deskflow/ProtocolUtil.h

This is a candidate fix for https://github.com/deskflow/deskflow/issues/8016.
[This line](https://github.com/deskflow/deskflow/commit/ab44559df6ebcd18c4a7fa088dbc608c75981d6e#diff-4ada4360f34addf3e4ad4389e49967a9617ba8b22b9da1c1fc682370e0062a24R180): `UInt32 n = read4BytesInt(stream);` added to `ProtocolUtil::vreadf` in commit https://github.com/deskflow/deskflow/commit/ab44559df6ebcd18c4a7fa088dbc608c75981d6e reads the length of a vector that is then re-read again in `readVector4BytesInt` (or `readVector1BytesInt` or `readVector2BytesInt`.) That second read eats the first 4 bytes of the content, interprets them as a length, and reads the shortest of that misinterpreted length and what's available on the stream. The read buffer is offset by the 4 missing bytes from the original. …

fix: messages read into vector are cut off by 4 bytes

---

src/apps/deskflow-gui/MainWindow.cpp
src/apps/deskflow-gui/MainWindow.h
src/apps/deskflow-gui/main.cpp

- allow only one instance of the gui to be running 
- When in the background opening a new instance should pop up the current one , this should work nicely in places with out tray support. 
- fixes #7975 
- fixes #5304 (as a tray icon is not really needed to get the running instance back now)
Test Results: 
-  [x] Mac OS:
-  [X] macOS Restores when window is minimized
-  [X] macOS Restores when window is hidden
-  [X] macOS Restores when window was closed, Needs: https://github.com/deskflow/deskflow/pull/8034
-  [X] Linux (Wayland):
-  [X] Wayland Restores when window is minimized
*Wayland doesn't allow for this on all De's the Icon flashes to request you look at the window instead
-  [X] Wayland Restores when window is hidden
-  [X] Wayland Restores when window was closed
-  [X] Linux …

Allow only one instance of the gui

---

src/apps/deskflow-gui/Action.cpp
src/apps/deskflow-gui/Action.h

a modified port of my Action related changes from https://github.com/input-leap/input-leap/pull/1829
- Fix private vars name to `m_foo`
-  Use arg substitution / and not concatantion
-  Create a SettingsKeys namespace for the settings keys
-  Remove redundant switch case (restart)
-  Remove a pointless Assert
-  Use inline static const QStringList inplace char*[]

Port Action improvements from IL

---

src/lib/gui/config/AppConfig.cpp
src/lib/gui/config/AppConfig.h

- save the setting for the tray icon color introduced in #8054

fix: Save the try icon setting

---

deploy/mac/deploy.cmake

Hotfix, typo in the name of the mac deploy tool prevents it from running on package.

build: run macdeployqt on package

---

src/lib/platform/OSXScreen.mm

based on https://github.com/input-leap/input-leap/pull/2116 by @spottenn 
Entering the screen at the top of enter should ensure new event happen on the screen.

fix: Enter screen on mac os asap to ensure event hand off

---

src/apps/deskflow-gui/dialogs/ActionDialog.cpp
src/apps/deskflow-gui/dialogs/ActionDialog.h
src/apps/deskflow-gui/dialogs/ActionDialog.ui
src/apps/deskflow-gui/dialogs/ServerConfigDialog.ui
src/apps/deskflow-gui/widgets/KeySequenceWidget.cpp
src/apps/deskflow-gui/widgets/KeySequenceWidget.h

a Modified port the updates i made to the Action Dialog in Input Leap
- Replace user facing string of `screen` -> `computer`
https://github.com/input-leap/input-leap/pull/1837
https://github.com/input-leap/input-leap/pull/1838
https://github.com/input-leap/input-leap/pull/1830
(FROM IL PR)
This Pr will be used to Improve the UX for the Action Dialog
Before: 
After Ui:
Key press, toggle and release look the same but different action strings

Improve the Action Dialog UX

---

src/apps/deskflow-gui/dialogs/SettingsDialog.cpp
src/apps/deskflow-gui/main.cpp

- Remove two more unused `DESKFLOW_GUI` Defines

chore: remove unused GUI_HOOK

---

README.md
deploy/linux/arch/PKGBUILD.in

- Update linux info on the readme to not say specific distros but instead the need for ei / portal and Qt(for the gui) 
-Add conflicts to the pkgbuild for arch , license is updated to w/ ssl exception string and do not install extra copy of the license

Add Arch conflict package and update linux readme info

---

src/apps/deskflow-gui/MainWindow.cpp
src/apps/deskflow-gui/MainWindow.h

When testing XFCE i noticed that their tray impl blocks the "activated" state of the tray so its not possible to hide / show by clicking on it (like mac os). This PR fixes this by
- Add `Open Deskflow` and `Minimize to tray` to the tray menu
- Added a second action for the tray's Quit action (mac os will move the first and this is incase others do too)
- Remove the window menu (the hide show happens on window close or via the tray icon now)
- Remove old code used on mac os to hide the dock icon when the window is not visible (it does not work and our new native code is less code and works) 
fixes: #8095  (it seams not all GNOME Tray exts allow you "activate" either)

Tray menu include show hide

---

.github/workflows/continuous-integration.yml

resolve #7785 
This happened finally https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
- Debian 13
- Fedora 41
- Opensuse tumbleweed
- Windows
- Github has not released windows arm runners
- Arch
- There is no official archarm image for us to build with . dockerhub's newest is over a year old
- flatpak 
- All the parts are in place within the CI job
- The flatpak builder image we use does not support arm.
- We need to either set up ubuntu with flatpak builder ourselves or wait for an image.

CI: Build Arm Packages for Debian, Fedora and Opensuse

---

README.md

Synergy 3 uses mDNS which makes it incompatible for now.

docs: Indicate S1/S3 compatibility in README

---

src/lib/platform/EiKeyState.cpp

On some systems, the keymap file provided by Ei required to create the XKB context is not properly seeked to the start.
This will cause reading the file to fail (or, more accurately, just cause 0 bytes to be read), causing the keymap to just default to a US-keymap.
This PR fixes this, causing the correct keymap to be loaded.
See input-leap/input-leap#2158

Fix keymap not correctly loading for the Ei backend

---

.github/workflows/continuous-integration.yml
src/apps/deskflow-gui/MainWindow.cpp
src/apps/deskflow-gui/dialogs/SettingsDialog.cpp

For some reason when the CI builds the mac os don't show the "deskflow" or "deskflow-symbolic" icons.
- bump mac os qt to 6.7.3
- Attempt to force the icons on mac os

fix: mac os tray icon not showing

---

src/apps/deskflow-client/CMakeLists.txt
src/apps/deskflow-core/CMakeLists.txt
src/apps/deskflow-server/CMakeLists.txt

Fixes #8119 (using the same method as pr #6649)

fix: #8119, by adding missing BSD checks for installing deskflow binaries

---

src/lib/deskflow/ClientApp.cpp
src/lib/deskflow/KeyMap.cpp
src/lib/deskflow/unix/AppUtilUnix.cpp
src/lib/deskflow/win32/AppUtilWindows.cpp
src/lib/gui/core/CoreProcess.cpp
src/lib/platform/EiKeyState.cpp
src/lib/platform/EiScreen.cpp
src/lib/platform/MSWindowsClipboard.cpp
src/lib/platform/MSWindowsScreen.cpp
src/lib/platform/OSXClipboard.cpp
src/lib/platform/XWindowsClipboard.cpp
src/lib/platform/XWindowsPowerManager.cpp

This change may help us turn up some everyday problems in the field that get missed due to not using debug log level.
This could also make the log a bit noisier, so at a later date we may need to downgrade anything that is too noisy/not helpful or not actually a failure/warning.

refactor: Use correct log level for failure messages

---

src/apps/deskflow-gui/MainWindow.cpp

use symbolic tray icon on mac os and mask it properly

fix: correctly mask symbolic icon on mac os

---

deploy/linux/deploy.cmake

The deepin and uos are debian liked OS, but they do define "ID_LIKE".
Log: enable cpack as DEB for deepin|uos.

chore: enable cpack as DEB for deepin|uos

---

.github/workflows/continuous-integration.yml

- dont save the flatpak cache based on github.sha...

ci:use -1.0 as tag for flatpak builder

---

README.md

Right now we're only seeing bounty interest through Algora's network of developers.
We can increase the number of potential contributors aware of bounties by making this prominent on our README.

docs: Update README.md to raise awareness of bounties

---

src/lib/base/String.cpp
src/lib/base/String.h
src/lib/net/InverseSockets/SslApi.cpp
src/lib/net/SecureSocket.cpp
src/test/unittests/base/StringTests.cpp

Clean up some of our String methods
- `String.cpp` does not need the access to `ARCH` 
- modified `void String::toHex(...)` -> `std::string String::toHex(...)` will now return a std::string;
- added `int String::fromHexChar(char c)`
- added `std::vector<uint8_t> string::fromHex(const std::string&)`
- Update copyright to SPDX format
#8098  Should base upon this and remove modifications to the `String` Class

chore: add missing String methods

---

README.md

The link was only showing open issues, which doesn't make sense for rewarded bounties (which are closed).
[Preview](https://github.com/deskflow/deskflow/blob/f6e93914f5006e0e04a02c92350c0cff4f02e81f/README.md)

docs: Fixed incorrect link on README.md for rewarded bounties

---

README.md

Fix up the [Readme](https://github.com/deskflow/deskflow/blob/updateReadme/README.md) to use the new link for the openSSL Exception.

docs: update openSSL exception link

---

src/apps/deskflow-gui/MainWindow.cpp

Fixes.
- macOs the theme icon falls back to the low detail 16x16 icon instead of the higher detail one.

refactor: force mac os to use the larger security icon for the status area

---

src/apps/deskflow-gui/CMakeLists.txt
src/apps/deskflow-gui/ScreenSetupModel.cpp
src/apps/deskflow-gui/ServerConfig.cpp
src/apps/deskflow-gui/dialogs/ServerConfigDialog.cpp
src/apps/deskflow-gui/dialogs/ServerConfigDialog.ui
src/apps/deskflow-gui/widgets/NewScreenWidget.cpp
src/apps/deskflow-gui/widgets/NewScreenWidget.h
src/apps/deskflow-gui/widgets/ScreenSetupView.cpp
src/apps/deskflow-gui/widgets/ScreenSetupView.h
src/lib/gui/config/Screen.cpp
src/lib/gui/config/Screen.h

- Fix #8155 
- "Return Early Return Often"  in `ScreenSetupModel::data method`
-  Bring back the `NewScreenWidget`
-  `QTextStream& screen::writeScreensSection(QTextStream&)` -> `QString Screen::screenSection()`
-  `QTextStream& screen::writeAliasSection(QTextStream&)` -> `QString Screen::aliasSection()`

Fix: Screen icons not showing on the screen setup tab

---

src/lib/platform/PortalInputCapture.cpp
src/lib/platform/PortalInputCapture.h

The options argument was missing so the argument data wasn't the right one and the method cb_disabled was actually called on a GVariant* instead on a PortalInputCapture*
This probably fix #8147 because in implementations when the screen size change, the `disabled` signal is sent, but that call is not handle by us due to a bad signature, this lead to a stall.

input-capture: Fix disabled call

---

README.md

- Add note to the readme's wayland section pointing to the known issues.
replaces #8160

docs: Link to the known wayland issues in the readme

---

src/test/unittests/gui/core/CoreProcessTests.cpp

The server always create an empty config file in user's home dir, set tmp config file path for the unittest in order to fix this issue.
Log: Fix unittest create empty config file.
fixes: #8174

fix: [test]fix #8174, create empty config file under HOME dir

---

src/apps/deskflow-core/CMakeLists.txt
src/apps/deskflow-core/deskflow-core.cpp
src/apps/deskflow-gui/MainWindow.cpp
src/apps/deskflow-gui/MainWindow.h
src/lib/deskflow/CMakeLists.txt
src/lib/gui/core/CoreProcess.cpp
src/lib/gui/core/CoreProcess.h
src/lib/gui/messages.cpp
src/lib/platform/CMakeLists.txt
src/lib/platform/MSWindowsWatchdog.cpp

Parts of #8180 that are easier to land first.
- Clean up of white space
- `src/apps/deskflow-gui/MainWindow.cpp`
- `lib/deskflow/CMakeLists.txt`
- `src/lib/gui/messages.cpp`
- MainWindow Remove some unneeded intermediary methods (one was renamed in https://github.com/deskflow/deskflow/pull/8180/commits/eaf6326e90da1f20a69b40121091dd9cd6cac514)
- Set the icon for deskflow-core
- [fix: Out of order m_trayIcon in ctor init](https://github.com/deskflow/deskflow/pull/8180/commits/1e32c2efaf92c6042238981af76749996d4f2293)
- modified to remove unused m_btnCancel
- [Rename core process start/stop function names](https://github.com/deskflow/deskflow/pull/8180/commits/e236f17d749d1cfbc7e7557a0c085a71b96c7d46)
- [Cleanup core binary help text](https://github.com/deskflow/deskflow/pull/8180/commits/b8 …

Parts of #8180 that are easy to land first

---

src/apps/deskflow-gui/MainWindow.cpp
src/apps/deskflow-gui/MainWindow.h
src/lib/gui/core/ServerConnection.cpp
src/lib/gui/core/ServerConnection.h
src/lib/gui/messages.cpp
src/lib/gui/messages.h

Some small cleanups we missed on peerbase. 
- Add a method to get the `MainWindow::trustedFingerprintDb`
- Adjust the message box bool (yet again) to even better name `serverRequiresPeerAuth`
- Simplify `MainWindow::checkFingerprints`
- rename `MainWindow::localFingerPrintDb` => `MainWindow::localFingerprintDb`

Post peer base clean

---

SECURITY.md

On the [security page](https://github.com/deskflow/deskflow/security), the 'Set up a security policy' button creates a file called `SECURITY.md`:

Create GitHub recommended security policy file

---

REUSE.toml

I though the file was going in to .github/ so i didn't check the spdx info.. ive added the file to the REUSE.toml This will fix the reuse lint failure

fix: missing reuse info for SECURITY.md file

---

src/apps/deskflow-server/deskflow-server.cpp
src/lib/arch/win32/ArchMiscWindows.cpp
src/lib/arch/win32/ArchMiscWindows.h
src/lib/deskflow/App.cpp
src/lib/deskflow/App.h
src/lib/deskflow/AppUtil.h
src/lib/deskflow/ArgParser.cpp
src/lib/deskflow/ArgsBase.h
src/lib/deskflow/DaemonApp.cpp
src/lib/deskflow/IAppUtil.h
src/lib/deskflow/win32/AppUtilWindows.cpp
src/lib/deskflow/win32/AppUtilWindows.h
src/lib/platform/CMakeLists.txt
src/lib/platform/MSWindowsDesks.cpp
src/lib/platform/MSWindowsProcess.cpp
src/lib/platform/MSWindowsProcess.h
src/lib/platform/MSWindowsScreen.cpp
src/lib/platform/MSWindowsSession.cpp
src/lib/platform/MSWindowsSession.h
src/lib/platform/MSWindowsWatchdog.cpp
src/lib/platform/MSWindowsWatchdog.h
src/test/unittests/deskflow/ArgParserTests.cpp

Fixes: #8183
Blocks: 
- #8180
- #7804
Restores some of the code deleted in fb686ede21413eee5e9f92fce917438388bdc9ce (#7827) which is needed to run the core process in secure desktops (UAC prompts, login, lock screen, etc). I thought I tested PR #7827 pretty thoroughly (https://github.com/deskflow/deskflow/pull/7827#issuecomment-2447209735) but it looks like I made a mistake and wasn't thorough enough.
This time we're using ~~deskflow-core.exe~~ `deskflow-server.exe` (temporarily until core bin ships) instead of `deskflow-legacy.exe` to find the active desktop name (which is not accessible to processes running in session 0).
Use 'Automatic' elevation:
Right click any app and click 'Run as administrator' to show the UAC dialog.
Expect: Mouse should work on client

fix: Restore active desktop name check in Windows daemon

---

.github/actions/install-dependencies/action.yml
.github/workflows/continuous-integration.yml
vcpkg-configuration.json
vcpkg.json

Speed up the windows CI
- bump qt install action to install qt 6.8.2
- use Qt action for windows
- do not use the vcpkg classic mode for CI builds, this prevents the `vcpkg.json` from not installing Qt for local builds.
- fixes https://github.com/deskflow/deskflow/issues/7976

Speed up the windows CI action build time

---

src/lib/base/log_outputters.cpp
src/lib/base/log_outputters.h
src/lib/deskflow/App.cpp
src/lib/deskflow/App.h
src/lib/deskflow/ArgsBase.h

As noted in https://github.com/deskflow/deskflow/issues/8107#issuecomment-2678563921
- Removed the mentioned item
- Remove the BufferlogOutputter as its not unused but did so in its own commit incase we need it back later.

Clean up a few items missed when removing the legacy tray

---

src/apps/deskflow-gui/MainWindow.cpp
src/apps/deskflow-gui/VersionChecker.cpp
src/lib/gui/styles.h

Naturally mac os had to do something with the style for the status buttons... 
-  fixes #8247
- Use `QStringLiteral` for style literal
- Create a style for flat buttons and those with highlight 
- use the styles for `btnToggleLog`,`btnUpdate` and `btnFingerprints`
The `btnToggleLog` should be flat and look like a label (when hovered the widget style may color it the highlight color, breeze does other don't its upto the style in that case) 
The `btnUpdate` and `btnFingerprints` should look flat and when hovered have a border that is 1px of your highlight color in my case blue on my mac)  The tooltip should look normal
Normal:
Hover

Toolbutton style

---

.github/ISSUE_TEMPLATE/bug_report.yml

Pasting the version info (from the copy button) to bug reports is awkward because it's a single line field. 
Expanding the field to a text area will make it easier to report bugs.

docs: Expand version field on `bug_report.yml`

---

src/apps/deskflow-gui/dialogs/AboutDialog.cpp
src/apps/deskflow-gui/dialogs/AboutDialog.h
src/apps/deskflow-gui/dialogs/AboutDialog.ui

- Remove unused icon path string const variables 
- Update about box to have icon credit and a scrollarea to allow for future explanation to talk about important devs

chore: add icon credit to about box

---

src/apps/deskflow-gui/MainWindow.cpp
src/apps/deskflow-gui/MainWindow.h
src/apps/deskflow-gui/MainWindow.ui
src/apps/deskflow-gui/dialogs/SettingsDialog.cpp
src/apps/deskflow-gui/dialogs/SettingsDialog.h
src/apps/deskflow-gui/dialogs/SettingsDialog.ui
src/apps/res/deskflow.qrc

Allow for rename on the mainwindow
Normal
When Editing, (note the size is the same i had to capture it differently to get the tooltip also, tooltip is normal tooltip not always shown, my cursor was not captured in the image )

refactor: MainWindow: Update name change

---

.github/workflows/continuous-integration.yml
REUSE.toml
deploy/linux/flatpak/ci-build-lint-exceptions.json

Images are broken in our CI build flatpaks
By default the linter for the flathub flatpak builder wants you to upload the screenshots to flathub, since our CI does not the images are blank in the resluting flatref , this skips the builder from remaking the screen shot links and tells the linter to not fail us because we did not upload the image to flathub.

ci: Fix missing screenshots in CI generated flatpaks

---

src/apps/deskflow-gui/dialogs/SettingsDialog.ui

- The Settings starts with the `Require peer certificates` checkbox focused this fixes that to start on the tab and corrects the tab order for the page
- Remove all the defaults from the ui. QtC add the property to teh ui file when you change the value from the default but does not automatically remove it when you set it back to the default value, leading to some unneeded lines in the ui file itself. This will not change the gui at all but make the ui file smaller by about 2k, by not adding the properties with values equal to their default.

Adjust settings tab order

---

src/apps/deskflow-client/CMakeLists.txt
src/apps/deskflow-core/CMakeLists.txt
src/apps/deskflow-server/CMakeLists.txt

Need to publiclly link Qt in the deskflow lib for mac os

fix: set rpath for client, server and core

---

src/apps/deskflow-gui/MainWindow.cpp

Stops the core process in client mode while the client it validating fingerprints of the server, this has two benefits
1. The Client no longer repeatably try to connect while the user is looking at the fingerprints of the server. So the Connection failed message mentioned in #8267 is no longer spawned.
2. The Server will not be spammed with connection attempts at this time from the connecting client.
I fail to see any downside to this since the any client may only be connected to a single server.  I tested this on the with a client using auto connect to a name with two servers using the same name one accepted and one not and the client only talks to the proper one the fingerprint dialog is not even show, so it does not look like a rouge server can use this as a DDOS of the client.
fixes …

fix: Do stop the client on fingerprint dialog

---

src/apps/deskflow-daemon/deskflow-daemon.cpp
src/apps/deskflow-gui/MainWindow.cpp
src/lib/arch/IArchSystem.h
src/lib/arch/unix/ArchSystemUnix.cpp
src/lib/arch/unix/ArchSystemUnix.h
src/lib/arch/win32/ArchMiscWindows.cpp
src/lib/arch/win32/ArchMiscWindows.h
src/lib/arch/win32/ArchSystemWindows.cpp
src/lib/arch/win32/ArchSystemWindows.h
src/lib/common/constants.h.in
src/lib/deskflow/DaemonApp.cpp
src/lib/deskflow/DaemonApp.h
src/lib/deskflow/ipc/DaemonIpcServer.cpp
src/lib/deskflow/ipc/DaemonIpcServer.h
src/lib/gui/core/CoreProcess.cpp
src/lib/gui/core/CoreProcess.h
src/lib/gui/ipc/DaemonIpcClient.cpp
src/lib/gui/ipc/DaemonIpcClient.h

Fixes: #8227
To test: 
1. Use Windows
2. Click 'Help'
3. Click 'Clear settings'
Expect: Registry key does not exist: `HKEY_LOCAL_MACHINE\SOFTWARE\Deskflow`

fix: Delete `HKEY_LOCAL_MACHINE\SOFTWARE\Deskflow` when clearing settings

---

cmake/Libraries.cmake
src/apps/deskflow-client/deskflow-client.cpp
src/apps/deskflow-daemon/deskflow-daemon.cpp
src/apps/deskflow-server/deskflow-server.cpp
src/lib/arch/win32/ArchMiscWindows.cpp
src/lib/arch/win32/ArchMiscWindows.h

Fixes: #8311
PR shows an error dialog and exits the program (server, client, and daemon) if the MSVC++ runtime is too old. This avoids silent crashes which are very confusing and waste a lot of time. Windows doesn't tell you when a binary was linked against an older library, it just loads whatever DLL it finds and hopes for the best.
Wrong version:
Missing runtime (default Windows message):

fix: Guard MSVC runtime version depending on compiler version

---

README.md

Time machine's broken.
Before:
After:

docs: Make Windows MSVC redist requirement stand out

---

src/apps/deskflow-gui/MainWindow.cpp

fixes #8310
Restore the icon mask for our tray icon. 
tldr it was in the wrong order you must mask before applying to the tray

fix: mac os icon mask

---

.github/actions/lint-check/action.yml
src/apps/deskflow-gui/MainWindow.cpp
src/apps/deskflow-gui/dialogs/FingerprintDialog.cpp
src/apps/deskflow-gui/main.cpp
src/lib/arch/win32/XArchWindows.cpp
src/lib/deskflow/win32/AppUtilWindows.cpp
src/lib/gui/config/ConfigScopes.h
src/lib/gui/messages.cpp
src/lib/gui/styles.h
src/lib/gui/tls/TlsUtility.cpp
src/lib/gui/validators/ScreenNameValidator.cpp
src/lib/platform/MSWindowsClipboardHTMLConverter.cpp
src/test/unittests/deskflow/KeyStateTests.cpp
src/test/unittests/gui/core/ClientConnectionTests.cpp

Looks like a new version of clang has come out and its some how changed our linting.. (-1 for linting yet again ...)
This pr: 
- updated files based on clang 20.1.0 rules
- Pins the lint-action to use clang-format 20.1.0 
Related: https://github.com/deskflow/scripts/pull/2
Set to automerge on accept

chore: update formating for clang-format 20.1.0

---

src/lib/common/common.h
src/lib/common/constants.h.in
src/lib/deskflow/win32/AppUtilWindows.cpp
src/lib/net/SecureSocket.cpp
src/lib/platform/EiEventQueueBuffer.cpp
src/lib/platform/EiScreen.cpp
src/lib/platform/MSWindowsHandle.h
src/lib/platform/MSWindowsKeyState.cpp
src/lib/platform/MSWindowsKeyState.h
src/lib/platform/MSWindowsProcess.cpp
src/lib/platform/MSWindowsWatchdog.cpp
src/lib/platform/MSWindowsWatchdog.h
src/lib/platform/OSXEventQueueBuffer.cpp

Fixes: #8245
Blocks:
- #8300
Blocked by:
- #8340
- #8339
Moving the SAS event wait and SendSAS call prevents blocking the main thread allowing for more responsive watchdog (e.g. faster restart Core client/server on session switch).

Make Windows watchdog more responsive with new SAS thread

---

src/apps/deskflow-gui/MainWindow.cpp

fix the jank resize for logs on windows / gnome / mac os (sometimes) .
fixes https://github.com/deskflow/deskflow/issues/8217
fixes https://github.com/deskflow/deskflow/issues/8081
Tested on windows and works perfect now.

fix: log Resize update the timer to 15ms

---

src/apps/deskflow-gui/MainWindow.cpp
src/apps/deskflow-gui/MainWindow.h
src/apps/deskflow-gui/MainWindow.ui

-  Remove from the main window the "save Configuration as" menu item and replace it with a button that is only shown when in server mode. 
- Add "configure" icon to the "Configure Server" button

refactor: mainwindow move save config to a button

---

src/lib/arch/win32/ArchFileWindows.cpp

fixes #8371
on windows the old arch method was appending `\\Deskflow` to our paths. (only on windows)

fix: windows looking in deskflow/deskflow for items

---

src/lib/common/Settings.h

Fixes typos in settings keys cases
-  `checkpeerfingerprints` => `checkPeerFingerprints`
- `invertscrolldirection` => `invertScrollDirection`
- `remotehost` => `remoteHost`
Draft: Ah, spotted 2 more:
- ~`checkpeerfingerprints`~ (Added by sithlord48)
- ~`invertscolldirection`~ (Added by sithlord48)

fix: Use correct casing for `RemoteHost` value in Settings.h

---

deploy/linux/flatpak/org.deskflow.deskflow.yml

- Sync our local flatpak to the same depends used in the flathub recipe
-  `libei 1.3.0` => `libei 1.4.0`
-  `libportal 0.8.1` => `libportal 0.9.1`

ci: Sync local flatpak depends to those on flathub

---

src/apps/deskflow-gui/MainWindow.cpp
src/apps/deskflow-gui/MainWindow.ui

- Give the menus in createMenu() parents, this prevents a tiny leak (according to valgrind)
- Use `setMaximumSize`  in place of calls to `setMaximumWidth` and `setMaximumHeight` in updateSize
- Remove from the UI an empty unused layout

fix a few items in the mainwindow

---

src/lib/arch/Arch.cpp
src/lib/arch/win32/ArchMiscWindows.cpp
src/lib/arch/win32/ArchMiscWindows.h
src/lib/platform/MSWindowsScreen.cpp

Remove a bunch of unused methods from `ArchMiscWindows`
- remove unused `ArchMiscWindows::hasValue`
- remove unused `ArchMiscWindows::setIcons`
- remove unused `ArchMiscWindows::getIcons`
- remove unused `ArchMiscWindows::deleteValue`
- remove unused `ArchMiscWindows::deleteKeyTree`
- remove unused `ArchMiscWindows::setValueBinary`
- remove unused `ArchMiscWindows::readValueBinary`
- remove unused `ArchMiscWindows::addDialog`
- remove unused `ArchMiscWindows::removeDialog`
- remove unused `ArchMiscWindows::s_dialog`
- remove unused `ArchMiscWindows::cleanup`
- remove unused `ArchMiscWindows::processDialog`

Remove unused items in ArchMiscWindows

---

src/apps/deskflow-gui/VersionChecker.cpp

- Shows warning when empty response back from update server. 
- Improved logging for when new version available/not available.

feat: Handle empty update response and improve logging

---

src/lib/base/Event.h
src/lib/base/EventQueue.cpp
src/lib/base/EventQueue.h
src/lib/base/EventTypes.cpp
src/lib/base/FinalAction.h
src/lib/base/Log.h
src/lib/base/LogOutputters.cpp
src/lib/base/LogOutputters.h
src/lib/base/PriorityQueue.h
src/lib/base/String.cpp
src/lib/base/String.h
src/lib/base/Unicode.cpp
src/lib/base/XBase.cpp
src/lib/platform/MSWindowsScreen.h

Remove unneeded includes in `lib/base`
- remove unused includes in `lib/base/Event`
- remove unused includes in `lib/base/EventQueue`
- remove unused includes in `lib/base/EventTypes`
- remove unused includes in `lib/base/FinalAction`
- remove unused includes in `lib/base/Log`
- remove unused includes in `lib/base/LogOutputters`
- remove unused includes in `lib/base/PriorityQueue`
- remove unused includes in `lib/base/Unicode`
- remove unused includes in `lib/base/String`
- remove unused includes in `lib/base/XBase`

Clean unneeded includes in lib/base

---

cmake/Libraries.cmake
src/lib/Config.h.in

Remove unused defines from `Config.in.h` / `Libaraies.cmake`
- remove unused define `HAVE_ISTREAM`
- remove unused define `HAVE_OSTREAM`
- remove unused define `HAVE_SSTREAM`
- remove unused define `HAVE_LOCALE_H`
- remove unused define `HAVE_SYS_UTSNAME_H`
- remove unused define `HAVE_WCHAR_H`
- remove unused define `HAVE_GETPWUID_R`
- remove unused define `HAVE_GMTTIME_R`

remove more unused defines

---

src/lib/gui/tls/TlsCertificate.cpp

- `tls/local-fingerprints` path was not correct fixed that to generate the file correctly

fix: local-fingerprint generation

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

- Modify the bug and feature templates to not add labels but instead add the Type
- `Triage [feature]` <= for newly proposed features 
- `Triage [bug]` <= for newly reported bugs
This will allow us to remove the bugs, triage and unanswered, feature request and enhancement and simplify these into a few groups based on their type and status. Also make labels more useful as they will be less clutter 
Workflow for bugs, A new bug is reported, We test etc 
- Confirmed, have their type changed to `Bug` and at this time we apply any labels we may want.
- Rejected, are closed.
Workflow for features, A new feature is proposed
- Accepted Features, have their type changed to `Feature` and at this time we apply any labels we may want.
- Rejected Features, are closed.
I have changed the last few …

chore: use Type for templates

---

deploy/windows/wix-patch.xml.in
doc/configuration.md
src/lib/common/Settings.cpp
src/lib/common/Settings.h
src/lib/gui/dialogs/SettingsDialog.cpp

Cleanup Settings:
- Remove unused private `Settings::isPortableSettings`
- Remove unused signal `Settings::scopeChanged`
- Remove unused signal `Settings::writableChanged`
- Add `Settings::validKeys` method to get the list of valid keys
- Use the same logic for the settings file on all platforms
- Change the default for the daemon log file on windows to the path of the daemon
- Update the configuration.md file include a section on the gui config
- Use `XDG_CONFIG_DIR` if set.
- Fix: mixmatch set / read for `UpdateCheck`
Fix Settings Issues:
- fixes: #8418 
- fixes: #8409 
- fixes: #8421 
Wix Installer Changes:
- Run deskflow when the finish button is clicked
- Run deskflow as a normal user post install
Tested on a Win11 CleanVm to make sure setting worked and daemon was picked up after …

Fix: settings releated issues, prepare it for testing

---

doc/configuration.md
src/lib/common/QSettingsProxy.cpp
src/lib/common/Settings.cpp
src/lib/common/Settings.h
src/lib/gui/Diagnostic.cpp
src/lib/gui/dialogs/SettingsDialog.cpp
src/lib/gui/dialogs/SettingsDialog.ui

fixes: #8429 
fixes: #8432 
fixes: #8434
- On windows use the registry to save the items normally in `Deskflow.conf`
- On windows use the registry unless the portableSettings file `[install-dir]/settings/Deskflow.conf` if found
- On Windows Use either `ProgramData\Deskflow`  to save tls and other non "settings" when registry is in use
- On Windows Use either `[installdir]/settings`  to save tls and other non "settings" when registry is not in use
- Set the default process Type based on the kind of settings loaded
-  `InI Format` (unix / mac / windows portable) the mode defaults to `Desktop`
-  `Native Format` settings (only windows installed mode) we default to `Service`
- Set the default elevation mode based on type also 
-  `InI Format` (unix / mac / windows portable) the mode defaults …

refactor: settings for windows 

---

deploy/windows/cpack-options.cmake.in
deploy/windows/deploy.cmake
deploy/windows/pre-cpack.cmake.in

- fixes: #6378 
- new artifact name is `deskflow-version-w64-portable.7z`
- portable version does not ship the `daemon`
- portable should be portable on most windows 10 / 11

Portable windows build

---

.github/workflows/continuous-integration.yml
src/lib/gui/KeySequence.cpp
src/lib/gui/KeySequence.h

- requires: #8453 
- fixes: #8448 
- bump windows and mac os ci to use Qt 6.9

fix: build issue on Qt 6.9

---

CMakeLists.txt
src/apps/CMakeLists.txt
src/apps/deskflow-gui/CMakeLists.txt
src/apps/deskflow-gui/deskflow-gui.cpp
src/apps/deskflow-gui/deskflow.man.template.in

- Requires #8440 
- Change app description from `Mouse and keyboard sharing utility` => `Keyboard and mouse sharing utility` 
Clean up some unused item in `deskflow-gui.cpp`
- Remove unused headers
- Remove unused `QThreadImpl` class
- Remove workaround for [Qt-40332](https://bugreports.qt.io/browse/QTBUG-40332)
- Remove fallback for pre mavericks accessibility dialog
Add Cli options 
- Removes the need for the template man page for deskflow's gui
- move `--no-reset` to the QCommandLineProcessor 
- add `--help`
```
Deskflow: 1.21.1.18 (f41b6a45)
Keyboard and mouse sharing utility
Usage: deskflow [options]
Options:
--help      Display Help on the command line
--version   Display version information
--no-reset  Prevent settings reset if DESKFLOW_RESET_ALL is set
```
- add `--version` 
``` …
```

feat: add help and version to gui,

---

src/lib/common/Settings.cpp
src/lib/common/Settings.h
src/lib/gui/core/CoreProcess.cpp
src/lib/gui/dialogs/SettingsDialog.cpp
src/lib/gui/dialogs/SettingsDialog.ui
src/lib/gui/ipc/DaemonIpcClient.cpp
src/lib/gui/ipc/DaemonIpcClient.h

fixes: #8350 
- Removes `Settings::Core::ElevateMode` and sets `Daemon::Elevate` Instead (default: true)
- New Settings: `Settings::Core::StopOnDeskSwitch` (default: false) 
You can only select one of the option

Settings service update

---

src/lib/platform/EiScreen.cpp

- libei added some new Types we do not handle to avoid warnings about this a default case has been added to handling

chore: add default case for EI_EVENT handling

---

.github/workflows/continuous-integration.yml

- osx 13 build fail randomly to find pthread, force this build to use the xcode15 sdk path in place of the 15.2 default

ci: force osxSysroot for osx13 builds

---

src/lib/gui/MainWindow.cpp

The server start success message was always showing whether or not the core start worked.

fix: Show first server start message only when start was successful

---

src/lib/common/Settings.h

When we moved the settings we assumed C we need to use QDir::rootPath in the case of windows not being installed on the "C" drive.

fixes #8463 do not assume C for root

---

src/lib/common/Settings.cpp

add -server to the defaut server external config fiile. 
fixes #8485

fix: Default external server config name should be *-server.conf

---

.github/actions/install-dependencies/action.yml
.github/actions/install-dependencies/aqt.ini

Qt default base (`download.qt.io`) has been flakey over the last few days:
- https://github.com/jurplel/install-qt-action/issues/285
- https://github.com/jurplel/install-qt-action/issues/283#issuecomment-2807825345
```
ERROR   : Failed to download checksum for the file '6.9.0-0-202503301022d3dcompiler_47-x64.7z' from mirrors '['https://download.qt.io/']
```
On my local machine:
```
curl https://download.qt.io/                                                              
curl: (7) Failed to connect to download.qt.io port 443 after 43 ms: Could not connect to server
```
We should try a mirror.
Edit: I tried setting `--base` but it turns out that `aqt` ignores that for checksums. The only way to get `aqt` to use checksums from the mirror seems to be to write a `.ini` file and pass it via …

Change Qt mirror (`download.qt.io` is down/flakey)

---

src/lib/gui/MainWindow.cpp
src/lib/gui/MainWindow.h

fixes #8478 
- Disable the actions and buttons used to enable the service in client mode without a remote host address.
- Do not auto start the client app if there is no remote host set.

fix: user can not start in client mode without a remote host

---

.github/workflows/continuous-integration.yml

The fork we use for the action is being absorbed back into the main project. This switches us back to the main action.
see: https://github.com/flathub-infra/flatpak-github-actions/issues/17 for more details

ci: Adjust back to main flatpak builder

---

.github/workflows/continuous-integration.yml

- mac os 14 failed a few times missing libpthread to prevent this set the OSX-Sysroot like we do on macos-13
- remove unused arch variable from the macos-14 ci job

ci: add osxSysroot to mac os14 job

---

src/lib/gui/MainWindow.cpp

requires: https://github.com/deskflow/deskflow/pull/8519
fixes #8517
the previous logic would only save if the setting was already not empty, when we want to only save if the lineHostname is not empty

Save the host name if the lineEdit is not empty

---

src/apps/deskflow-server/deskflow-server.cpp
src/lib/common/Settings.cpp
src/lib/common/Settings.h
src/lib/deskflow/ArgParser.cpp
src/lib/deskflow/ArgsBase.h
src/lib/deskflow/ClientApp.cpp
src/lib/deskflow/ServerApp.cpp
src/lib/gui/core/CoreProcess.cpp
src/lib/gui/dialogs/SettingsDialog.cpp
src/lib/gui/dialogs/SettingsDialog.ui
src/lib/platform/MSWindowsDesks.cpp
src/lib/platform/MSWindowsDesks.h
src/lib/platform/MSWindowsScreen.cpp
src/lib/platform/MSWindowsScreen.h
src/lib/platform/MSWindowsWatchdog.cpp
src/lib/platform/MSWindowsWatchdog.h

requires: https://github.com/deskflow/deskflow/pull/8519
fixes #8458
A Start to removing the switch on desk option.
Done:
- Remove from settings
- Remove from Args
- Remove from MSWindowsScreen 
- Remove from MSWindowsWatchdog

Rm switchon desk

---

src/lib/gui/MainWindow.cpp

fixes #8522
#8522 was caused by it shown being connected to firstShown so we could : 
1. Add more code that calls disconnect in firstShown
2. Skip the connection and call firstShown once from the constructor
3. Remove firstShown and just do the stuff in the constructor
I picked option 1, since 2 and 3 resulted in a new dialog being under the mainwindow

fix: firstshown called on every re open

---

src/lib/gui/tls/TlsCertificate.cpp
src/lib/gui/tls/TlsCertificate.h

- remove unused `TLSCertificate::getCertificatePath()`
Any new code should use `Settings::tlsLocalDb()` for this path.

chore: remove unused TLSCertificate::getCertificatePath

---

REUSE.toml

- reuse lint is upset we landed a non reuse compliant md file 
- rather then have ever md file trigger a rebuild we will auto assign `**/*.md` to MIT this is inline with our ci filter to not run on those files.

fix: add reuse info to **.md by default

---

src/apps/deskflow-client/deskflow-client.cpp
src/apps/deskflow-core/deskflow-core.cpp
src/apps/deskflow-server/deskflow-server.cpp

fixes #8534
`deskflow-server`, `deskflow-core` and `deskflow-client` are not QApplications this causes the qApp used in our settings object to fallback to the default path and make the settings read from different paths (if not using the default one) 
To Fix this on windows only we make a QCoreApplication in each of them and delete it after , this is enough to initialize the qApp.
We should consider in the future making these apps use a QCoreApplication in place of the `App`

ensure client, server and core use correct setting path

---

src/lib/deskflow/ServerApp.cpp
src/lib/deskflow/ServerApp.h

Related to #8525 
When looking at the above i noticed the server configuration paths are completely wrong and the fallback is also wrong . It is safest to have the user provide them in the command like we do when running from the GUI / Daemon. 
- No longer use a fallback for the server config
- Adjust the help message
- Remove redundant command
- Update log level when config can't be loaded to `LOG_ERR`
- Correct the include for `common/Settings.h` => `common/QSettingsProxy.h`
- Remove unused `CONFIG_NAME` variable

fix: incorrect paths for the server configs shown in help message

---

.github/actions/install-dependencies/action.yml

ci: use normal built in vcpkg cache

---

src/lib/deskflow/App.cpp
src/lib/deskflow/ClientApp.cpp
src/lib/deskflow/ServerApp.cpp
src/lib/platform/OSXScreen.h
src/lib/platform/OSXScreen.mm

- Remove unnecessary  checks for the mac os version  both 10.7 and 10.9 are below our current  required version .  
- Replace the needed checks with `#if WINAPI_CARBON`
Testing:

refactor: remove old mac os version checks 

---

src/lib/deskflow/ipc/DaemonIpcServer.cpp
src/lib/gui/MainWindow.cpp
src/lib/gui/MainWindow.h
src/lib/gui/core/CoreProcess.cpp
src/lib/gui/core/CoreProcess.h
src/lib/gui/ipc/DaemonIpcClient.cpp
src/lib/gui/ipc/DaemonIpcClient.h
src/lib/platform/MSWindowsWatchdog.cpp

Retry mechanism for Windows Daemon IPC client

---

src/lib/base/String.cpp

Both trigger:
warning: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
In the first hunk we already checked for i < 0 so casting to size_t is fine. In the second hunk we don't use i so we can pick the right type.

chore: Silence two compiler signedness warnings

---

src/lib/platform/EiEventQueueBuffer.cpp

If we're starved for resources, we may end up with more than 64 notifications in our pipe before we get to actually read them. Those notifications are just that though, so let's drain them.
Seen in https://github.com/deskflow/deskflow/pull/8503#issuecomment-2841702394

ei: Drain all events sitting in our pipe

---

src/lib/platform/EiScreen.cpp

It can happen that the libeis implementation (read: the wayland compositor) sends a `start_emulating` event to a device already emulating. This is a protocol violation of libei/libeis. The client<-->server connection is severed (which is correct behavior), but deskflow never releases the captured xdg-desktop-portal-input-capture. Thus, the cursor remains perpetually stuck. The fix is to release the portal-input-capture when deskflow handles the `EI_EVENT_DISCONNECT` event.
The bug causes the mouse cursor to become stuck at the edge of the server screen (most often the top, but sometimes the sides) when using Deskflow on Wayland. When this happens, all mouse and keyboard input on the server is frozen, and the only way to recover is to SSH in and kill the deskflow-server process. …

Fix: Cursor stuck off server screen (Wayland, attempt)

---

src/apps/deskflow-gui/deskflow-gui.cpp
src/lib/gui/Diagnostic.cpp

Remove the use of the environmental variable `DESKFLOW_RESET_ALL` and reset instead when --reset is passed as an option.

Deskflow-gui add `reset` option

---

src/lib/platform/OSXClipboard.h
src/lib/platform/OSXClipboardAnyBitmapConverter.cpp
src/lib/platform/OSXClipboardAnyBitmapConverter.h
src/lib/platform/OSXClipboardAnyTextConverter.cpp
src/lib/platform/OSXClipboardAnyTextConverter.h
src/lib/platform/OSXClipboardBMPConverter.cpp
src/lib/platform/OSXClipboardBMPConverter.h
src/lib/platform/OSXClipboardHTMLConverter.cpp
src/lib/platform/OSXClipboardHTMLConverter.h
src/lib/platform/OSXClipboardTextConverter.cpp
src/lib/platform/OSXClipboardTextConverter.h
src/lib/platform/OSXClipboardUTF16Converter.cpp
src/lib/platform/OSXClipboardUTF16Converter.h
src/lib/platform/OSXClipboardUTF8Converter.h
src/lib/platform/OSXEventQueueBuffer.cpp
src/lib/platform/OSXEventQueueBuffer.h
src/lib/platform/OSXKeyState.cpp
src/lib/platform/OSXKeyState.h
src/lib/platform/OSXPowerManager.cpp
src/lib/platform/OSXPowerManager.h
src/lib/platform/OSXScreenSaver.h
src/lib/platform/OSXUchrKeyResource.h

similar to #8564  get `override` and use of default constructors / deconstructors

Tidy up macos code smells missed by sonarscan

---

CMakeLists.txt

When testing locally with win arm64 the detection was incorrect. I have adjusted the check to look for the CI's ENV var then try to use the CMAKE_SYSTEM_PROCESSOR when detecting the cpu type on windows

Better detect windows Arm64 on both CI and local builds

---

src/lib/gui/dialogs/SettingsDialog.cpp
src/lib/gui/dialogs/SettingsDialog.ui

Add spacers to the Settings tabs
fixes #8578

refactor: make sure settings dialog pushes all options to the top

---

src/lib/platform/OSXScreen.mm

Observed on macOS Monterey 12.7.6 with cmake version 4.0.1, Homebrew clang version 20.1.4, Target: x86_64-apple-darwin21.6.0:
```
$ CXX="$(brew --prefix llvm)/bin/clang++" CC="$(brew --prefix llvm)/bin/clang" cmake -S . -B build-clang -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=/usr/local/Homebrew/Library/Homebrew/cmake/trap_fetchcontent_provider.cmake -Wno-dev -DBUILD_TESTING=OFF -DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -DBUILD_TESTS:BOOL=OFF -DCMAKE_INSTALL_DO_STRIP=1 -DSYSTEM_PUGIXML:BOOL=ON
...
$ CXX="$(brew --prefix llvm)/bin/clang++" CC="$(brew --prefix llvm)/bin/clang" cmake --build build-clang
...
[ 50%] Building CXX object …
```

Resolve `deprecated-enum-float-conversion` compiler warnings

---

src/lib/common/Constants.h.in
src/lib/gui/MainWindow.cpp
src/lib/gui/dialogs/FingerprintDialog.cpp
src/lib/gui/dialogs/FingerprintDialog.h
src/lib/gui/tls/TlsCertificate.cpp
src/lib/gui/widgets/FingerprintPreview.cpp
src/lib/gui/widgets/FingerprintPreview.h
src/lib/net/FingerprintDatabase.cpp
src/lib/net/FingerprintDatabase.h
src/lib/net/SecureSocket.cpp

Remove most support for SHA1
No Longer:
- Write SHA1 hash to localDB
- Send a SHA1 when sending peer fingerprints.
- Preview SHA1 in the Fingerprint preview
We still support SHA1 As a valid digest type in fingerprint. We can recognize them but don't use them anymore.

Do not use SHA1

---

src/lib/gui/config/Screen.cpp
src/lib/gui/config/Screen.h
src/lib/gui/dialogs/ScreenSettingsDialog.cpp

fixes: #8587
My mistake there was a small error i missed at review time in https://github.com/deskflow/deskflow/pull/8580 that initialized our modifiers to 0.
This fixes that initialization moves them to the header and removes the now no needed init() method

fix settings modifiers initilization, move initization to header

---

src/lib/gui/dialogs/SettingsDialog.cpp

fix: Disable the save button when config not writable

---

src/lib/gui/MainWindow.cpp

Fix a possible crash if the first server run dialog is up when a new client and the fingerprint is dealt with and screen added the app would freeze w/ the first server run dialog showing.. (this allows you to close it)
shown in https://github.com/deskflow/deskflow/issues/8599
1. Have working config (server with clients connected)
1. Clear settings (on the server only let the client continue to connect)
1. Start server (do not touch the first time server message box)
1. See 'Server is running' and fingerprint dialogs at the same time (fingerprint dialog appears in front and no freeze)
1. Accept the fingerprints and add the screen to the server config (you must fully connect the client, accept it etc)
1. If the new server dialog is open still the app will freeze.

fix: lockup if first run message is up and a client connects

---

.github/actions/install-dependencies/action.yml

Simplifies the install dependencies action a bit:
- remove the ninja install action as ninja is part of the runners now
- remove cmake / ninja install from mac os runs as they are part of the runner for mac os also 
- Do do the `Install Depends` step on windows its was empty anyway

ci: Simplify our `Install Dependencies` action

---

src/lib/platform/XWindowsUtil.cpp

Why was this guarded ? 
related #3259  to the latest comments ?

Remove Ifdef around iso_level5

---

src/lib/gui/MainWindow.cpp

If for some reason writing to the fingerprint database fails we log a message and also stop the core process so the user can address the problem related to #8598 Should at least stop a loop in the case of an un-writable db file.

Log Error and stop the core process if print database is not writable

---

.github/actions/install-dependencies/action.yml
deploy/linux/arch/PKGBUILD.in

Add `qt6-svg` to our dependencies on Arch Linux.
Fixes #8626

build: add qt6-svg to arch package depends

---

src/apps/CMakeLists.txt

Avoid leaking build paths in manpages by not passing the full build path of deskflow binaries to help2man.
FIx #8525

fix: avoid leaking build paths in manpages

---

src/lib/gui/dialogs/ServerConfigDialog.cpp
src/lib/gui/dialogs/ServerConfigDialog.ui

Fix an locked controls in ServerConfigDialog when the parent control is enabled 
The following were disabled when the controlling option was enabled on the dialog being opened
- sbHeartbeat
- sbSwitchDelay
- sbSwitchDoubleTap
- External Config Controls (also disable other tabs if enabled)

fix: ServerConfigDialog disabled spinboxes that should be enabled on open

---

src/lib/gui/MainWindow.cpp
src/lib/gui/MainWindow.ui

On mac os the save server config buttons is much taller then the other buttons, this fixes that 
- Convert btnSaveConfig to QPushbutton
- Set the icon size to 22x22 only when not on mac os
- On mac os make sure the button is square
- Remove the unneeded text from the button 
Before: (macOS)
After: (macOS)

Mac os make sure server save and config are the same height

---

deploy/linux/org.deskflow.deskflow.metainfo.xml

The Appstream file incorrectly says the project is `gpl2.0+`. the project is `gpl2.0`

chore: correct appstream license to gpl2.0 NOT gpl2.0+

---

.github/actions/install-dependencies/action.yml
.github/workflows/continuous-integration.yml
src/apps/deskflow-gui/deskflow-gui.cpp
src/lib/gui/MainWindow.cpp
src/lib/gui/StyleUtils.h
src/lib/gui/tls/TlsCertificate.cpp

- windows has random build failues with 6.9.1 so reverted it to 6.8.3
- reverted the vcpkg action to no longer use my fork since johnwason's now is updated.
- A few files ha included QApplication, QGuiApplicaiton or QCoreApplication when it was not needed this removes those includes.

ci: Fix windows random build failures

---

src/lib/gui/ServerConfig.cpp

Noticed two small things when looking at QStrings.
- remove anon namespace before ServerConfig::addToFirstEmptyGrid

Remove anon namespace from Serverconfig::addtoFirstEmptyGrid

---

src/lib/arch/unix/ArchDaemonUnix.cpp
src/lib/platform/Wayland.h
src/lib/platform/XWindowsScreen.cpp

idea from: https://github.com/debauchee/barrier/pull/847/
we are now being sure to use the version from std

chore use std::getenv Not c style getenv

---

src/lib/arch/ArchString.cpp
src/lib/arch/ArchString.h
src/lib/arch/unix/ArchMultithreadPosix.cpp
src/lib/arch/unix/ArchMultithreadPosix.h
src/lib/arch/unix/ArchNetworkBSD.cpp
src/lib/arch/unix/ArchNetworkBSD.h
src/lib/arch/win32/ArchMultithreadWindows.cpp
src/lib/arch/win32/ArchMultithreadWindows.h
src/lib/arch/win32/ArchNetworkWinsock.cpp
src/lib/arch/win32/ArchNetworkWinsock.h
src/lib/base/CMakeLists.txt
src/lib/base/EventQueue.cpp
src/lib/base/EventQueue.h
src/lib/base/Log.cpp
src/lib/base/Log.h
src/lib/deskflow/PacketStreamFilter.cpp
src/lib/deskflow/PacketStreamFilter.h
src/lib/net/TCPListenSocket.cpp
src/lib/net/TCPListenSocket.h
src/lib/platform/XWindowsEventQueueBuffer.cpp
src/lib/platform/XWindowsEventQueueBuffer.h

Begin to replace `ArchMutex` with `std::mutex`. In this first step all cases of `ArchMutex` or `Mutex` that were not part of a conditional var have been replaced. 
Tested locally for a few days didn't see any issues.
Backport from https://github.com/debauchee/barrier/pull/410:
- use `std::mutex` in `arch/unix/ArchMutithreadPosix`
- use `std::mutex` in `arch/ArchStrings`
- use `std::mutex` in `base/Log`
- use `std::mutex` in `base/EventQueue`
Additionally:
- Links arch to base
- use `std::mutex` in `arch/win32/ArchMultiThreadWindows`
- use `std::mutex` in `arch/unix/ArchNetworkBSD`
- use `std::mutex` in `arch/unix/ArchNetworkWinSock`
- use `std::mutex` in `deskflow/PacketStreamFilter`
- use `std::mutex` in `net/TCPListenSocket`
- use `std::mutex` in `platform/XWindowsEventQueue`

Begin to use std::mutex in place of ArchMutex

---

src/lib/gui/MainWindow.cpp
src/lib/gui/MainWindow.h
src/lib/gui/core/ServerConnection.cpp
src/lib/gui/core/ServerConnection.h

fixes: #8688 
Modify the status area to show different message on connections
ServerConnection Changes:
- Added new Q_EMIT to ServerConnection::clientsChanged (QStringList) 
- Replace `QStringList m_receivedClients` => `QSet<QString> m_connectedClients` (set items are unique) 
MainWindows Changes: 
Clients will show
`Deskflow is connected as client of <serverName>`
Servers will show a few things depends on the number of clients
No clients: `Deskflow is waiting for clients`
1 Client: `Deskflow is connected to a client: <clientName>
2-4 Clients: `Deskflow is connected N clients: <clientName1>, <clientName2>, <clientName3>, <clientName4>
5+ Clients: `Deskflow is connected to N clients`
If any more then one client is connected the client list is set to the status bars tooltip in a message …

feat: improve connections status bar info

---

src/lib/arch/ArchString.cpp
src/lib/arch/unix/ArchMultithreadPosix.cpp
src/lib/arch/unix/ArchNetworkBSD.cpp
src/lib/arch/win32/ArchDaemonWindows.cpp
src/lib/arch/win32/ArchMultithreadWindows.cpp
src/lib/arch/win32/ArchNetworkWinsock.cpp
src/lib/base/EventQueue.cpp
src/lib/base/Log.cpp
src/lib/base/Stopwatch.cpp
src/lib/deskflow/App.cpp
src/lib/deskflow/PacketStreamFilter.cpp
src/lib/deskflow/win32/AppUtilWindows.cpp
src/lib/net/SecureSocket.cpp
src/lib/net/TCPListenSocket.cpp
src/lib/platform/EiEventQueueBuffer.cpp
src/lib/platform/EiScreen.cpp
src/lib/platform/MSWindowsScreen.cpp
src/lib/platform/MSWindowsScreenSaver.cpp
src/lib/platform/MSWindowsWatchdog.cpp
src/lib/platform/OSXEventQueueBuffer.cpp
src/lib/platform/OSXKeyState.cpp
src/lib/platform/OSXScreen.mm
src/lib/platform/XWindowsClipboard.cpp
src/lib/platform/XWindowsEventQueueBuffer.cpp
src/lib/platform/XWindowsScreen.cpp
src/unittests/platform/OSXKeyStateTests.cpp

- Use `std::scoped_lock` in place of `std::lock_guard` 
- use Arch::time in place of ARCH->time()
- use Arch::sleep() in place of ARCH->sleep()

Minor smell cleanup

---

src/apps/deskflow-gui/deskflow-gui.cpp

Related to: #8685
We should print the parser error text to stderr and return non-zero exit code so that it's clear when you enter an invalid option.
As it is, it's a bit confusing how it doesn't tell you when you enter an invalid arg.

fix: Error text is not shown for Qt CLI parser

---

src/lib/platform/EiEventQueueBuffer.cpp
src/lib/platform/EiEventQueueBuffer.h
src/lib/platform/EiKeyState.cpp
src/lib/platform/EiKeyState.h
src/lib/platform/EiScreen.cpp
src/lib/platform/EiScreen.h
src/lib/platform/PortalInputCapture.cpp
src/lib/platform/PortalInputCapture.h
src/lib/platform/PortalRemoteDesktop.cpp
src/lib/platform/PortalRemoteDesktop.h

Fixes #8700 
- Conform `EIScreen` `PortalRemoteDesktop` `PortalInputCapture` and `EiKeyState` and `EiEventQueueBuffer` to our code standards 
- Fixed a few sonar issues afterwards.

Conform the remaining EI and Portal item to our code style

---

src/apps/deskflow-gui/deskflow-gui.cpp
src/lib/gui/MainWindow.cpp
src/lib/gui/StyleUtils.h

Simplify how we resolve the fallback search paths. 
1. We do not need to to search any themes child dirs. `StyleUtil::checkSubDir` is not needed  and has been removed
2. Set our fallback search to always include the icon theme path `:icons/deskflow-light` or `:/icons/deskflow-dark` `StyleUtil::SetFallbackThemePath` has been removed and just is set in deskflow-gui.cpp 
3. Remove the Theme settings in MainWindow and do it deskflow-gui

chore: simplify icon theme path fallback path

---

src/lib/base/CMakeLists.txt
src/lib/base/DirectionTypes.h
src/lib/deskflow/IPlatformScreen.h
src/lib/deskflow/IPrimaryScreen.h
src/lib/deskflow/PlatformScreen.h
src/lib/deskflow/ProtocolTypes.h
src/lib/platform/EiScreen.cpp
src/lib/platform/EiScreen.h
src/lib/platform/MSWindowsHook.cpp
src/lib/platform/MSWindowsHook.h
src/lib/platform/MSWindowsScreen.cpp
src/lib/platform/MSWindowsScreen.h
src/lib/platform/OSXScreen.h
src/lib/platform/OSXScreen.mm
src/lib/platform/PortalInputCapture.cpp
src/lib/platform/PortalInputCapture.h
src/lib/platform/XWindowsScreen.cpp
src/lib/platform/XWindowsScreen.h

fixes #8572 
fixes #8452 
fixes #8605 
any remaining cases of #8005 
Maybe more as well as those cases where the mouse could just vanish when it touched an edge (at least for wayland) 
- Remove un needed `InputCapturePortal::fakeEisFd` method 
- Set only the barriers that have a screen next to them on wayland 
- Move Direction and DirectionMask enums to `base/DirectionTypes.h`
- Add `IPrimaryScreen::activeSides` to return the side mask
- Implement `IPrimaryScreen::refactor` in the subclasses 
- Use activeSide data to set zones used when making the InputCapture portal request

InputCapture portal Improvements

---

.github/actions/install-dependencies/action.yml
src/lib/gui/MainWindow.cpp
src/lib/gui/MainWindow.ui

Use the system's monospace font for the log.
Bump the font size up a bit for macOS to 12px. Its default is way to small.
fixes : maybe some of https://github.com/deskflow/deskflow/issues/7865 , Others?
windows runner was updated to ninja 1.13.1 so reverting the commit to update it with our action

chore: MainWindow, Use system monospace font in log

---

.github/workflows/continuous-integration.yml

downgrade Qt on x64 windows to avoid random build failures with 6.9.1.
The build randomly fails locally for me and on CI when building with Qt 6.9.1 on windows x64 (but not arm..) until this is resolved lets save a bunch of Ci time by landing this and letting the cache get repopulated.

ci: use Qt 6.9.0 for x64 windows

---

deploy/windows/wix-patch.xml.in
src/lib/common/Settings.cpp

Windows Only: 
- write the daemon log to `C:\ProgramData\Deskflow`
- on update / install remove old log `C:\ProgramFiles\Deskflow\deskflow-daemon.log` (makes sure if updating then uninstalling later on the install dir is removed correctly)

refactor: windows write daemon log in ProgramData\Deskflow

---

CMakeLists.txt

Fixes a Cmake typo preventing non git build from getting the right version (sometimes not even configuring) 
Extends : #6197

build: fix cmake error with git version if no tags / git repo

---

src/lib/base/Event.h
src/lib/base/PriorityQueue.h
src/lib/deskflow/KeyMap.cpp
src/lib/deskflow/KeyMap.h
src/lib/deskflow/KeyState.cpp
src/lib/gui/dialogs/ActionDialog.cpp
src/lib/gui/dialogs/ActionDialog.h
src/lib/platform/EiKeyState.cpp
src/lib/platform/MSWindowsKeyState.cpp
src/lib/platform/OSXKeyState.cpp
src/lib/platform/PortalInputCapture.cpp
src/lib/platform/PortalRemoteDesktop.cpp
src/lib/platform/XWindowsKeyState.cpp
src/unittests/legacytests/legacytests/deskflow/KeyStateTests.cpp

Fix more sonar issues 
- Refactor: ActionDialog to use proper method in place of lambda
- PriorityQueue: use std::ranges version of heap methods 
- KeyMap::mapCommandKey and keysToRestoreModifier use ranged loops
- More Enum Classes
- KeyMap's `EType` => `KeyMap::KeyType`
- Explicit constructor for `Event's` not default constructors.

Sonar cleanup 9

---

src/lib/base/Log.cpp
src/lib/client/ServerProxy.cpp
src/lib/client/ServerProxy.h
src/lib/deskflow/IKeyState.cpp
src/lib/deskflow/unix/X11LayoutsParser.cpp
src/lib/gui/ScreenSetupModel.cpp
src/lib/gui/dialogs/ServerConfigDialog.cpp
src/lib/mt/Thread.cpp
src/lib/mt/Thread.h
src/lib/net/Fingerprint.h
src/lib/net/NetworkAddress.cpp
src/lib/net/NetworkAddress.h
src/lib/platform/XWindowsClipboard.cpp
src/lib/platform/XWindowsKeyState.cpp
src/lib/platform/XWindowsScreen.cpp
src/lib/server/Config.cpp
src/lib/server/Config.h
src/lib/server/InputFilter.cpp
src/lib/server/InputFilter.h

Next batch of sonar cleanup contains
- Log: Replace use of `snprintf` with `std::format_to_n` (for non macOS builds)
- Use `std::ranges` version of methods in most places where a container is used
- XWindowsClipboard: Replace uses of `snprintf` with `std::format_to_n`
- Remove redundant `private` section in Fingerprint Struct
- Declare Variables on separate lines (XWindowsScreen)
- Remove redundant `!=` operator. In c++20 as long as a class has the `==` operator  a `!=` operator of `!(a==b)` will be generated.

Sonar Cleanup 11

---

src/lib/server/Server.h

It is likely random whether the server works or not without a manually configured protocol option, which is neither documented nor enforced to be set.
With a random uninitialized value in m_protocol, this can happen: 
[2025-08-03T12:39:57] NOTE: accepted client connection
[2025-08-03T12:39:57] FATAL: a runtime error occurred: XInvalidProtocol
Reports of "it works with debug enabled" are likely due to having parts of the memory space the server object is allocated into being cleared, and thus having a 0 (Synergy) startup value.

fix: server: initialize the m_protocol member with a default value

---

src/lib/base/FunctionEventJob.h
src/lib/base/FunctionJob.h
src/lib/base/Stopwatch.cpp
src/lib/base/Stopwatch.h
src/lib/deskflow/App.cpp
src/lib/deskflow/App.h
src/lib/deskflow/ClientApp.cpp
src/lib/deskflow/ClientApp.h
src/lib/deskflow/PlatformScreen.h
src/lib/deskflow/ServerApp.cpp
src/lib/deskflow/ServerApp.h
src/lib/gui/FileTail.h
src/lib/gui/ServerConfig.h
src/lib/gui/dialogs/AddClientDialog.h
src/lib/gui/dialogs/ScreenSettingsDialog.h
src/lib/gui/widgets/KeySequenceWidget.h
src/lib/net/NetworkAddress.h
src/lib/net/SecureListenSocket.cpp
src/lib/net/SecureSocket.cpp
src/lib/net/TCPListenSocket.h
src/lib/net/TCPSocket.h
src/lib/server/Config.h
src/lib/server/InputFilter.h

Next round of sonar "issues"  cleanup 
- Add `explicit` for a bunch of constructiors
- Remove unused `StopWatch::double()`
- Make `App::m_events` private, access it from existing `App::getEvents()` in the sub classes
- Make `TCPListenSocket` protected var's private and access via protected methods in subclasses
- Make `TCPSocket::m_events` private access it from getEvents() in sub classes.
- Note Attempting to make `TcpSocket::outputBuffer` / `TcpSocket::inputBuffer` private with protected member access did build but resulted in failure to connect.  
- Unify `ClientApp::handleScreenError` and `ServerApp::handleScreenError` into `App::handleScreenError`
- Make `App::m_bye` protected member
- Remove `do nothing` methods `ClientApp::updateStatus(...)` and `ServerApp::updateStatus(...)` (was …

Sonar cleanup 12

---

src/lib/deskflow/App.h
src/lib/deskflow/ClientApp.cpp
src/lib/deskflow/DisplayInvalidException.h
src/lib/deskflow/IKeyState.cpp
src/lib/deskflow/KeyMap.cpp
src/lib/deskflow/KeyMap.h
src/lib/deskflow/KeyState.cpp
src/lib/deskflow/KeyTypes.cpp
src/lib/deskflow/ServerApp.cpp
src/lib/deskflow/unix/AppUtilUnix.cpp
src/lib/deskflow/unix/AppUtilUnix.h
src/lib/gui/Action.cpp
src/lib/gui/Action.h
src/lib/gui/KeySequence.cpp
src/lib/gui/KeySequence.h
src/lib/gui/ServerConfig.cpp
src/lib/net/Fingerprint.cpp
src/lib/net/Fingerprint.h
src/lib/net/TCPSocket.cpp
src/lib/platform/MSWindowsDesks.cpp
src/lib/server/Config.cpp
src/lib/server/Config.h

Next round of sonar clean up: 
- TCPSocket: init `m_socket` before `m_events`
- ServerConfig: use ranged loops for screens section
- IKeyState: directly send args for string creation to emplace
- IKeyState: Remove use of malloc (+ use auto now for the type) 
- App: make `m_bye` private and access via existing method `bye`
- DisplayInvalidException remove unneeded constructors on non mac os
- MSWindowsDesks::getCursorPos, initialize pos to 0,0
- KeyState::updateModifierState, use `std::ranges::set_difference`
- KeyTypes::KeyModifierNameMapEntry, remove commented code
- AppUtilUnix remove name from unused IEventQueue pointer
- Use default == operator for `KeyMap`, `Action`, `KeySequence`, `Fingerprint`
- server/Config remove redundant != operator

Sonar cleanup 13

---

src/lib/base/DirectionTypes.h
src/lib/deskflow/PlatformScreen.cpp
src/lib/deskflow/PlatformScreen.h
src/lib/platform/EiScreen.cpp
src/lib/platform/MSWindowsScreen.cpp
src/lib/platform/OSXScreen.mm
src/lib/platform/XWindowsScreen.cpp

For the longest time, this log line has bugged me:
```
active sides: e
```
It's hex, but it looks like a bug, since there's no `0x` prefix. Also, most humans can't read hex, so I added a string representation.
New version:
```
[2025-08-06T11:56:00] DEBUG: active sides: LRT (0x0e)
```

chore: Improve logging for active sides

---

src/lib/platform/EiKeyState.cpp

Some modifiers, notably LevelThree, were not accounted for in the modifier mask calculation. This leads to an incorrect keymap where some key symbols were listed for keys without (or insufficient) modifiers. Emulating those keys can then produce the wrong keysyms.
Reproducible with server and client on English(UK) layout and typing e.g. [. That key has its own key AD11 (right of P) but is also on the third level of AE08 (the 8 key). When the server sends the keyid 91 (for [) the client looks it up in the pre-generated keymap. It is found first on the 8 key with no modifiers (because LevelThree was previously ignored), hence the client simulates a key 8 press without modifiers. This erroneously produced an 8 instead of the wanted [.
Fix this by ensuring that all modifiers are accounted for …

fix: Account for more modifiers in the EI keymap calculation

---

src/lib/gui/MainWindow.cpp

Adjust `MainWindow::setHostName`
- Return early if the new name is the same as the old name 
- Only check the server config for an existing screen if we are in server mode.
- If in server mode make sure to call serverConfig()::upateServerName() when the name changes, Failing todo this can break the server layout as the screen config is not updated.

fix: MainWindow::setHostName potental error

---

src/lib/platform/EiEventQueueBuffer.cpp
src/lib/platform/EiEventQueueBuffer.h
src/lib/platform/EiKeyState.cpp
src/lib/platform/EiKeyState.h
src/lib/platform/EiScreen.cpp
src/lib/platform/EiScreen.h
src/lib/platform/PortalInputCapture.h

fixes: #8818
update our variable and methods names to match our naming conventions
Some `snake_case` remains but these are types or methods outside of our code.

Conform EI files to our naming convention

---

src/lib/gui/MainWindow.cpp
src/lib/gui/MainWindow.h
src/lib/gui/MainWindow.ui
src/lib/gui/Styles.h

GUI
- Use `Link Color` for coloring the ip to use 
- Move the gui display to the top right 
- show ONLY the suggested IP on the gui the rest are in a tooltip. no tooltip for a single ip
- Only show the IP when in server mode. 
I don't have a screen shot for the tooltip buts its 
```
If connecting via the hostname fails, Try the following Ips:
SuggestedIP (in color) 
other ip 
other ip
...
```

GUI: Move the shown ip location, only show when in server mode

---

src/lib/gui/MainWindow.cpp
src/lib/gui/MainWindow.h
src/lib/gui/MainWindow.ui

move start and restart inline with mode options
update labels for the mode buttons actions and menu actions 
use callstart / callstop for connect and disconnect icons
Server mode (not started)
client mode (connected)
client mode (DC)

MainWindow Slight gui update

---

src/apps/deskflow-core/deskflow-core.cpp
src/apps/deskflow-daemon/deskflow-daemon.cpp
src/apps/deskflow-gui/deskflow-gui.cpp
src/lib/common/CMakeLists.txt
src/lib/common/Common.h
src/lib/common/ExitCodes.h
src/lib/deskflow/App.cpp
src/lib/deskflow/ClientApp.cpp
src/lib/deskflow/DaemonApp.cpp
src/lib/deskflow/ServerApp.cpp
src/lib/platform/MSWindowsProcess.cpp

fixes: #8258
- Prevents `deskflow-core` from running two instances at the same time
- `deskflow-core --help` will always return the help message
- `deskflow-core --version` will always return the version info
-  Duplicate runs will print `An instance of deskflow core is already running` and exit
- Intercept `--help` and `-h` in `deskflow-core` to call its `showHelp`
- Intercept `--version` and `-v` in `deskflow-core` to call  its `showVersion`
- Move the exit codes to a new `common/ExitCodes.h`
- Use new exit codes for all exits.
- Add new exit code `s_exitDuplicate` to return when exiting because of an instance is already running.

feat: Prevent core, client and or server from running at the same time

---

src/apps/deskflow-core/deskflow-core.cpp
src/apps/deskflow-daemon/deskflow-daemon.cpp
src/apps/res/deskflow.qrc
src/apps/res/icons/deskflow-dark/actions/16/network-connect.svg
src/apps/res/icons/deskflow-dark/actions/16/network-disconnect.svg
src/apps/res/icons/deskflow-dark/actions/22/network-connect.svg
src/apps/res/icons/deskflow-dark/actions/22/network-disconnect.svg
src/apps/res/icons/deskflow-dark/actions/24/network-connect.svg
src/apps/res/icons/deskflow-dark/actions/24/network-disconnect.svg
src/apps/res/icons/deskflow-light/actions/16/network-connect.svg
src/apps/res/icons/deskflow-light/actions/16/network-disconnect.svg
src/apps/res/icons/deskflow-light/actions/22/network-connect.svg
src/apps/res/icons/deskflow-light/actions/22/network-disconnect.svg
src/apps/res/icons/deskflow-light/actions/24/network-connect.svg
src/apps/res/icons/deskflow-light/actions/24/network-disconnect.svg
src/lib/deskflow/DaemonApp.cpp
src/lib/gui/MainWindow.cpp
src/lib/gui/VersionChecker.cpp
src/lib/gui/core/CoreProcess.cpp
src/lib/net/SecureSocket.cpp
src/lib/net/SecureSocket.h
src/lib/platform/XWindowsKeyState.cpp

A couple of unrelated changes i didn't feel like making separate PRS for 
- Where possible use qPrintable in place of `QString::toStdString().c_str()` 
- Include `io/FileSystem.h` in SecureSocket cpp instead of header. 
- Adjust CoreProcess::onProcessFinished , do no restart the core if it stopped because an instance has already started.
- Adjust the message for when the core exits due to a duplicate
- Add fallback icons for the connect / disconnect buttons. 
@nbolton  This changes the daemon a little please take a bit of extra time testing the windows daemon on this branch.

various small fixes

---

src/lib/platform/EiKeyState.cpp

Fixes: #8840
I have no idea why, but removing the [meta key](https://en.wikipedia.org/wiki/Meta_key) mapping fixes the Alt key on my Arch+KDE client.
I do wonder if the [original] meta key is actually used today. It often gets mixed up with the super ("logo") key (which is called meta now by many DE's such as KDE).
My meta/logo/super key works fine with this PR.
CC @wismill @whot

Disable meta mod (fixes alt key bug)

---

src/lib/common/Settings.cpp
src/lib/common/Settings.h
src/lib/gui/Messages.cpp

Closes: #8907 
Will need #8906  to show if you log level is below NOTE
added a checkbox and setting to track this,
please note the checkbox is added by the QMessagebox we don't have control over placement w/o making custom dialogs.

feat: Allow suppression of generic client connection error dialog

---

doc/user/configuration.md
src/lib/gui/Action.cpp
src/lib/gui/Action.h
src/lib/gui/dialogs/ActionDialog.h
src/lib/gui/dialogs/ActionDialog.ui
src/lib/server/Config.cpp
src/lib/server/InputFilter.cpp
src/lib/server/InputFilter.h
src/lib/server/Server.cpp
src/lib/server/Server.h

- Add switchToNextScreen action type and GUI option
- Implement server-side screen cycling logic
- Update configuration parsing for new action
- Fix Action::text() method indexing bug
- Update copyright headers for 2025
This implements GitHub issue https://github.com/deskflow/deskflow/issues/8006 - a hotkey to cycle through
connected computers in the Deskflow network.
Closes https://github.com/deskflow/deskflow/issues/8006

feat: Add switchToNextScreen hotkey to cycle through computers

---

src/lib/gui/dialogs/ServerConfigDialog.cpp
src/lib/gui/dialogs/ServerConfigDialog.h

This should correct the inability to write to the server config

refactor: ScreenConfigDialog, make sure to populate the screen model after server config

---

src/lib/gui/MainWindow.cpp

fix: Prevent log visibility toggle when window is hidden

---

src/lib/deskflow/App.h
src/lib/deskflow/ArgParser.cpp
src/lib/deskflow/ArgsBase.h
src/lib/deskflow/ClientApp.cpp
src/lib/deskflow/ClientApp.h
src/lib/deskflow/IApp.h
src/lib/deskflow/ServerApp.cpp
src/lib/deskflow/ServerApp.h
src/lib/deskflow/unix/AppUtilUnix.cpp
src/lib/deskflow/win32/AppUtilWindows.cpp
src/lib/gui/core/CoreProcess.cpp
src/unittests/deskflow/ArgParserTests.cpp
src/unittests/deskflow/ArgParserTests.h

- Removes the `--daemon` and `--no-daemon / -f `  option. Deskflow will now by default start in foreground like all other unix apps. 
- Remove unused `--service` and `--relaunch` options for windows. 
- Removes `IApp::foregroundStartup`  (as its now unused)
- Rename  `IApp::standardStartup` => `IApp::start`
- Fix Broken Arg Test on arm64 fedora (args must be static removing soon so not too worried) 
Does not remove `Arch->daemonize` this should be looked at to see if we need this in Arch since its  only used on windows with the daemon process now. We should also look to redo  IApp::runInner to not require the startupMethod (both of these are tangled into the daemon on windows)

feat: Remove unused OS based arguments

---

src/lib/arch/win32/ArchNetworkWinsock.cpp
src/lib/net/TCPListenSocket.cpp

Fixes #8978
Apparently, this is common practice on Unix to allow fast process restart and is needed because of `TIME_WAIT` (I didn't test this). It appears this pattern was copied to the Windows implementation, but that is not advisable for Windows sockets since they don't behave the same.

fix: Do not reuse listen sockets on Windows

---

src/lib/base/LogOutputters.cpp
src/lib/base/PriorityQueue.h
src/lib/net/SecureSocket.cpp
src/lib/net/SecureSocket.h
src/lib/platform/EiScreen.h
src/lib/server/ClientProxy1_5.cpp
src/lib/server/ClientProxy1_5.h
src/lib/server/ClientProxy1_7.cpp
src/lib/server/ClientProxy1_7.h
src/lib/server/Config.cpp
src/lib/server/InputFilter.cpp
src/lib/server/InputFilter.h

Various Sonar cleanup  
- remove unused InputFilter::RestartServer::m_events
- remove unused ClientProxy1_7::m_events
- remove unused ClientProxy1_5::m_events
- EiScreen::m_powerManager add no_unique_address
- SecureSocket serviceConnect / serviceAccept make anonymous ISocketMultiplexer *const 
- FileLogOutputter::write use static `QFile::rename`
- PriorityQueue:comp add no_unique_address

Sonar cleanup 18

---

src/lib/gui/dialogs/SettingsDialog.cpp

Set the SettingsDialog debug warning's initial visibility  based on log level.

fix: SettingsDialog, ensure debug warning is shown

---

src/lib/common/Settings.cpp
src/lib/common/Settings.h
src/lib/gui/core/CoreProcess.cpp
src/lib/gui/core/CoreProcess.h

Clean up items not needed after merging deskflow-client and deskflow-server into deskflow-core 
- Remove `Settings::Client::Binary` and `Settings::Server::Binary`, use kCoreBinName in its place
- Clean up `CoreProcess` so it sets m_appPath and uses it in place of local app it passes around between methods
- Remove unused `CoreProcess::extract`

Cleanup the CoreProcess

---

src/lib/base/Log.cpp
src/lib/base/Log.h
src/lib/deskflow/App.cpp

Fixes: #8999
-  mac os does not like the char pointer for `CLOG->setFilter` change it to take a QString instead

Set Filter log with QString

---

src/lib/gui/core/CoreProcess.cpp

fixes: #9003
If deskflow-core has returned non 0 we stop the process instead of retrying.

fix: stop retry if core has crashed
