deskflow/deskflow

- src/lib/platform/OSXScreen.cpp
- src/lib/platform/OSXScreen.h
I'm creating a new PR, since I accidentally merged #4261 (oops).
> Double click breaks dragging and tripple click on Mac

- src/gui/res/ServerConfigDialogBase.ui
- src/gui/src/MainWindow.cpp
- src/gui/src/ServerConfig.cpp
- src/gui/src/ServerConfig.h
- src/gui/src/ServerConfigDialog.cpp
This should address [issue 4327](https://github.com/synergy/synergy/issues/4327).
> Add drag and drop enable option to GUI settings

- src/gui/res/ServerConfigDialogBase.ui
- src/gui/src/MainWindow.cpp
- src/gui/src/ServerConfig.cpp
- src/gui/src/ServerConfig.h
- src/gui/src/ServerConfigDialog.cpp
> Revert "Add drag and drop enable option to GUI settings"

- src/setup/win32/Product.wxs
> Revert "Fix missing DLLs after install #3774"

- src/lib/synergy/ToolApp.cpp
Using account instead of premium in auth URL
> v1.8.2 future-proof GUI login by using newer auth URL

- src/gui/gui.pro
- src/gui/res/SettingsDialogBase.ui
- src/gui/src/AppConfig.cpp
- src/gui/src/AppConfig.h
- src/gui/src/ElevateMode.h
- src/gui/src/IpcClient.cpp
- src/gui/src/IpcClient.h
- src/gui/src/MainWindow.cpp
- src/gui/src/SettingsDialog.cpp
- src/gui/src/SettingsDialog.h
This pr expands the boolean elevation option to a tristate preference, closing #4323 and #3241
> v1.8.3 Make auto-elevate optional

- src/lib/base/EventTypes.cpp
- src/lib/base/EventTypes.h
- src/lib/client/Client.cpp
- src/lib/client/Client.h
- src/lib/net/TCPSocket.cpp
- src/lib/net/TCPSocket.h
- src/lib/plugin/ns/SecureListenSocket.cpp
- src/lib/plugin/ns/SecureSocket.cpp
- src/lib/plugin/ns/SecureSocket.h
- src/lib/server/ClientListener.cpp
- src/lib/server/ClientListener.h
- src/lib/server/Server.cpp
- src/lib/server/Server.h
- src/lib/synergy/ArgParser.cpp
- src/lib/synergy/ProtocolUtil.cpp
- src/lib/synergy/StreamChunker.cpp
- src/lib/synergy/StreamChunker.h
@XinyuHou Can we merge this branch yet or do we need to cherry pick?
A lot of the SSL refactoring seems to be mixed up in us moving clipboard back to the main thread.
> Move clipboard back to main thread (Fixes issue #4740)

- src/gui/res/ServerConfigDialogBase.ui
- src/gui/src/ServerConfig.cpp
- src/gui/src/ServerConfig.h
- src/gui/src/ServerConfigDialog.cpp
- src/lib/client/Client.cpp
- src/lib/client/Client.h
- src/lib/client/ServerProxy.cpp
- src/lib/server/Config.cpp
- src/lib/server/Config.h
- src/lib/server/Server.cpp
- src/lib/server/Server.h
- src/lib/synergy/ServerArgs.h
- src/lib/synergy/option_types.h
Added an option in GUI to disable clipboard. This setting works on servers, then servers notify clients to disable the clipboard functionality.
> v1.8.3-issue123-disable clipboard option

- src/lib/server/Server.cpp
I have my screens configured such that there is a screen below my primary screen, but nothing to the left of my primary screen. I noticed that when the cursor is in the bottom-left corner of the primary screen, it wouldn't switch to the lower screen. The problem is that the code in `Server::onMouseMovePrimary()` only calls `isSwitchOkay()` for a single direction. When the cursor is in the bottom-left corner, the code calls `isSwitchOkay()` for the `kLeft` direction, but then never checks the `kBottom` direction when that fails. The code in this PR checks `isSwitchOkay()` in both the horizontal and vertical directions when the cursor is in a corner.
> fixed vertical screen switch problem when cursor is in a corner

- src/gui/src/DataDownloader.cpp
- src/gui/src/ScreenSetupView.cpp
- src/gui/src/ScreenSetupView.h
- src/gui/src/ZeroconfServer.cpp
- src/gui/src/ZeroconfServer.h
- src/lib/arch/IArchString.cpp
- src/lib/arch/win32/ArchNetworkWinsock.cpp
- src/lib/arch/win32/ArchTaskBarWindows.cpp
- src/lib/base/String.cpp
- src/lib/ipc/IpcLogOutputter.cpp
- src/lib/ipc/IpcLogOutputter.h
- src/lib/ipc/IpcServer.cpp
- src/lib/net/SecureSocket.cpp
- src/lib/net/TCPSocket.cpp
- src/lib/platform/MSWindowsClipboard.cpp
- src/lib/platform/MSWindowsDesks.cpp
- src/lib/platform/MSWindowsScreen.cpp
- src/lib/platform/MSWindowsScreenSaver.cpp
- src/lib/platform/MSWindowsSession.cpp
- src/lib/platform/MSWindowsUtil.cpp
- src/lib/synergy/App.cpp
- src/lib/synergy/Chunk.cpp
Various minor code quality issues reported by PVS Studio
The only ones with an impact on users are https://github.com/symless/synergy/commit/0c2b89ed2139329bfcdb249eaae27615be880408 , https://github.com/symless/synergy/commit/cc2f1146ea36147717c03ede8e2bcae9d53a9cdb and https://github.com/symless/synergy/commit/e608f8f0814454b14f9cb06a3d807b89d3f93463
Broken optimizations removed in https://github.com/symless/synergy/commit/3e6b6dc7b8ae20133c6e5e77323bb6d7af4674e9 . If this code ever fetched a string longer than 1K, it would leak memory and then perform a null dereference.
> PVS Studio related bugfixes for v1.9

- src/gui/src/AppConfig.cpp
> Disabled default Bonjour auto-config setting

- src/gui/src/ZeroconfService.cpp
> Removed Zeroconf string suffix from Zeroconf service name

- src/gui/src/MainWindow.cpp
> Hack to ignore TIS/TSM log line on macOS

- src/lib/platform/OSXScreen.h
- src/lib/platform/OSXScreen.mm
> Fixed mouse drift by switching from int to float

- src/gui/src/AppConfig.cpp
- src/gui/src/AppConfig.h
- src/gui/src/MainWindow.cpp
- src/gui/src/MainWindow.h
- src/gui/src/ZeroconfService.cpp
> Remember last used auto config host

- src/gui/src/MainWindow.cpp
> Fixed Hostname dialog box opening unnecessarily 

- .cirrus.yml
- CI/MacOS/qtifwsilent.qs
- CI/Windows/build.bat
- CI/Windows/qtifwsilent.qs
- CI/build.sh
- CI/package.sh
- CI/ubuntu1604.Dockerfile
- CI/ubuntu1804.Dockerfile
- CI/ubuntu1904.Dockerfile
- CMakeLists.txt
- src/gui/src/ActionDialog.cpp
- src/gui/src/ScreenSetupView.cpp
#6470
Added Cirrus CI Builds for
- Windows
- MacOS
- Ubuntu 16.04
- Ubuntu 18.04
Linux builds are Via docker containers
MacOS uses Anka VMs via Cirrus CI
Windows uses Google cloud images via Cirus CI (Image managed by Symless)
> Added CI Solution for automated builds

- src/lib/net/SecureSocket.cpp
#6460 
Recreated #6174 due to branch changes and old source
> Fixed TLS socket memory leak

- src/gui/src/AppConfig.cpp
- src/gui/src/MainWindow.cpp
> Fixes auto config UI elements in enterprise versions

- src/gui/src/MainWindow.cpp
- src/gui/src/MainWindow.h
- src/lib/platform/XWindowsUtil.cpp
> Stopped gui locking into retry loop

- README.md
The README.md file on v2-dev branch has very useful information. If anyone is building/using v1-dev it should be readily accessible there also.
> Add README.md from v2-dev to v1-dev branch.

- src/lib/platform/OSXScreen.mm
#3705
Can we have this in the next release please?
> Fix broken hotkeys on macOS servers

- src/gui/src/Action.cpp
- src/gui/src/Action.h
- src/gui/src/ActionDialog.cpp
- src/gui/src/ActionDialogBase.ui
- src/lib/server/Config.cpp
- src/lib/server/InputFilter.cpp
- src/lib/server/InputFilter.h
> Server restart hotkey

- src/lib/platform/MSWindowsScreen.cpp
- src/lib/platform/MSWindowsScreen.h
> Prevented cursor moving off screen when a locking issue may occur

- src/lib/synergy/KeyMap.cpp
> Change info message to debug1

- CMakeLists.txt
Needs testing across multiple Linux Distros
Fixes #6556
> Changed ssl libs to static linking

- src/gui/src/VersionChecker.cpp
> #6588 Added version number to version check request

- src/lib/base/Unicode.cpp
Original PR #6408 
> TBH, I'm not even sure if this code is used, but I think the corrections are straightforward.
This was a good catch and should defiantly be merged
I have linked this to #6593 as it may affect it
> Fixed possible data index bug for Unicode read

- azure-pipelines.yml
- src/gui/CMakeLists.txt
- src/gui/lang.cmd
- src/gui/res/Languages.qrc
- src/gui/res/Synergy.qrc
- src/gui/src/SetupWizardBase.ui
> Fixed problems with translations

- azure-pipelines.yml
- src/gui/src/MainWindow.cpp
- src/gui/src/MainWindowBase.ui
> Limited the log in the GUI to 10,000 lines to prevent RAM hogging

- src/lib/platform/XWindowsEventQueueBuffer.cpp
- src/lib/platform/XWindowsEventQueueBuffer.h
> Updated fix for cusor freezes

- CMakeLists.txt
> FreeBSD compatibility patch

- CI/Windows/windows-build.yml
This PR satisfies the requirements of https://github.com/symless/blacksheep-desktop/issues/40
> Added windows core binaries upload to sandor

- .github/workflows/job-changelog-check.yml
- ChangeLog
> Added Github action to check for changed to changlog

- ChangeLog
Testing #6500 with new deployment process and signing
Resolves #6720
> Adding macdeployqt to cmake

- ChangeLog
- src/lib/client/Client.cpp
- src/lib/client/Client.h
- src/lib/net/SecureListenSocket.cpp
- src/lib/server/Server.cpp
- src/lib/server/Server.h
- src/lib/synergy/App.cpp
- src/lib/synergy/App.h
- src/lib/synergy/ArgParser.cpp
- src/lib/synergy/ArgParser.h
- src/lib/synergy/ArgsBase.cpp
- src/lib/synergy/ArgsBase.h
- src/lib/synergy/ClientApp.cpp
- src/lib/synergy/ClientApp.h
- src/lib/synergy/ClientArgs.cpp
- src/lib/synergy/ClientArgs.h
- src/lib/synergy/DaemonApp.cpp
- src/lib/synergy/IApp.h
- src/lib/synergy/ServerApp.cpp
- src/lib/synergy/ServerApp.h
- src/lib/synergy/ServerArgs.cpp
- src/lib/synergy/ServerArgs.h
- src/test/integtests/net/NetworkTests.cpp
- src/test/unittests/synergy/ArgParserTests.cpp
- src/test/unittests/synergy/ClientArgsParsingTests.cpp
- src/test/unittests/synergy/GenericArgsParsingTests.cpp
- src/test/unittests/synergy/ServerArgsParsingTests.cpp
Resolves #6736 
- Moved ArgsBase, ClientArgs, and ServerArgs to own namespace
- Added some Documentation to Args classes
> Added command line option for custom TLS certificate

- CI/Linux/linux-build.yml
- CI/MacOS/mac-build.yml
- CI/Windows/windows-build.yml
- ChangeLog
- azure-pipelines.yml
Resolves #6743
The problem seems that the CMake files when not in snapshot mode expect an environmental variable `GIT_COMMIT` to be set the the full commit hash.
> Fixed error with about page showing a bad commit hash

- ChangeLog
- src/gui/src/AboutDialog.cpp
- src/gui/src/AboutDialogBase.ui
Resolves #6748 
[SYNERGY-84]
[SYNERGY-84]: https://symless.atlassian.net/browse/SYNERGY-84
> Updated copyright in about to the current build year

- ChangeLog
- src/lib/base/Log.cpp
- src/lib/platform/XWindowsClipboard.cpp
- src/lib/synergy/App.cpp
- src/lib/synergy/ClientApp.cpp
- src/lib/synergy/ServerApp.cpp
> Replaced sprintf with snprintf

- .github/workflows/job-jira-issues.yml
Replaces #6756 due to sonar gate error
> Added job to add issue to jira automatically

- ChangeLog
- src/gui/src/AppConfig.cpp
> Fixed Synergy loseing license when creating a System scope config

- ChangeLog
- src/lib/synergy/ProtocolUtil.cpp
- src/lib/synergy/ProtocolUtil.h
> Added a check to prevent buffer overflow

- ChangeLog
- src/lib/common/Version.cpp
- src/lib/common/Version.h
- src/lib/synergy/App.cpp
> SYNERGY-189 Updated copyright in cmd version to use build date

- ChangeLog
- src/gui/src/ActivationDialog.cpp
- src/gui/src/LicenseManager.cpp
- src/gui/src/LicenseManager.h
- src/gui/src/MainWindow.cpp
- src/gui/src/MainWindow.h
- src/lib/shared/SerialKey.cpp
- src/lib/shared/SerialKey.h
- src/lib/shared/SerialKeyType.cpp
- src/lib/shared/SerialKeyType.h
- src/test/unittests/shared/SerialKeyTests.cpp
- src/test/unittests/shared/SerialKeyTypeTests.cpp
License key expiry has been implemented.
I used the same algorithm as for trial version.
The new word "temp" can be used instead of "trial" in the same column as trial.
Also purchase link has been corrected.
> SYNERGY-110 license key expiry

- .github/workflows/job-build-linux-centos.yml
- .github/workflows/job-build-linux-debian.yml
- .github/workflows/job-build-linux-fedora.yml
- .github/workflows/job-build-linux-ubuntu.yml
- .github/workflows/job-build-mac.yml
- .github/workflows/job-build-windows.yml
- ChangeLog
- azure-pipelines.yml
Squashed previous PR into a new branch so sonar cloud can run
> Switched to Github actions for builds on PR and pushes

- ChangeLog
- src/lib/arch/unix/ArchFileUnix.cpp
- src/lib/platform/XWindowsScreen.cpp
- src/lib/synergy/ArgParser.cpp
- src/test/unittests/synergy/ArgParserTests.cpp
> incorporating sonar's major

- .github/workflows/codeql-analysis.yml
- ChangeLog
> Enabling Github Code Scanning

- ChangeLog
- src/gui/src/main.cpp
> removing unnecessary check on icon tray

- ChangeLog
- src/gui/res/mac/Info.plist
SYNERGY-622 Application is blurry and unfocused on macOS
> Fixed #6858 Application is blurry and unfocused on macOS

- ChangeLog
Found this minor typo while looking at the latest Changelog.
> Fixed typo in Changelog.

- ChangeLog
- src/lib/arch/IArchString.cpp
- src/lib/arch/IArchString.h
- src/lib/arch/unix/ArchNetworkBSD.cpp
- src/lib/arch/unix/ArchNetworkBSD.h
- src/lib/base/String.cpp
- src/lib/base/Unicode.cpp
- src/lib/base/Unicode.h
- src/lib/net/NetworkAddress.cpp
- src/lib/platform/XWindowsClipboard.cpp
- src/lib/server/Config.cpp
- src/lib/synergy/ArgParser.cpp
- src/lib/synergy/KeyMap.cpp
- src/lib/synergy/KeyMap.h
- src/lib/synergy/KeyState.cpp
- src/lib/synergy/KeyState.h
- src/test/mock/synergy/MockKeyState.h
- src/test/unittests/arch/IArchStringTests.cpp
- src/test/unittests/arch/unix/ArchNetworkBSDTests.cpp
- src/test/unittests/base/UnicodeTests.cpp
- src/test/unittests/server/ConfigTests.cpp
- src/test/unittests/synergy/KeyMapTests.cpp
- src/test/unittests/synergy/KeyStateTests.cpp
Synergy-591
This PR addresses all 25 bugs pointed out by SonarCloud. Most of them are related to the use of for constructs (styles that are prone to errors); one does unveil a potential memory leak on BSD.
All sections addressed have never before been visited by tests, thus the big cost and complexity that the tests related to this PR will have -but there's also its value right there.
> Remaining SonarCloud Bugs

- ChangeLog
- src/lib/synergy/ArgParser.cpp
- src/lib/synergy/ArgsBase.h
- src/lib/synergy/ClientAppArguments.md
- src/lib/synergy/ServerApp.cpp
- src/lib/synergy/ServerAppArguments.md
- src/lib/synergy/win32/AppUtilWindows.cpp
- src/test/unittests/synergy/GenericArgsParsingTests.cpp
Review of the existing arguments prompted the removal of an unused one, and a small fix for an uninitialised value.
> Document CLI arguments

- ChangeLog
- src/gui/res/lang/gui_es-ES.ts
- src/gui/src/ConfigWriter.cpp
> Save global settings

- .github/workflows/job-build-raspberry-pi.yaml
- ChangeLog
- Fix file glob for deb build on `Raspberry Pi`
> Fix package glob

- .github/workflows/job-build-raspberry-pi.yaml
- ChangeLog
- Fixes a stage name issue
- Fixes the check for synergy enterprise
> Add stage to file name

- .github/workflows/job-build-mac-10.13.yaml
- CI/MacOS/notorize.sh
- ChangeLog
This adds a builder for macOS 10.13
> SYNERGY-801 Add self-hosted runner for OSX 10.13

- .github/workflows/job-build-mac-10.13.yaml
- ChangeLog
Not sure how this was not caught earlier. I seemed to miss this instruction when I set this up.
> Add missing make instruction

- ChangeLog
- src/gui/src/MainWindow.cpp
* Add temporary fix of problem with missed config file
> SYNERGY-835 Synergy stops working

- ChangeLog
- src/gui/src/MainWindow.cpp
- src/gui/src/ServerConfigDialog.cpp
- src/gui/src/ServerConnection.cpp
The following issues were fixed:
1. Eliminate using isLinkLocal to fix compilation on old Linux platforms
2. Fixed problem with server screen on installation from scratch
3. Fixed problem with repeated popups on Windows system
> SYNERGY-694 Setup client configuration issues

- ChangeLog
- src/gui/src/VersionChecker.cpp
Updates:
1. the URL path for version checker set to new staging URL
2. added X-Synergy-Language to contain the user's system language
> Synergy 542 language record

- ChangeLog
- src/gui/src/SettingsDialogBase.ui
> SYNERGY-907 Client tray language switcher reverts to EN

- ChangeLog
- src/gui/src/MainWindow.cpp
- src/gui/src/MainWindow.h
Should not be merged until the RC 1.14.0 is merged
> SYNERGY-124 - Start synergy if the service is idle

- .github/workflows/job-test-linux-fedora.yml
- ChangeLog
- azure-pipelines.yml
It's the same as https://github.com/symless/synergy-core/pull/7023 but for the master branch.
> SYNERGY-1005 Add Fedora 33 to build and release pipeline

- ChangeLog
- src/gui/src/ActivationDialog.cpp
- src/gui/src/AppConfig.cpp
- src/lib/shared/EditionType.h
- src/lib/shared/SerialKeyEdition.cpp
- src/lib/shared/SerialKeyEdition.h
- src/test/unittests/shared/SerialKeyEditionTests.cpp
This PR adds ability to generate two new licenses for the chinese market.
These licenses are the same as pro and basic but with another title.
> SYNERGY-1028 New licenses for Chinese market

- ChangeLog
- src/gui/src/ServerConfig.cpp
* Fix save order for clipboard and clipboard chunk size
> SYNERGY-1133 Clipboard sharing re-enables automatically

- scripts/buildCoreLinux.sh
probably from a copy/paste at some point.
> zip filename fix

- .github/workflows/job-build-mac-m1.yaml
- .github/workflows/job-test-mac.yml
- ChangeLog
New PR based on #7122 by @stephengroat's.
This excludes the `aws-upload-mac.yml` change because we deleted this file.
> Brew bundle

- .github/workflows/job-build-raspberry-pi.yaml
- CI/Linux/linux-build.yml
- CI/deb_changelog.py
- ChangeLog
- debian/source/lintian-overrides
Adds the changelog to the deb files instead of the "Initial Commit" message.
> Add changelogs to deb's

- .github/workflows/job-test-linux-fedora.yml
- ChangeLog
- azure-pipelines.yml
> Add fedora 36 build

- ChangeLog
- src/gui/src/AppConfig.cpp
- src/gui/src/MainWindow.cpp
Fixes https://github.com/symless/synergy-core/issues/7186
> SYNERGY1-1544 Issue with TLS options when user switches to system profile

- ChangeLog
- src/gui/src/AboutDialog.cpp
- src/gui/src/AboutDialog.h
- src/gui/src/AboutDialogBase.ui
- src/gui/src/CreditsLoader.cpp
- src/gui/src/CreditsLoader.h
- src/lib/synergy/unix/SynergyXkbKeyboard.cpp
> Special contributor mentions on the about screen

- src/gui/src/AboutDialog.cpp
- src/gui/src/AboutDialog.h
- src/gui/src/AppConfig.cpp
- src/gui/src/AppConfig.h
- src/gui/src/CreditsLoader.cpp
- src/gui/src/CreditsLoader.h
- src/gui/src/MainWindow.cpp
SYNERGY1-1570
This PR moves API URL to settings file which allow change the URL and test this functionality.
> Move credits API URL to config file

- src/gui/src/ActivationDialog.cpp
- src/gui/src/AppConfig.cpp
- src/lib/shared/EditionType.h
- src/lib/shared/SerialKeyEdition.cpp
- src/lib/shared/SerialKeyEdition.h
- src/lib/shared/SerialKeyParser.cpp
> Add TLS to Synergy (Lite edition)

- .github/workflows/job-test-mac.yml
- ChangeLog
[SYNERGY1-1595](https://symless.atlassian.net/browse/SYNERGY1-1595)
> Update macos workflow to use macos-latest

- ChangeLog
- azure-pipelines.yml
[SYNERGY1-1595](https://symless.atlassian.net/browse/SYNERGY1-1595)
Update azure pipelines to use `macos-latest`.
> Update azure pipelines to use latest macos image

- ChangeLog
- cmake/Version.cmake
- src/gui/src/AppConfig.cpp
- src/gui/src/AppConfig.h
- src/gui/src/MainWindow.cpp
- src/gui/src/MainWindow.h
- src/gui/src/MainWindowBase.ui
- src/gui/src/ServerConfig.cpp
- src/gui/src/ServerConfig.h
- src/gui/src/SettingsDialog.cpp
- src/gui/src/SettingsDialogBase.ui
- src/lib/client/Client.cpp
- src/lib/client/Client.h
- src/lib/net/CMakeLists.txt
- src/lib/net/InverseSockets/AutoArchSocket.cpp
- src/lib/net/InverseSockets/AutoArchSocket.h
- src/lib/net/InverseSockets/InverseClientSocket.cpp
- src/lib/net/InverseSockets/InverseClientSocket.h
- src/lib/net/InverseSockets/InverseServerSocket.cpp
- src/lib/net/InverseSockets/InverseServerSocket.h
- src/lib/net/InverseSockets/InverseSocketFactory.cpp
- src/lib/net/InverseSockets/InverseSocketFactory.h
- src/lib/server/Config.cpp
- src/lib/server/Config.h
- src/lib/synergy/ArgParser.cpp
- src/lib/synergy/ClientApp.cpp
- src/lib/synergy/ClientApp.h
- src/lib/synergy/ClientArgs.h
- src/lib/synergy/ServerApp.cpp
- src/lib/synergy/ServerApp.h
> Add ability to initiate connection from server

- ChangeLog
- src/lib/net/InverseSockets/InverseClientSocket.h
- src/lib/net/InverseSockets/InverseServerSocket.cpp
- src/lib/net/InverseSockets/InverseServerSocket.h
- src/lib/net/InverseSockets/InverseSocketFactory.cpp
- src/lib/net/InverseSockets/SecureClientSocket.cpp
- src/lib/net/InverseSockets/SecureClientSocket.h
- src/lib/net/InverseSockets/SecureServerSocket.cpp
- src/lib/net/InverseSockets/SecureServerSocket.h
- src/lib/net/InverseSockets/SslApi.cpp
- src/lib/net/InverseSockets/SslApi.h
- src/lib/net/InverseSockets/SslLogger.cpp
- src/lib/net/InverseSockets/SslLogger.h
- src/lib/net/SecureSocket.cpp
- src/lib/net/SecureSocket.h
> Initiate TLS connection from server

- src/lib/net/InverseSockets/InverseServerSocket.cpp
- src/lib/net/InverseSockets/InverseServerSocket.h
- src/lib/net/SecureSocket.cpp
- src/lib/server/ClientListener.cpp
- src/lib/server/ClientListener.h
- src/lib/server/Config.cpp
- src/lib/server/Config.h
- src/lib/server/Server.cpp
- src/lib/synergy/ServerApp.cpp
SYNERGY1-1611
This RR adds reconnection functionality to the server when server initiate the connection. 
ChangeLog wasn't updated because this PR is a part of functionality which was implemented previously.
> Add ability to reconnect from server side

- src/lib/net/InverseSockets/SecureClientSocket.cpp
- src/lib/server/ClientListener.cpp
- src/lib/server/ClientListener.h
- src/lib/server/Server.cpp
- src/lib/server/Server.h
SYNERGY1-1618
This PR fixes the problem with reconnection when TLS is on and the user should accept server fingerprint.
> Fix issue with reconnection when server initiate TLS connection. 

- src/cmd/synergy-core/CMakeLists.txt
- src/cmd/synergy-core/synergy-core.cpp
- src/cmd/synergy-core/synergy-core.exe.manifest
> Add manifest for synergy-core to fix problem with dpi on windows

- ChangeLog
- flatpak/synergy-business.yml
- flatpak/synergy-enterprise.yml
- flatpak/synergy.yml
SYNERGY1-1592
This PR fixes problem with tls generation for flatpak package.
> Fix tls certificate generation for flatpak

- ChangeLog
- dist/wix/Product.wxs
SYNERGY1-1644
This PR adds firewall exception for synergy client into Windows installer
> Add firewall exception for synergy client

- ChangeLog
- azure-pipelines.yml
Add build pipelines for fedora 37 and 38
> Add new fedora pipelines

- .github/workflows/job-build-mac-m1.yaml
- .github/workflows/job-test-mac.yml
- ChangeLog
> Fix backward compatibility for m1 build

- ChangeLog
- src/lib/platform/XWindowsKeyState.cpp
SYNERGY1-1653
Remove extra key press traces for Linux
> Remove extra key press traces for Linux

- ChangeLog
- src/lib/platform/MSWindowsWatchdog.cpp
- src/lib/synergy/App.cpp
- src/lib/synergy/ArgParser.cpp
- src/lib/synergy/ClientApp.cpp
- src/lib/synergy/ServerApp.cpp
S3-834
This PR changes core start errors to FATAL.
> Change core start errors to fatal

- src/lib/synergy/ServerApp.cpp
> Change error priority based on param

- CI/deb_changelog.py
- ChangeLog
> Apply markdown formatting to ChangeLog

- README.md
We feel that the readme message has now fulfilled its purpose. Our Ukrainian team members asked that we share these links:
- https://bank.gov.ua/en/news/all/natsionalniy-bank-vidkriv-spetsrahunok-dlya-zboru-koshtiv-na-potrebi-armiyi
- https://www.prytula-co.org/
- https://www.comebackalive.in.ua/
> We stand with Ukraine

- CMakePresets.json
- ChangeLog
> Add Linux and macOS CMake presets

- CMakePresets.json
- ChangeLog
> Static link OpenSSL libs in CMake preset for Windows

- .github/workflows/ci.yml
- .github/workflows/stale-issues.yml
- ChangeLog
https://symless.atlassian.net/browse/S1-1689
> Schedule CI daily at 5am to detect code rot early

- cmake/Definitions.cmake
https://symless.atlassian.net/browse/S1-1698
> Fixed use of `ENV` in CMake `if`

- .github/workflows/ci.yml
- config.yaml
https://symless.atlassian.net/browse/S1-1704
> Fix: OpenSUSE build failing (libqt5/libxslt dep error)

- .github/workflows/create-release.yml
https://symless.atlassian.net/browse/S1-1709
> Rename `next-version-action` to `actions/next-version`

- .github/workflows/create-release.yml
https://symless.atlassian.net/browse/S1-1709
> Override stage to 'snapshot' if not release

- .github/workflows/ci.yml
- .gitignore
- ChangeLog
- scripts/lib/linux.py
- scripts/package.py
- src/lib/synergy/ArgParser.cpp
- src/lib/synergy/ArgsBase.h
- src/lib/synergy/ClientApp.cpp
- src/lib/synergy/ServerApp.cpp
- src/test/unittests/synergy/ArgParserTests.cpp
https://symless.atlassian.net/browse/S1-1696
1. Remove any existing Synergy install
2. Configure and build (`cmake ...`)
3. `./scripts/install_deps.py --only-python`
4. `./scripts/package.py`
> Re-implement packaging for GitHub workflows (Linux ARM)

- .github/docker/debian-12/Dockerfile
- .github/workflows/build-containers.yml
https://symless.atlassian.net/browse/S1-1711
> Automated weekly build of Docker images for Linux runners

- ChangeLog
- LICENSE
- cmake/Packaging.cmake
- config.yaml
- src/lib/common/Version.cpp
https://symless.atlassian.net/browse/S1-1705
To test:
1. Fresh Debian-like distro install
2. Download `.deb`
3. Install with `apt`
4. Expect: No dep errors
> Add missing dependencies to Debian package

- res/dist/arch/PKGBUILD.in
https://symless.atlassian.net/browse/S1-1715
> Disable debug for Arch package

- .github/workflows/codeql-analysis.yml
- .github/workflows/lint-changelog.yml
- .github/workflows/lint-source.yml
- .github/workflows/sonarcloud-analysis.yml
- ChangeLog
https://symless.atlassian.net/browse/S1-1716
> Improve workflow triggers to ensure correct run time

- .github/workflows/build-containers.yml
- .github/workflows/ci.yml
https://symless.atlassian.net/browse/S1-1722
Note: Commits are related to testing Windows ARM64, but those changes were backed out (will be done in a separate PR) since the ARM64 runner doesn't appear to be setup for development (perhaps it's only useful for testing binaries).
> Use GitHub ARM64 runner for Linux

- .vscode/settings.json
- ChangeLog
- src/lib/server/Server.cpp
https://symless.atlassian.net/browse/S1-1740
> Catch exception propagating to `Server` dtor

- ChangeLog
- src/gui/src/MainWindow.cpp
https://symless.atlassian.net/browse/S1-1771
> Only load core after settings have fully loaded

- ChangeLog
- src/lib/gui/AppConfig.cpp
- src/lib/gui/AppConfig.h
https://symless.atlassian.net/browse/S1-1773
> Handle empty value for computer name setting

- ChangeLog
- src/lib/gui/core/ServerConnection.cpp
https://symless.atlassian.net/browse/S1-1724
> More reliable button click detection for add client dialog

- ChangeLog
- cspell.json
- src/gui/src/ActivationDialog.cpp
- src/gui/src/MainWindow.cpp
- src/gui/src/MainWindow.h
- src/gui/src/MainWindowBase.ui
- src/gui/src/SettingsDialog.cpp
- src/lib/gui/core/CoreProcess.cpp
- src/lib/license/License.cpp
- src/lib/license/License.h
- src/lib/license/SerialKeyType.cpp
- src/lib/license/SerialKeyType.h
- src/lib/license/parse_serial_key.cpp
- src/test/unittests/shared/LicenseTests.cpp
https://symless.atlassian.net/browse/S1-1764
> Parse date numbers as long instead of int

- cmake/Packaging.cmake
- scripts/lib/linux.py
- scripts/package.py
https://symless.atlassian.net/browse/S1-1789
> Remove .sh package to reduce confusion

- .env.example
- ChangeLog
- src/gui/src/MainWindow.cpp
- src/lib/gui/constants.h
- src/lib/gui/core/CoreProcess.cpp
- src/lib/gui/core/CoreProcess.h
- src/lib/gui/dialogs/SettingsDialog.cpp
- src/lib/gui/license/LicenseHandler.h
- src/lib/gui/license/license_config.cpp
- src/lib/gui/license/license_config.h
- src/lib/gui/messages.cpp
- src/lib/gui/tls/TlsUtility.cpp
- src/lib/gui/tls/TlsUtility.h
https://symless.atlassian.net/browse/S1-1791
> Introduced new env vars for testing

- ChangeLog
- src/lib/gui/dialogs/UpgradeDialog.cpp
- src/lib/gui/dialogs/UpgradeDialog.h
https://symless.atlassian.net/browse/S1-1735
Workaround Qt 6.5 bug (problem does not occur in Qt 6.4)
> Compare result of `clickedButton` instead of `exec`

- ChangeLog
- src/gui/src/AboutDialogBase.ui
https://symless.atlassian.net/browse/S1-1776
> Fixed light logo filename on about screen

- ChangeLog
- src/lib/gui/Logger.cpp
- src/lib/gui/Logger.h
- src/lib/gui/messages.cpp
- src/test/unittests/gui/LoggerTests.cpp
https://symless.atlassian.net/browse/S1-1795
> Share file line logic between logger and message box

- .github/actions/run-tests-setup/action.yml
- .github/actions/run-tests/action.yml
- .github/workflows/ci.yml
- .github/workflows/sonarcloud-analysis.yml
- .github/workflows/valgrind-analysis.yml
- ChangeLog
https://symless.atlassian.net/browse/S1-1810
> Only add PR comments for internal PR

- scripts/install_deps.py
https://symless.atlassian.net/browse/S1-1801
> Restore `--only-python` arg to only install Python deps

- README.md
There is some misinformation that I'd like to correct! 🙂
> Update README.md to provide more community info

- README.md
Blocked by: #7533, #7535  {no-changelog-lint}
@sithlord48 What do you think? [Preview](https://github.com/deskflow/deskflow/blob/5f050508688c0ffb6c26c19809fa8206cd01cf54/README.md)
> docs: add sponsor badge and blurb to readme

- README.md
Ooo, shiny. [Preview](https://github.com/deskflow/deskflow/tree/readme-logo)
> docs: add new logo to readme and update screenshot

- .github/workflows/ci-comment.yml
> ci: add link back to workflow summary in pr comment

- .github/workflows/ci-comment.yml
> ci: handle files with same name in ci comment workflow

- .github/workflows/ci-comment.yml
> ci: use braces block for formatting in ci comment

- .github/workflows/ci-comment.yml
> ci: lookup pr number by head sha for ci comment

- README.md
URL to sponsor badge was broken.
> docs: Fixed broken URL in README.md

- README.md
Everyone seems to prefer Matrix over IRC, so let's make that our primary form of communication.
Discussion: https://github.com/deskflow/deskflow/discussions/7604
> docs: Update `README.md` with Matrix link

- .github/workflows/ci.yml
- CMakePresets.json
- cmake/Libraries.cmake
- src/lib/net/CMakeLists.txt
- Use Find_package to get openssl 1.1.1 + 
- Link with proper names
- Rm Windows specific macro
> build: findSSL via cmake

- .gitignore
- Update `.gitignore` to also ignore common cmake user and generated files
> chore: cmake user files to gitignore

- .github/workflows/ci.yml
- Restore the working vcpkg cache
> ci: working vcpkg cache

- .github/workflows/ci.yml
fixes #7555 
- Attempt to do continuous and normal releases
> ci: attempt releases

- .github/ISSUE_TEMPLATE/bug_report.yml
🚨 Grammar police. Wew wew wew.
> Fixed minor typos in the bug report template

- src/gui/src/MainWindow.cpp
- src/lib/arch/unix/ArchFileUnix.cpp
- src/lib/gui/paths.h
- src/lib/gui/tls/TlsFingerprint.cpp
- src/lib/net/InverseSockets/SecureServerSocket.cpp
- src/lib/net/InverseSockets/SslApi.cpp
- src/lib/net/SecureListenSocket.cpp
- src/lib/net/SecureSocket.cpp
OMG... how many places is this dir string defined? Will fix that in a separate PR.
Fixes: #5762
> Change TLS dir to same as Qt config

- src/lib/gui/VersionChecker.cpp
> fix: Check for errors before reading version string

- .github/workflows/ci.yml
Sight reorder to the steps so that 
All jobs need lint first  
Simplify conditions 
Needs #7691 to pass arch
> ci: clearer and cleaner steps

- res/dist/arch/PKGBUILD.in
Fix up arch package
- Add missing pubixml dependency
- allow building on more architectures
> Arch package fixup

- .github/workflows/ci.yml
> Always run PR comments job

- .editorconfig
- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
Intent: Attempting to keep indentation consistent across workflow files and CMake.
> docs: Add .editorconfig file

- src/lib/gui/core/WaylandWarnings.cpp
- src/lib/gui/core/WaylandWarnings.h
- src/lib/gui/messages.cpp
- src/lib/gui/messages.h
- src/test/unittests/gui/core/WaylandWarningsTests.cpp
> Remove Wayland experimental pop

- .github/workflows/ci-linux.json
- .github/workflows/ci.yml
- cmake/Packaging.cmake
- Linux Packages via CPack only with proper name
- new macro to set linux distro name and rpm / deb package release info
> build: linux packages with proper names using cpack

- .vscode/launch.json
- .vscode/tasks.json
I intend to move the `.vscode` dir out of this project as it's a relic of a corporate repo, but until then these changes will significantly help my productivity.
> build: Add `gtest-args` for VS Code users

- cmake/Packaging.cmake
> chore: resolve cmake cap nits

- src/lib/gui/dialogs/AboutDialog.cpp
> fix: Let users select version number and build in About Dialog

- .github/ISSUE_TEMPLATE/feature_request.yml
For a feature request we only want to know about the proposed feature
> chore: Update feature request template

- .github/actions/add-kitware-repo/action.yml
- .github/workflows/ci.yml
- .github/workflows/sonarcloud-analysis.yml
- .github/workflows/valgrind-analysis.yml
- CMakeLists.txt
> build: Require cmake 3.24

- res/dist/arch/PKGBUILD.in
> build: arch package won't install /bin

- src/gui/src/ServerConfigDialog.cpp
- src/gui/src/ServerConfigDialog.h
> fix: server config dialog show event

- .github/workflows/ci.yml
- cmake/Libraries.cmake
- src/lib/deskflow/CMakeLists.txt
- vcpkg.json
- get and other items from vcpkg and cache them on the ci
> build: use vcpkg for all depends, vcpkg action on ci to cache

- src/gui/src/ScreenSetupModel.cpp
Resolve: https://github.com/deskflow/deskflow/security/code-scanning/559
> Static cast screen column count for scan alert 559

- meson.build
- subprojects/packagefiles/wintoast/meson.build
- subprojects/wintoast.wrap
we left some meson items for win toast.
> build: remove stale meson parts for wintoast

- .github/workflows/codeql-analysis.yml
- .github/workflows/sonarcloud-analysis.yml
- .github/workflows/valgrind-analysis.yml
> ci: Bump containers for analyze workflows

- cmake/Libraries.cmake
- cmake/Packaging.cmake
- res/dist/wix/Product.wxs
- src/lib/deskflow/CMakeLists.txt
- properly link wintoast
- Fix #7763
> Link wintoast correctly to fix windows installer

- cmake/Libraries.cmake
This was intended to be part of #7781 
Removes the two macros for lib portal in libraries.cmake
> ci: remove unused libportal check from Librarires.cmake

- src/lib/gui/dialogs/SettingsDialogBase.ui
- Adds two _What's This?_ attributes related to the Windows service
- Rewords the related tooltips to provide a brief explanation
> Elaborate on settings dialog help (what's this)

- src/cmd/deskflow-core/CMakeLists.txt
- src/cmd/deskflow-legacy/CMakeLists.txt
- src/cmd/deskflowc/CMakeLists.txt
- src/cmd/deskflowd/CMakeLists.txt
- src/cmd/deskflows/CMakeLists.txt
- src/lib/arch/CMakeLists.txt
- src/lib/base/CMakeLists.txt
- src/lib/client/CMakeLists.txt
- src/lib/deskflow/CMakeLists.txt
- src/lib/io/CMakeLists.txt
- src/lib/ipc/CMakeLists.txt
- src/lib/mt/CMakeLists.txt
- src/lib/net/CMakeLists.txt
- src/lib/platform/CMakeLists.txt
- src/lib/server/CMakeLists.txt
- Removed  globs from all but `tests`, `gui` and `lib/gui`
> Mosty glob free

- cmake/Packaging.cmake
After talking with a debian package maintainer he mentioned
We are not making official packages
-  we should not set a rpm or debian revision
-  we should do not have to use 'correct' names for deb / rpm
- Remove the RPM / DEB REVISION
- Use `DistroName_DistroVersion_Archtecture` for the "OS String" on all linux packages  made by cpack
EX `deskflow-1.17.0.133-debian_trixie_x86_64.deb`
> build: update package names for linux to be more unified

- .github/actions/winget-publish/action.yaml
- .github/workflows/ci.yml
resolve #7808 
Took the idea from: https://techcommunity.microsoft.com/t5/educator-developer-blog/wingetcreate-keeping-winget-packages-up-to-date/ba-p/4037598
> CI: added updated winget package submission

- doc/CMakeLists.txt
Fixes minor nits around Doxygen messages.
> docs: Improve error messages around Doxygen

- src/lib/deskflow/App.cpp
> fix: crash on --help arg

- README.md
- Add contributors to the read me [Preview](https://github.com/deskflow/deskflow/blob/contribs_onReadme/README.md)
> docs: contributors on readme

- .github/actions/winget-publish/action.yaml
Update the package name scheme used by winget publish
> ci: update winget release for new filename scheme

- .github/workflows/continuous-integration.yml
> ci: consistant upload name for flatpak 

- src/lib/net/SecureSocket.cpp
- src/lib/net/SecureSocket.h
> Fix(CVE-2021-42074): Handle SSL race conditions and segmentation fault 

- src/lib/base/EventTypes.cpp
- src/lib/base/EventTypes.h
- src/lib/client/ServerProxy.cpp
- src/lib/deskflow/PacketStreamFilter.cpp
- src/lib/deskflow/PacketStreamFilter.h
- src/lib/deskflow/ProtocolUtil.cpp
- src/lib/deskflow/protocol_types.h
- src/lib/net/SecureSocket.cpp
- src/lib/net/TCPSocket.cpp
- src/lib/server/ClientProxy1_0.cpp
- src/lib/server/ClientProxyUnknown.cpp
> Fix(CVE-2021-42076): Enforce maximum message length

- .github/actions/lint-check/action.yml
- src/apps/deskflow-gui/MainWindow.cpp
- fix lint action to follow proper style
> ci: update lint action style

- CMakeLists.txt
- deploy/linux/org.deskflow.deskflow.metainfo.xml
> Release 1.18.0

- src/apps/deskflow-gui/MainWindow.cpp
- Check if the server / client is running and stop if when switching modes.
> Stop core process when mode changes in gui

- src/apps/deskflow-gui/Hotkey.cpp
- src/apps/deskflow-gui/Hotkey.h
Fix, multi action hotkeys being broken (Port, https://github.com/debauchee/barrier/pull/915 )
- General improvements to the Hotkey itself also
> Hotkey fix

- src/apps/deskflow-gui/CMakeLists.txt
- src/apps/deskflow-gui/dialogs/SettingsDialog.cpp
- src/apps/deskflow-gui/main.cpp
- src/lib/gui/CMakeLists.txt
Remove unused and undefined vars
- DESKFLOW_GUI_HOOK_LIB
- DESKFLOW_GUI_HOOK_HEADER
> Chore: rm unused DESKFLOW_GUI_HOOK Items

- src/apps/deskflow-gui/MainWindow.cpp
> Fix8059 re assign quit key shortcut on windows

- src/apps/deskflow-gui/dialogs/AboutDialog.cpp
- src/apps/deskflow-gui/dialogs/AboutDialog.h
- Copy more info to the clipboard for version, should help with bugs reports 
-  + Qt Version
-  + OS Info / De name / session type
Example
```
Deskflow: 1.18.0.46(3875e411)
Qt: 6.8.1
System: Arch Linux Session: KDE(wayland)
```
> refactor: copy more info with the about dialog info's copy button

- .github/workflows/continuous-integration.yml
fixes https://github.com/deskflow/deskflow/issues/7884
> ci: add builder for ubuntu 25.04

- src/lib/deskflow/unix/AppUtilUnix.cpp
- src/lib/deskflow/unix/AppUtilUnix.h
Fixed based on #8112 for bsd users
> fix: check bsdpath for evdev fixes #8112

- src/lib/deskflow/unix/X11LayoutsParser.cpp
It perhaps no variant for a keyboard's layout, set a default value in order to continue detect local language.
Log: Fix detect language.
> fix: Fix detect language

- src/apps/deskflow-gui/dialogs/SettingsDialog.ui
compatability =>
compatibility
> Fix a typo in SettingsDialog

- src/lib/platform/EiScreen.cpp
based on https://github.com/input-leap/input-leap/pull/2167
> chore: reset screen xywh on update_shape

- src/lib/base/CMakeLists.txt
- src/lib/base/finally.h
- src/lib/io/CMakeLists.txt
- src/lib/io/filesystem.cpp
- src/lib/io/filesystem.h
- src/lib/io/win32/encoding_utilities.cpp
- src/lib/io/win32/encoding_utilities.h
- src/lib/net/CMakeLists.txt
- src/lib/net/FingerprintData.cpp
- src/lib/net/FingerprintData.h
- src/lib/net/FingerprintDatabase.cpp
- src/lib/net/FingerprintDatabase.h
> Add FingerPrint DB

- src/apps/deskflow-gui/MainWindow.cpp
- src/apps/deskflow-gui/MainWindow.h
- src/apps/deskflow-gui/MainWindow.ui
- Dont use `on` names
- Conform to naming conventions.
- Don't use lambda for items that are directly connectable
> Gui cleanup.main window

- src/apps/deskflow-gui/MainWindow.cpp
- src/apps/deskflow-gui/MainWindow.h
> fix: Security icons showing with fresh install

- .github/workflows/codeql-analysis.yml
- .github/workflows/continuous-integration.yml
- .github/workflows/sonarcloud-analysis.yml
- .github/workflows/valgrind-analysis.yml
Use the v1 tag for fancycheckout
> chore: use fancy-checkout v1 tag

- src/apps/deskflow-gui/MainWindow.cpp
show the fingerprint label after updating
> fix: Update local fingerprint label after fingerprint regeneration

- src/apps/deskflow-gui/MainWindow.cpp
- src/apps/deskflow-gui/MainWindow.h
MY "version" of #8209 
- Use a method to return the localfingerprintPath
- use less stdstring to in the gui
> Main window update

- src/apps/deskflow-gui/VersionChecker.cpp
- update the log level of the update success to Debug
- fixes: #8224
> chore: move version check log to debug, fixes #8224

- src/apps/deskflow-gui/MainWindow.cpp
> fix: log expanded on start up and windows not resizeable

- src/apps/deskflow-gui/MainWindow.cpp
> fix: raise mainwindow on update check dialog

- sonar-project.properties
CI already adds these with CLI options.
https://github.com/deskflow/deskflow/blob/a1400ab9b3138e808cb8e3bca15e53a11c48754b/.github/workflows/sonarcloud-analysis.yml#L79-L80
> chore: Remove unused config lines from sonar-project.properties

- src/apps/deskflow-gui/MainWindow.cpp
- src/apps/deskflow-gui/MainWindow.h
> fix: #8259, Track seperate list for attempted client and server connections

- src/apps/deskflow-client/CMakeLists.txt
- src/apps/deskflow-core/CMakeLists.txt
- src/apps/deskflow-gui/CMakeLists.txt
- src/apps/deskflow-server/CMakeLists.txt
> chore: update windows rc descriptions fixes #8270

- src/apps/deskflow-gui/ServerConfig.cpp
- src/lib/gui/config/Screen.cpp
Resolve issues related to the `switchCorners` setting
> Address switch Corner issues.

- src/apps/deskflow-daemon/CMakeLists.txt
- src/apps/deskflow-daemon/deskflow-daemon.cpp
- src/lib/arch/win32/ArchDaemonWindows.h
> Fix Windows daemon version print timing and tidy up descriptions

- src/apps/deskflow-daemon/CMakeLists.txt
- src/apps/deskflow-daemon/deskflow-daemon.cpp
- src/apps/deskflow-gui/CMakeLists.txt
- src/apps/deskflow-gui/dialogs/AboutDialog.cpp
- src/lib/common/CMakeLists.txt
- src/lib/common/common.h
- src/lib/common/version.h
Fixes: #8304
Blocked by: #8303 (merge that one first)
> feat: Show Git SHA in Windows daemon version number

- deploy/windows/wix-patch.xml.in
> chore: Fixed Windows service description in wix-patch.xml

- src/lib/arch/win32/ArchMiscWindows.cpp
Some contributors have only VS2019 and have not yet updated to VS2022. We should allow them to build as well (so they aren't forced to update their IDE and risk breaking their dev env).
> fix: Allow compiling on VS2019 for contributors with old IDEs

- deploy/windows/wix-patch.xml.in
> Check for MSVC redist before starting service on Windows

- src/apps/deskflow-gui/MainWindow.cpp
- src/lib/common/constants.h.in
- src/lib/gui/paths.h
- src/lib/gui/tls/TlsCertificate.cpp
- src/lib/net/SecureSocket.cpp
> chore: Rename TLS constants for consistency

- src/lib/arch/win32/ArchMiscWindows.cpp
- src/lib/arch/win32/ArchMiscWindows.h
Fixes: #8338
Blocked by:
- #8339
> feat: Use `EnumProcessModules` to search loaded Windows modules

- src/apps/deskflow-daemon/deskflow-daemon.cpp
- src/lib/arch/IArchDaemon.h
- src/lib/arch/win32/ArchDaemonWindows.cpp
- src/lib/arch/win32/ArchDaemonWindows.h
- src/lib/arch/win32/ArchMiscWindows.cpp
- src/lib/arch/win32/ArchMiscWindows.h
- src/lib/deskflow/DaemonApp.cpp
- src/lib/deskflow/DaemonApp.h
- src/lib/deskflow/ipc/DaemonIpcServer.cpp
- src/lib/deskflow/ipc/DaemonIpcServer.h
- src/lib/gui/core/CoreProcess.cpp
- src/lib/gui/ipc/DaemonIpcClient.cpp
- src/lib/platform/MSWindowsProcess.cpp
- src/lib/platform/MSWindowsWatchdog.cpp
- src/lib/platform/MSWindowsWatchdog.h
Fixes: #8349
Related: #8288
Blockers:
- #8290
- #8334
Todo:
> Refactor Windows daemon to use Qt args and improve logging

- .github/actions/install-dependencies/action.yml
- cmake/Libraries.cmake
- src/lib/deskflow/CMakeLists.txt
- remove the unused libarary gtkpixbuf
> Remove dependency: gtkpixbuf

- .github/actions/install-dependencies/action.yml
- cmake/Libraries.cmake
- deploy/linux/arch/PKGBUILD.in
- deploy/linux/flatpak/org.deskflow.deskflow.yml
- src/lib/deskflow/CMakeLists.txt
- src/lib/deskflow/unix/X11LayoutsParser.cpp
- src/lib/deskflow/unix/X11LayoutsParser.h
Replace the xml parsing with Qt's XML module
Remove the need for pugixml
> refactor: use QtXml in place of pugixml

- CMakeLists.txt
- deploy/linux/org.deskflow.deskflow.metainfo.xml
> Release 1.21.0

- CMakeLists.txt
- deploy/linux/org.deskflow.deskflow.metainfo.xml
- update info for 1.21.1 release
> Release 1.21.1

- .github/workflows/continuous-integration.yml
- For some reason the unix build is trying to run the old setup script.
> ci: Install proper depends for freebsd job

- CMakeLists.txt
- deploy/linux/org.deskflow.deskflow.metainfo.xml
> Release 1.21.2

- src/lib/gui/Logger.cpp
- src/lib/gui/MainWindow.cpp
> fix: Remove unnecessary log line endings and trimming

- src/lib/gui/MainWindow.cpp
fixes #8470
adds menu accelerators back
> fix: Add missing menu accelerators

- src/lib/deskflow/Clipboard.cpp
- Remove asserts in `deskflow/clipboard`. instead check the assertion and handle the case.
> No assert clipboard

- src/lib/gui/Logger.cpp
Fixes: #8489
Only use `Qt::endl` when writing to the output stream; `Q_EMIT newLine` should not include a trailing newline because `appendPlainText` doesn't expect one.
> fix: Use QTextStream to write to stdout and stderr

- src/lib/gui/MainWindow.cpp
- src/lib/gui/MainWindow.h
- src/lib/gui/Messages.cpp
- src/lib/gui/Messages.h
- src/lib/gui/core/CoreProcess.cpp
- src/lib/gui/core/CoreProcess.h
- src/lib/gui/ipc/DaemonIpcClient.cpp
- src/lib/gui/ipc/DaemonIpcClient.h
> feat(daemon): Friendly message on daemon connection error

- src/lib/platform/MSWindowsProcess.cpp
- src/lib/platform/MSWindowsWatchdog.cpp
- src/lib/platform/MSWindowsWatchdog.h
> Improve Windows daemon retry mechanism and related logging

- src/lib/deskflow/ServerApp.cpp
- src/lib/server/ClientListener.cpp
- src/lib/server/ClientListener.h
- src/lib/server/Config.cpp
- src/lib/server/Config.h
- src/lib/server/Server.cpp
- src/lib/server/Server.h
Remove unused code related to the [inverse connection](https://github.com/deskflow/deskflow/pull/8240).
> Remove more code for inverse connection

- README.md
- Condensed and deduped the Synergy sponsor text
- Add more headings to make sections clearer
- Add rewarded bounty badge
- Move values to wiki
[Preview](https://github.com/deskflow/deskflow/blob/clearer-readme/README.md)
> docs: Improve readability of readme

- src/lib/gui/MainWindow.cpp
> fix: Show first server start message only in server mode

- src/lib/base/EventQueue.cpp
- src/lib/base/EventQueue.h
- src/lib/net/IListenSocket.h
- src/lib/net/SecureListenSocket.cpp
- src/lib/net/SecureListenSocket.h
- src/lib/net/TCPListenSocket.cpp
- src/lib/net/TCPListenSocket.h
- src/lib/server/ClientListener.cpp
backport: (most of) https://github.com/input-leap/input-leap/pull/1542
used author to be sure p12tic gets commit credit
> IL Backport: Use some std::unique_prt in event Queue

- src/lib/gui/Messages.cpp
Basic improvements to `deskflow::gui::messages`
- Use AppName in the title for dialogs
- Use QString::append() to add to messages
- Enable translations for messages 
- Use question / information style boxes
> Messages improve

- src/lib/net/TCPSocket.cpp
backport: https://github.com/debauchee/barrier/pull/211
```
Properly deal with a socket that is readable and writable at the same time
Its possible poll() will return that a socket is both readable and
writable.  When this happens TCPSocket::serviceConnected() is
overwriting the result from doWrite() with the result from doRead()
This can cause a situation where doWrite() tried to notify that we
should stop polling if the socket is writable, but the doRead() result
causes that to be ignored.  This results in a tight loop and 100% cpu
usage in SocketMultiplexer::serviceThread() as the poll() call
instantly returns that the socket is writable, but no one cares that
it is.  The issue eventually corrects itself with enough mouse
movement/clicks.
```
> refactor: handle read and write on tcpsocket at the same time

- src/lib/gui/dialogs/AboutDialog.cpp
- src/lib/gui/dialogs/AboutDialog.h
- src/lib/gui/dialogs/AboutDialog.ui
- Added @p12tic  and @shymega to our list of important developers. 
- Adjusted the about dialog's default size
> Add Main Input-leap / Barrier Devs to our Important dev list

- src/lib/platform/PortalInputCapture.cpp
- src/lib/platform/PortalInputCapture.h
Missed some item in PortalInputCapture
- Fix regression in portal input capture that broke the app in debug builds
- More const args for methods
- Fixed up one missed variable name update
> More style items

- src/lib/platform/XWindowsScreen.cpp
Issue https://github.com/deskflow/deskflow/issues/8803
This prevent crash of deskflow-server
> Fix: Crash when m_buttons size is smaller than maxButton

- src/lib/deskflow/KeyMap.cpp
- src/lib/deskflow/KeyState.cpp
Minor nits found while debugging #8168
> Cleanup redundant log and unused includes

- src/lib/server/Server.cpp
We plan to move this elsewhere, but in the meantime, the DEBUG1 logging was too noisy. Also fixed some code style that was bugging me.
> Improve logging in `Server.cpp`

- .github/workflows/continuous-integration.yml
Bump our CI to use v5 of the reuse action
> ci: Use reuse-actionv5

- src/lib/deskflow/KeyMap.cpp
> fix: resolve issues with some swedish characters

- .github/workflows/continuous-integration.yml
> ci: use action checkout v5

- src/lib/deskflow/ClientApp.cpp
- src/lib/deskflow/ServerApp.cpp
- src/lib/gui/core/CoreProcess.cpp
fixes #8905
Add missing IPC level calls.
> fix: missing IPC messages

- src/lib/gui/Messages.cpp
- src/lib/gui/dialogs/ServerConfigDialog.cpp
- src/lib/gui/dialogs/ServerConfigDialog.h
- src/lib/platform/EiKeyState.cpp
- src/lib/platform/XWindowsClipboard.cpp
Address some more sonar issues.
> Sonar cleanup 15

- src/lib/deskflow/unix/X11LayoutsParser.cpp
- src/lib/gui/config/ServerConfig.cpp
- src/lib/gui/core/CoreProcess.cpp
- src/lib/gui/core/CoreProcess.h
- src/lib/gui/dialogs/ScreenSettingsDialog.cpp
- src/lib/gui/dialogs/ScreenSettingsDialog.h
- src/lib/gui/dialogs/ServerConfigDialog.cpp
- src/lib/gui/dialogs/ServerConfigDialog.h
- src/lib/gui/widgets/LogWidget.h
- src/lib/io/StreamBuffer.cpp
- src/lib/net/IDataSocket.h
- src/lib/net/SecureSocket.cpp
- src/lib/platform/EiEventQueueBuffer.cpp
- src/lib/platform/EiEventQueueBuffer.h
- src/lib/platform/EiScreen.cpp
- src/lib/platform/XWindowsKeyState.cpp
- src/lib/platform/XWindowsKeyState.h
- src/lib/server/Config.cpp
- src/lib/server/Server.cpp
- src/lib/server/Server.h
> Sonar cleanup 16

- src/lib/deskflow/ArgsBase.h
- remove unused ArgsBase::m_disableTray
> chore: remove unused ArgsBase::m_disableTray

- src/apps/deskflow-core/deskflow-core.cpp
- src/lib/arch/ArchDaemonNone.cpp
- src/lib/arch/IArchDaemon.h
- src/lib/arch/unix/ArchDaemonUnix.cpp
- src/lib/arch/win32/ArchDaemonWindows.cpp
- src/lib/deskflow/App.cpp
- src/lib/deskflow/App.h
- src/lib/deskflow/AppUtil.h
- src/lib/deskflow/ClientApp.cpp
- src/lib/deskflow/ClientApp.h
- src/lib/deskflow/DaemonApp.cpp
- src/lib/deskflow/IApp.h
- src/lib/deskflow/ServerApp.cpp
- src/lib/deskflow/ServerApp.h
- src/lib/deskflow/unix/AppUtilUnix.cpp
- src/lib/deskflow/unix/AppUtilUnix.h
- src/lib/deskflow/win32/AppUtilWindows.cpp
- src/lib/deskflow/win32/AppUtilWindows.h
- Remove the argc and argv from various app and IApp methods.
Should check this with windows daemon
> App cleanup unused args
